// JR
// ES lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'General',
popup_tab : 'Ventana emergente',
events_tab : 'Eventos',
advanced_tab : 'Avaznzado',
general_props : 'Propiedades generales',
popup_props : 'Propiedades de ventanas emergentes',
event_props : 'Eventos',
advanced_props : 'Propiedades avanzadas',
popup_opts : 'Opciones',
anchor_names : 'Anclas',
target_same : 'Abrir en esta ventana / marco',
target_parent : 'Abrir en ventana padre / marco',
target_top : 'Abrir en el marco superior (reemplaza todos los marcos)',
target_blank : 'Abrir en ventana nueva',
popup : 'Javascript popup',
popup_url : 'URL de la ventana emergente',
popup_name : 'Nombre de la ventana',
popup_return : 'Insertar \'return false\'',
popup_scrollbars : 'Barras de desplazamiento',
popup_statusbar : 'Barra de estado',
popup_toolbar : 'Barra de herramientas',
popup_menubar : 'Barra de menú',
popup_location : 'Barra de localización',
popup_resizable : 'Permitir cambiar el tamaño de la ventana',
popup_dependent : 'Dependientes (sólo Mozilla/Firefox)',
popup_size : 'Tamaño',
popup_position : 'Posición (X/Y)',
id : 'Id',
style: 'Estilo',
classes : 'Clases',
target_name : 'Nombre del destino',
langdir : 'Dirección del lenguaje',
target_langcode : 'Lenguaje destino',
langcode : 'Código del lenguaje',
encoding : 'Codificación de caracteres del destino',
mime : 'Tipo MIME del destiono',
rel : 'Relación de la página con el destino',
rev : 'Relación del destino con la página',
tabindex : 'Orden de tabulación',
accesskey : 'Tecla de acceso',
ltr : 'Izquierda a derecha',
rtl : 'Derecha a izquierda',
class_label: 'Clase',
periferia_enlace: 'Opciones generales',
div_label : 'Clase del envoltorio',
tamano_label: 'Tama&ntilde;o (X.XX MB)',
resumen_label: 'Incluir enlace al resumen'
});
