// ES lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'General',
popup_tab : 'Popup',
events_tab : 'Eventos',
advanced_tab : 'Advanzado',
general_props : 'Propiedades generales',
popup_props : 'Propiedades del popup',
event_props : 'Eventos',
advanced_props : 'Propiedades avanzadas',
popup_opts : 'Opciones',
anchor_names : 'Anclas',
target_same : 'Abrir en esta ventana/frame',
target_parent : 'Abrir en ventana/frame padre',
target_top : 'Abrir en ventana superior (reemplaza todos los frames)',
target_blank : 'Abrir en ventana nueva',
popup : 'Popup Javascript',
popup_url : 'URL del popup',
popup_name : 'Nombre de la ventana',
popup_return : 'Insertar \'return false\'',
popup_scrollbars : 'Mostrar barras de desplazamiento (scroll)',
popup_statusbar : 'Mostrar barra de estado',
popup_toolbar : 'Mostrar herramientas',
popup_menubar : 'Mostrar la barra de men&uacute;',
popup_location : 'Mostrar la barra de direcci&oacute;n',
popup_resizable : 'Permitir redimensi&oacute;n',
popup_dependent : 'Dependiente (s&oacute;lo Mozilla/Firefox)',
popup_size : 'Tama&ntilde;o',
popup_position : 'Posici&oacute;n (X/Y)',
id : 'Id',
style: 'Estilo',
classes : 'Clases',
target_name : 'Nombre del destino',
langdir : 'Direcci&oacute;n del idioma',
target_langcode : 'Idioma destino',
langcode : 'C&oacute;digo idioma',
encoding : 'Codificaci&oacute;n destino',
mime : 'Tipo MIME destino',
rel : 'Relaci&oacute;n p&aacute;gina-destino',
rev : 'Relaci&oacute;n destino-p&aacute;gina',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Izquierda a derecha,
rtl : 'Derecha a izquierda'
});