// ES lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'General',
popup_tab : 'Popup',
events_tab : 'Eventos',
advanced_tab : 'Avanzado',
general_props : 'Propiedades generales',
popup_props : 'Propiedades del popup',
event_props : 'Eventos',
advanced_props : 'Propiedades avanzadas',
popup_opts : 'Opciones',
anchor_names : 'Anclas',
target_same : 'Abrir en esta ventana/frame',
target_parent : 'Abrir en ventana/frame padre',
target_top : 'Abrir en ventana superior (reemplaza todos los frames)',
target_blank : 'Abrir en ventana nueva',
popup : 'Popup Javascript',
popup_url : 'URL del popup',
popup_name : 'Nombre de la ventana',
popup_return : 'Insertar \'return false\'',
popup_scrollbars : 'Mostrar barras desplazamiento (scroll)',
popup_statusbar : 'Mostrar barra de estado',
popup_toolbar : 'Mostrar herramientas',
popup_menubar : 'Mostrar la barra de men\u00FA',
popup_location : 'Mostrar la barra de direcci\u00F3n',
popup_resizable : 'Permitir redimensi\u00F3n',
popup_dependent : 'Dependiente (s\u00F3lo Mozilla/Firefox)',
popup_size : 'Tama\u00F1o',
popup_position : 'Posici\u00F3n (X/Y)',
id : 'Id',
style: 'Estilo',
classes : 'Clases',
target_name : 'Nombre del destino',
langdir : 'Direcci\u00F3n del idioma',
target_langcode : 'Idioma destino',
langcode : 'C\u00F3digo idioma',
encoding : 'Codificaci\u00F3n destino',
mime : 'Tipo MIME destino',
rel : 'Relaci\u00F3n p\u00E1gina-destino',
rev : 'Relaci\u00F3n destino-p\u00E1gina',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Izquierda a derecha',
rtl : 'Derecha a izquierda'
});