tinymce.addI18n('all',{
"Cut": _("Cut"),
"Heading 5": _("Heading 5"),
"Header 2": _("Header 2"),
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": _("Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead."),
"Heading 4": _("Heading 4"),
"Div": _("Div"),
"Heading 2": _("Heading 2"),
"Paste": _("Paste"),
"Close": _("Close"),
"Font Family": _("Font Family"),
"Pre": _("Pre"),
"Align right": _("Align right"),
"New document": _("New document"),
"Blockquote": _("Blockquote"),
"Numbered list": _("Numbered list"),
"Heading 1": _("Heading 1"),
"Headings": _("Headings"),
"Increase indent": _("Increase indent"),
"Formats": _("Formats"),
"Headers": _("Headers"),
"Select all": _("Select all"),
"Header 3": _("Header 3"),
"Blocks": _("Blocks"),
"Undo": _("Undo"),
"Strikethrough": _("Strikethrough"),
"Bullet list": _("Bullet list"),
"Header 1": _("Header 1"),
"Superscript": _("Superscript"),
"Clear formatting": _("Clear formatting"),
"Font Sizes": _("Font Sizes"),
"Subscript": _("Subscript"),
"Header 6": _("Header 6"),
"Redo": _("Redo"),
"Paragraph": _("Paragraph"),
"Ok": _("Ok"),
"Bold": _("Bold"),
"Code": _("Code"),
"Italic": _("Italic"),
"Align center": _("Align center"),
"Header 5": _("Header 5"),
"Heading 6": _("Heading 6"),
"Heading 3": _("Heading 3"),
"Decrease indent": _("Decrease indent"),
"Header 4": _("Header 4"),
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": _("Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off."),
"Underline": _("Underline"),
"Cancel": _("Cancel"),
"Justify": _("Justify"),
"Inline": _("Inline"),
"Copy": _("Copy"),
"Align left": _("Align left"),
"Visual aids": _("Visual aids"),
"Lower Greek": _("Lower Greek"),
"Square": _("Square"),
"Default": _("Default"),
"Lower Alpha": _("Lower Alpha"),
"Circle": _("Circle"),
"Disc": _("Disc"),
"Upper Alpha": _("Upper Alpha"),
"Upper Roman": _("Upper Roman"),
"Lower Roman": _("Lower Roman"),
"Name": _("Name"),
"Anchor": _("Anchor"),
"You have unsaved changes are you sure you want to navigate away?": _("You have unsaved changes are you sure you want to navigate away?"),
"Restore last draft": _("Restore last draft"),
"Special character": _("Special character"),
"Source code": _("Source code"),
"B": _("B"),
"R": _("R"),
"G": _("G"),
"Color": _("Color"),
"Right to left": _("Right to left"),
"Left to right": _("Left to right"),
"Emoticons": _("Emoticons"),
"Robots": _("Robots"),
"Document properties": _("Document properties"),
"Title": _("Title"),
"Keywords": _("Keywords"),
"Encoding": _("Encoding"),
"Description": _("Description"),
"Author": _("Author"),
"Fullscreen": _("Fullscreen"),
"Horizontal line": _("Horizontal line"),
"Horizontal space": _("Horizontal space"),
"Insert/edit image": _("Insert/edit image"),
"General": _("General"),
"Advanced": _("Advanced"),
"Source": _("Source"),
"Border": _("Border"),
"Constrain proportions": _("Constrain proportions"),
"Vertical space": _("Vertical space"),
"Image description": _("Image description"),
"Style": _("Style"),
"Dimensions": _("Dimensions"),
"Insert image": _("Insert image"),
"Zoom in": _("Zoom in"),
"Contrast": _("Contrast"),
"Back": _("Back"),
"Gamma": _("Gamma"),
"Flip horizontally": _("Flip horizontally"),
"Resize": _("Resize"),
"Sharpen": _("Sharpen"),
"Zoom out": _("Zoom out"),
"Image options": _("Image options"),
"Apply": _("Apply"),
"Brightness": _("Brightness"),
"Rotate clockwise": _("Rotate clockwise"),
"Rotate counterclockwise": _("Rotate counterclockwise"),
"Edit image": _("Edit image"),
"Color levels": _("Color levels"),
"Crop": _("Crop"),
"Orientation": _("Orientation"),
"Flip vertically": _("Flip vertically"),
"Invert": _("Invert"),
"Insert date/time": _("Insert date/time"),
"Remove link": _("Remove link"),
"Url": _("Url"),
"Text to display": _("Text to display"),
"Anchors": _("Anchors"),
"Insert link": _("Insert link"),
"New window": _("New window"),
"None": _("None"),
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": _("The URL you entered seems to be an external link. Do you want to add the required http:// prefix?"),
"Target": _("Target"),
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": _("The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?"),
"Insert/edit link": _("Insert/edit link"),
"Insert/edit video": _("Insert/edit video"),
"Poster": _("Poster"),
"Alternative source": _("Alternative source"),
"Paste your embed code below:": _("Paste your embed code below:"),
"Insert video": _("Insert video"),
"Embed": _("Embed"),
"Nonbreaking space": _("Nonbreaking space"),
"Page break": _("Page break"),
"Paste as text": _("Paste as text"),
"Preview": _("Preview"),
"Print": _("Print"),
"Save": _("Save"),
"Could not find the specified string.": _("Could not find the specified string."),
"Replace": _("Replace"),
"Next": _("Next"),
"Whole words": _("Whole words"),
"Find and replace": _("Find and replace"),
"Replace with": _("Replace with"),
"Find": _("Find"),
"Replace all": _("Replace all"),
"Match case": _("Match case"),
"Prev": _("Prev"),
"Spellcheck": _("Spellcheck"),
"Finish": _("Finish"),
"Ignore all": _("Ignore all"),
"Ignore": _("Ignore"),
"Add to Dictionary": _("Add to Dictionary"),
"Insert row before": _("Insert row before"),
"Rows": _("Rows"),
"Height": _("Height"),
"Paste row after": _("Paste row after"),
"Alignment": _("Alignment"),
"Border color": _("Border color"),
"Column group": _("Column group"),
"Row": _("Row"),
"Insert column before": _("Insert column before"),
"Split cell": _("Split cell"),
"Cell padding": _("Cell padding"),
"Cell spacing": _("Cell spacing"),
"Row type": _("Row type"),
"Insert table": _("Insert table"),
"Body": _("Body"),
"Caption": _("Caption"),
"Footer": _("Footer"),
"Delete row": _("Delete row"),
"Paste row before": _("Paste row before"),
"Scope": _("Scope"),
"Delete table": _("Delete table"),
"H Align": _("H Align"),
"Top": _("Top"),
"Header cell": _("Header cell"),
"Column": _("Column"),
"Row group": _("Row group"),
"Cell": _("Cell"),
"Middle": _("Middle"),
"Cell type": _("Cell type"),
"Copy row": _("Copy row"),
"Row properties": _("Row properties"),
"Table properties": _("Table properties"),
"Bottom": _("Bottom"),
"V Align": _("V Align"),
"Header": _("Header"),
"Right": _("Right"),
"Insert column after": _("Insert column after"),
"Cols": _("Cols"),
"Insert row after": _("Insert row after"),
"Width": _("Width"),
"Cell properties": _("Cell properties"),
"Left": _("Left"),
"Cut row": _("Cut row"),
"Delete column": _("Delete column"),
"Center": _("Center"),
"Merge cells": _("Merge cells"),
"Insert template": _("Insert template"),
"Templates": _("Templates"),
"Background color": _("Background color"),
"Custom...": _("Custom..."),
"Custom color": _("Custom color"),
"No color": _("No color"),
"Text color": _("Text color"),
"Show blocks": _("Show blocks"),
"Show invisible characters": _("Show invisible characters"),
"Words: {0}": _("Words: {0}"),
"Insert": _("Insert"),
"File": _("File"),
"Edit": _("Edit"),
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": _("Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help"),
"Tools": _("Tools"),
"View": _("View"),
"Table": _("Table"),
"Format": _("Format")
});