tinymce.addI18n('all',{
"Cut": _("Cut"),
"Heading 5": _("Heading 5"),
"Header 2": _("Heading 2"),
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": _("Currently not supported by your browser, use keyboard shortcuts instead."),
"Heading 4": _("Heading 4"),
"Div": "DIV",
"Heading 2": _("Heading 2"),
"Paste": _("Paste"),
"Close": _("Close"),
"Font Family": _("Font Family"),
"Pre": "PRE",
"Align right": _("Align Right"),
"New document": _("New Document"),
"Blockquote": _("Block Quote"),
"Numbered list": _("Insert/Remove Numbered List"),
"Heading 1": _("Heading 1"),
"Headings": _("Header"),
"Increase indent": _("Increase Indent"),
"Formats": _("Formats"),
"Headers": _("Headers"),
"Select all": _("Select All"),
"Header 3": _("Heading 3"),
"Blocks": _("Block"),
"Undo": _("Undo"),
"Strikethrough": _("Strikethrough"),
"Bullet list": _("Insert/Remove Bulleted List"),
"Header 1": _("Heading 1"),
"Superscript": _("Superscript"),
"Clear formatting": _("Remove Formatting"),
"Font Sizes": _("Font Size"),
"Subscript": _("Subscript"),
"Header 6": _("Heading 6"),
"Redo": _("Redo"),
"Paragraph": _("Paragraph"),
"Ok": _("Ok"),
"Bold": _("Bold"),
"Code": _("Code"),
"Italic": _("Italic"),
"Align center": _("Align Center"),
"Header 5": _("Heading 5"),
"Heading 6": _("Heading 6"),
"Heading 3": _("Heading 3"),
"Decrease indent": _("Decrease Indent"),
"Header 4": _("Heading 4"),
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": _("Paste is now in plain text mode. Click again to toggle back to regular paste mode. After you paste something you will be returned to regular paste mode."),
"Underline": _("Underline"),
"Cancel": _("Cancel"),
"Justify": _("Full"),
"Inline": _("Inline"),
"Copy": _("Copy"),
"Align left": _("Align Left"),
"Visual aids": _("Show/Hide Visual Control Characters"),
"Lower Greek": _("Lower Greek"),
"Square": _("Square"),
"Default": _("Default"),
"Lower Alpha": _("Lower Alpha"),
"Circle": _("Circle"),
"Disc": _("Disc"),
"Upper Alpha": _("Upper Alpha"),
"Upper Roman": _("Upper Roman"),
"Lower Roman": _("Lower Roman"),
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": _("Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores."),
"Name": _("Name"),
"Anchor": _("Anchor"),
"Id": "ID",
"You have unsaved changes are you sure you want to navigate away?": _("The changes you made will be lost if you navigate away from this page."),
"Restore last draft": _("Restore last draft"),
"Special character": _("Special character"),
"Source code": _("Edit source code"),


"B": "B",
"R": "R",
"G": "G",
"Color": _("Color"),
"Right to left": _("Right to Left"),
"Left to right": _("Left to Right"),
"Emoticons": _("Emoticons"),
"Robots": _("Robots"),
"Document properties": _("Document Properties"),
"Title": _("Title"),
"Keywords": _("Keywords"),
"Encoding": _("Character Encoding"),
"Description": _("Description"),
"Author": _("Author"),
"Fullscreen": _("Full Screen"),
"Horizontal line": _("Horizontal Line"),
"Horizontal space": _("Horizontal Space"),
"Insert/edit image": _("Insert/Edit Image"),
"General": _("General"),
"Advanced": _("Advanced"),
"Source": _("Source"),
"Border": _("Border"),
"Constrain proportions": _("Constrain proportions"),
"Vertical space": _("Vertical Space"),
"Image description": _("Image Description"),
"Image Title": _("Image Title"),
"Style": _("Style"),
"Dimensions": _("Dimensions"),









"Image options": _("Image Options"),
"Apply": _("Apply"),









"Date/time": _("Date/Time"),
"Insert date/time": _("Date/Time"),
"Remove link": _("Unlink"),
"Url": _("URL"),
"Text to display": _("Text to display"),
"Anchors": _("Anchors"),
"Insert link": _("Insert/Edit Link"),
"Link": _("Link"),
"New window": _("New Window"),
"None": _("None"),
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": _("The URL you entered seems to be an external link. Do you want to add the required http:// prefix?"),

"Target": _("Target"),
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": _("The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?"),
"Insert/edit link": _("Insert/Edit Link"),
"Insert/edit video": _("Insert/Edit Embedded Media"),

"Alternative source": _("Alternative source"),
"Paste your embed code below:": _("Use CTRL+V on your keyboard to paste the code into the window."),

"Poster": _("Poster"),


"Nonbreaking space": _("Non-Breaking Space"),
"Page break": _("Page Break"),
"Paste as text": _("Paste as Plain Text"),
"Preview": _("Preview"),
"Print": _("Print"),
"Save": _("Save"),
"Could not find the specified string.": _("The term could not be found"),
"Replace": _("Replace"),
"Next": _("Next"),
"Whole words": _("Whole Words"),
"Find and replace": _("Find and Replace"),
"Replace with": _("Replace with"),
"Find": _("Find"),
"Replace all": _("Replace all"),
"Match case": _("Match Case"),
"Prev": _("Previous"),

"Finish": _("Finish"),
"Ignore all": _("Ignore All"),
"Ignore": _("Ignore Word"),

"Insert row before": _("Insert Row Before"),
"Rows": _("Rows"),
"Height": _("Height"),
"Paste row after": _("Paste Row After"),
"Alignment": _("Alignment"),
"Border color": _("Border color"),
"Column group": _("Col Group"),
"Row": _("Row"),
"Insert column before": _("Insert Column Before"),
"Split cell": _("Split Cell"),
"Cell padding": _("Cell Padding"),
"Cell spacing": _("Cell Spacing"),
"Row type": _("Row Type"),
"Insert table": _("Insert Table"),
"Body": _("Body"),
"Caption": _("Table Caption"),
"Footer": _("Footer"),
"Delete row": _("Delete Row"),
"Paste row before": _("Paste Table Row Before"),
"Scope": _("Scope"),
"Delete table": _("Delete Table"),
"H Align": _("Horizontal Position"),
"Top": _("Top"),
"Header cell": _("Header Cell"),
"Column": _("Column"),
"Row group": _("Row Group"),
"Cell": _("Cell"),
"Middle": _("Middle"),
"Cell type": _("Cell Type"),
"Copy row": _("Copy Row"),
"Row properties": _("Table Row Properties"),
"Table properties": _("Table Properties"),
"Bottom": _("Bottom"),
"V Align": _("Vertical Alignment"),
"Header": _("Header"),
"Right": _("Right"),
"Insert column after": _("Insert Column After"),
"Cols": _("Columns"),
"Insert row after": _("Insert Row After"),
"Width": _("Width"),
"Cell properties": _("Table Cell Properties"),
"Left": _("Left"),
"Cut row": _("Cut Table Row"),
"Delete column": _("Delete Column"),
"Center": _("Center"),
"Merge cells": _("Merge Table Cells"),
"Insert template": _("Predefined Template Content"),
"Templates": _("Templates"),
"Template": _("Template"),
"Background color": _("Background color"),
"Custom...": _("Custom..."),
"Custom color": _("Custom color"),
"No color": _("No color"),
"Text color": _("Text color"),

"Show blocks": _("Show blocks"),
"Show invisible characters": _("Show invisible characters"),
"Words: {0}": _("Words: {0}"),
"Insert": _("Insert"),
"File": _("File"),
"Edit": _("Edit"),
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": _("Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help"),
"Tools": _("Tools"),
"View": _("View"),
"Table": _("Table"),
"Format": _("Format"),
"Preformatted": _("Preformatted"),
// JavaScript Popup
"Popup URL": _("Popup URL"),
"JavaScript Popup": _("JavaScript Popup"),
"Window Name": _("Window Name"),
"Size": _("Size"),
"Position (X/Y)": _("Position (X/Y)"),
"Options": _("Options"),
"Show Location Bar": _("Show Location Bar"),
"Show Scrollbars": _("Show Scrollbars"),
"Show Menu Bar": _("Show Menu Bar"),
"Make Window Resizable": _("Make Window Resizable"),
"Show Toolbars": _("Show Toolbars"),
"Show Status Bar": _("Show Status Bar"),
"Insert 'return false'": _("Insert 'return false'"),
"Events": _("Events")
});