tinyMCE.addI18n('ca.media_dlg',{list:"Llista",file:"Fitxer/URL",advanced:"Avan\u00e7at",general:"General",title:"Insereix / edita multim\u00e8dia incrustada","align_top_left":"Superior esquerra","align_center":"Centre","align_left":"Esquerra","align_bottom":"Inferior","align_right":"Dreta","align_top":"Superior","qt_stream_warn":"Els recursos rtsp fets flux s\'haurien d\'afegir al camp QT Src sota la pestanya avan\u00e7ada.\nTamb\u00e9 haur\u00edeu d\'afegir una versi\u00f3 no feta flux al camp Src..",qtsrc:"QT Src",progress:"Progr\u00e9s",sound:"S\u00f2",swstretchvalign:"Alineaci\u00f3 vertical de l\'extensor",swstretchhalign:"Alineaci\u00f3 horitzontal de l\'extensor",swstretchstyle:"Estil de l\'extensor",scriptcallbacks:"Crides de retorn a script","align_top_right":"Superior dreta",uimode:"Mode UI",rate:"Velocitat",playcount:"Compte de reproducci\u00f3",defaultframe:"Marc per defecte",currentposition:"Posici\u00f3 actual",currentmarker:"Retolador actual",captioningid:"Id nominal",baseurl:"URL base",balance:"Equilibri",windowlessvideo:"V\u00eddeo sense finestra",stretchtofit:"Estirar fins a encaixar",mute:"Silenci",invokeurls:"Invoca els URL",fullscreen:"Pantalla completa",enabled:"Habilitat",autostart:"Inici autom\u00e0tic",volume:"Volumen",target:"Dest\u00ed",qtsrcchokespeed:"Velocitat",href:"Href",endtime:"Fi",starttime:"Inici",enablejavascript:"Habilita el javascript",correction:"Sense correcci\u00f3",targetcache:"Target cache",playeveryframe:"Reprodueix cada marc",kioskmode:"Mode quiosc",controller:"Controlador",menu:"Mostra el men\u00fa",loop:"Bucle",play:"Reproducci\u00f3 autom\u00e0tica",hspace:"Espai horitzontal",vspace:"Espai vertical","class_name":"Classe",name:"Nom",id:"Id",type:"Tipus",size:"Dimensions",preview:"Previsualitzaci\u00f3","constrain_proportions":"Mant\u00e9 les proporcions",controls:"Controls",numloop:"Nre. bucles",console:"Consola",cache:"Mem\u00f2ria cau",autohref:"AutoHREF",liveconnect:"SWLiveConnect",flashvars:"Flashvars",base:"Base",bgcolor:"Fons",wmode:"Mode W",salign:"Alinea S",align:"Alinea",scale:"Escala",quality:"Qualitat",shuffle:"Shuffle",prefetch:"Prec\u00e0rrega",nojava:"Sense java",maintainaspect:"Mant\u00e9 l\'aspecte",imagestatus:"Estat de la imatge",center:"Alinea al centre",autogotourl:"URL goto autom\u00e0tic","shockwave_options":"Opcions del Shockwave","rmp_options":"Opcions del Real media player","wmp_options":"Opcions del Windows media player","qt_options":"Opcions del Quicktime","flash_options":"Opcions del Flash",hidden:"Ocult","align_bottom_left":"Inferior esquerra","align_bottom_right":"Inferior dreta",flash:"Flash (swf, flv, mp3)",quicktime:"QuickTime (mov, mp4, mpeg)","embedded_audio_options":"Opcions d\'audio incrustat",windowsmedia:"Windows Media (wmv, wma)",realmedia:"Real Media (ram)",shockwave:"shockwave",audio:"HTML5 audio (ogg)",video:"HTML5 video (ogv/ogg, webm)","html5_video_options":"Opcions de v\u00eddeo HTML5",altsource1:"Font alternatiu 1",altsource2:"Font alternatiu 2",preload:"Pre-c\u00e0rrega",poster:"Anunci",source:"Font","html5_audio_options":"Opcions d\'audio","preload_none":"No precarregar","preload_metadata":"Precarregar metadata de v\u00eddeo","preload_auto":"Deixar decidir a l\'usuari del navegador",iframe:"iframe",embeddedaudio:"embeddedaudio",
// The New eXeLearning
selected_file : "Fitxer seleccionat",
html5_warning : "HTML5 no funciona en tots els navegadors",
recommended_type : "Tipus recomanat",
confirm_question : "Voleu continuar sense fer cap canvi?",
preview_error : "No s'ha pogut generar una previsualitzaci\u00F3",
video_download_file_warning : "Si el navegador de l'usuari no pot reproduir el v\u00EDdeo es mostrar\u00e0 un enlla\u00E7 al fitxer.",
audio_download_file_warning : "Si el navegador de l'usuari no pot reproduir l'\u00e0udio es mostrar\u00e0 un enlla\u00E7 al fitxer.",
use_mediaelement : "Usar reproductor JavaScript",
"tab_caption":"Encap\u00E7alament i peu",
"recognition":"T\u00EDtol i atribuci\u00F3",
"header":"Encap\u00E7alament",
"media_title":"T\u00EDtol de l\'obra",
"media_title_link":"Enlla\u00E7 del t\u00EDtol",
"author_name":"Origen/autor",
"author_name_link":"Enlla\u00E7 origen/autor",
"caption_license":"Llic\u00E8ncia",
"caption_select_license":"Selecciona...",
"public_domain":"Domini p\u00FAblic",
"all_rights_reserved":"Tots els drets reservats",
"block_presentation":"Presentaci\u00F3",
"text_align":"Alineaci\u00F3 del text",
"align_left":"Esquerra",
"align_center":"Centre",
"align_right":"Dreta",
"image_and_caption_position":"Posici\u00F3 del conjunt",
"position_center":"Centre",
"position_normal":"Normal",
"image_and_caption_float":"Comportament",
"position_left":"A l\'esquerra del text",
"position_right":"A la dreta del text",
"image_and_caption_margin":"Marge del conjunt",
"caption_explanation":"L\'encap\u00E7alament i el peu no seran editables des d\'aquest di\u00E0leg.",
"caption_warning":"L\'encap\u00E7alament i el peu no es poden editar des d\'aquest di\u00E0leg. Podeu modificar-los o esborrar-los editant el vostre text."
// The New eXeLearning
});