tinyMCE.addI18n('en.media_dlg',{list:"List",file:"File/URL",advanced:"Advanced",general:"General",title:"Insert/Edit Embedded Media","align_top_left":"Top Left","align_center":"Center","align_left":"Left","align_bottom":"Bottom","align_right":"Right","align_top":"Top","qt_stream_warn":"Streamed RTSP resources should be added to the QT Source field under the Advanced tab.\nYou should also add a non-streamed version to the Source field.",qtsrc:"QT Source",progress:"Progress",sound:"Sound",swstretchvalign:"Stretch V-Align",swstretchhalign:"Stretch H-Align",swstretchstyle:"Stretch Style",scriptcallbacks:"Script Callbacks","align_top_right":"Top Right",uimode:"UI Mode",rate:"Rate",playcount:"Play Count",defaultframe:"Default Frame",currentposition:"Current Position",currentmarker:"Current Marker",captioningid:"Captioning ID",baseurl:"Base URL",balance:"Balance",windowlessvideo:"Windowless Video",stretchtofit:"Stretch to Fit",mute:"Mute",invokeurls:"Invoke URLs",fullscreen:"Full Screen",enabled:"Enabled",autostart:"Auto Start",volume:"Volume",target:"Target",qtsrcchokespeed:"Choke Speed",href:"HREF",endtime:"End Time",starttime:"Start Time",enablejavascript:"Enable JavaScript",correction:"No Correction",targetcache:"Target Cache",playeveryframe:"Play Every Frame",kioskmode:"Kiosk Mode",controller:"Controller",menu:"Show Menu",loop:"Loop",play:"Auto Play",hspace:"H-Space",vspace:"V-Space","class_name":"Class",name:"Name",id:"ID",type:"Type",size:"Dimensions",preview:"Preview","constrain_proportions":"Constrain Proportions",controls:"Controls",numloop:"Num Loops",console:"Console",cache:"Cache",autohref:"Auto HREF",liveconnect:"SWLiveConnect",flashvars:"Flash Vars",base:"Base",bgcolor:"Background",wmode:"WMode",salign:"SAlign",align:"Align",scale:"Scale",quality:"Quality",shuffle:"Shuffle",prefetch:"Prefetch",nojava:"No Java",maintainaspect:"Maintain Aspect",imagestatus:"Image Status",center:"Center",autogotourl:"Auto Goto URL","shockwave_options":"Shockwave Options","rmp_options":"Real Media Player Options","wmp_options":"Windows Media Player Options","qt_options":"QuickTime Options","flash_options":"Flash Options",hidden:"Hidden","align_bottom_left":"Bottom Left","align_bottom_right":"Bottom Right","html5_video_options":"HTML5 Video Options",altsource1:"Alternative source 1",altsource2:"Alternative source 2",preload:"Preload",poster:"Poster",source:"Source","html5_audio_options":"Audio Options","preload_none":"Don\'t Preload","preload_metadata":"Preload video metadata","preload_auto":"Let user\'s browser decide", "embedded_audio_options":"Embedded Audio Options", video:"HTML5 video (ogv/ogg, webm)", audio:"HTML5 audio (ogg)", flash:"Flash (swf, flv, mp3)", quicktime:"QuickTime (mov, mp4, mpeg)", shockwave:"Shockwave", windowsmedia:"Windows Media (wmv, wma)", realmedia:"Real Media (ram)", iframe:"Iframe", embeddedaudio:"Embedded Audio",
// The New eXeLearning
selected_file : "Selected file",
html5_warning : "HTML5 does not work in all browsers",
recommended_type : "Recommended type",
confirm_question : "Continue without changing your settings?",
preview_error : "Could not generate preview",
video_download_file_warning : "For Web browsers that do not support this video, a link to the video file will be displayed.",
audio_download_file_warning : "For Web browsers that do not support this audio, a link to the audio file will be displayed.",
"tab_caption":"Header and caption",
"recognition":"Title and attribution",
"header":"Header",
"media_title":"Image title",
"media_title_link":"Title link",
"author_name":"Source/author",
"author_name_link":"Source/author link",
"caption_license":"License",
"caption_select_license":"Choose a license...",
"public_domain":"Public domain",
"all_rights_reserved":"All rights reserved",
"block_presentation":"Presentation",
"text_align":"Text align",
"align_left":"Left",
"align_center":"Center",
"align_right":"Right",
"image_and_caption_position":"Group position",
"position_center":"Center",
"position_normal":"None",
"image_and_caption_float":"Float",
"position_left":"Left",
"position_right":"Right",
"image_and_caption_margin":"Group margin",
"caption_explanation":"You would not be able to edit the header and the caption from this dialog.",
"caption_warning":"The header and the caption can't be edited from this dialog. You can change or remove them editing the text itself."
// The New eXeLearning
}); 