tinyMCE.addI18n('eu.media_dlg',{list:"Zerrenda",file:"Fitxategia/URL",advanced:"Aurreratua",general:"Orokorra",title:"Sartu / editatu ahokatutako euskarria","align_top_left":"Goian ezkerran","align_center":"Erdian","align_left":"Ezkerrean","align_bottom":"Behean","align_right":"Eskuinean","align_top":"Goian","qt_stream_warn":"Streaming bidez ematen diren rtsp baliabideak aurreratuak fitxa n dagoen QT Src eremuan gehitu behar dira.\n Streaming gabeko bertsio bat ere gehitu beharko zenuke.",qtsrc:"QT Src",progress:"Aurrerapena",sound:"Soinua",swstretchvalign:"Stretch V-Align",swstretchhalign:"Stretch H-Align",swstretchstyle:"Stretch style",scriptcallbacks:"Script callbacks","align_top_right":"Goian eskuinean",uimode:"UI Modua",rate:"Rate",playcount:"Play count",defaultframe:"Lehenetsitako fotograma",currentposition:"Uneko posizioa",currentmarker:"Current marker",captioningid:"Captioning id",baseurl:"Base URL",balance:"Balanzea",windowlessvideo:"Lehiogabeko bideoa",stretchtofit:"Neurrikoa izateko zabaldu",mute:"Ixilik",invokeurls:"URLa deitu",fullscreen:"Pantaila osoa",enabled:"Gaituta",autostart:"Automatikoki hasi",volume:"Bolumena",target:"Helburua",qtsrcchokespeed:"Talka abiadura",href:"Href",endtime:"Noiz bukatu",starttime:"Noiz hasi",enablejavascript:"Gaitu JavaScript",correction:"Zuzenketarik ez",targetcache:"Helburu katxea",playeveryframe:"Marko guztiak erreproduzitu",kioskmode:"Kiosko modua",controller:"Controller",menu:"Erakutsi menua",loop:"Begizta",play:"Auto play",hspace:"H-Space",vspace:"V-Space","class_name":"Klasea",name:"Izena",id:"Id",type:"Mota",size:"Tamaina",preview:"Aurrebista","constrain_proportions":"Itxura erlazioa blokeatu",controls:"Kontrolak",numloop:"Begizta kopurua",console:"Konsola",cache:"Katxea",autohref:"AutoHREF",liveconnect:"SWLiveConnect",flashvars:"Flashvars",base:"Oinarria",bgcolor:"Atzea",wmode:"WMode",salign:"SAlign",align:"Lerrokatu",scale:"Eskalatu",quality:"Kalitatea",shuffle:"Shuffle",prefetch:"Prefetch",nojava:"Java ez",maintainaspect:"Itxura mantendu",imagestatus:"Irudi edoera",center:"Erdian",autogotourl:"Automatikoi joan URLra","shockwave_options":"Shockwave aukerak","rmp_options":"Real media player aukerak","wmp_options":"Windows media player aukerak","qt_options":"Quicktime aukerak","flash_options":"Flash aukerak",hidden:"Ezkutuan","align_bottom_left":"Behean ezkerrean","align_bottom_right":"Behean eskuinean",flash:"Flash (swf, flv, mp3)",quicktime:"QuickTime (mov, mp4, mpeg)",windowsmedia:"Windows Media (wmv, wma)",realmedia:"Real Media (ram)",shockwave:"shockwave",audio:"HTML5 audio (ogg)",video:"HTML5 video (ogv/ogg, webm)",iframe:"iframe","html5_video_options":"HTML5 bideo aukerak",altsource1:"Ordezko iturria 1",altsource2:"Ordezko iturria 2",preload:"Aurrekargatu",poster:"Posterra",source:"Iturria","html5_audio_options":"Audio aukerak","preload_none":"Ez aurrekargatu","preload_metadata":"Bideoaren metadatuak aurrekargatu","preload_auto":"Nabitzaileari erabakitzen utzi",
// The New eXeLearning
selected_file : "Aukeratutako fitxategia",
html5_warning : "HTML5 ez dabil nabigatzaile guztietan",
recommended_type : "Gomendatutako mota",
confirm_question : "Aldaketarik gabe jarraitu?",
preview_error : "Aurrebista ezin izan da sortu",
video_download_file_warning : "Erabiltzailearen nabigatzaileak ezin badu bideoa erreproduzitu, fitxategiaren esteka bistaratuko da.",
audio_download_file_warning : "Erabiltzailearen nabigatzaileak ezin badu audioa erreproduzitu, fitxategiaren esteka bistaratuko da.",
"tab_caption":"Encabezado y pie",
use_mediaelement : "Use MediaElement.js audio and video player",
"recognition":"T\u00EDtulo y reconocimiento",
"header":"Encabezado",
"media_title":"T\u00EDtulo de la obra",
"media_title_link":"Enlace del t\u00EDtulo",
"author_name":"Origen/autor",
"author_name_link":"Enlace orig./autor",
"caption_license":"Licencia",
"caption_select_license":"Seleccionar...",
"public_domain":"Dominio p\u00FAblico",
"all_rights_reserved":"Todos los derechos reservados",
"block_presentation":"Presentaci\u00F3n",
"text_align":"Alineaci\u00F3n del texto",
"align_left":"Izquierda",
"align_center":"Centro",
"align_right":"Derecha",
"image_and_caption_position":"Posici\u00F3n del conjunto",
"position_center":"Centro",
"position_normal":"Normal",
"image_and_caption_float":"Comportamiento",
"position_left":"A la izquierda del texto",
"position_right":"A la derecha del texto",
"image_and_caption_margin":"Margen del conjunto",
"caption_explanation":"El encabezado y el pie no ser\u00E1n editables desde este di\u00E1logo.",
"caption_warning":"El encabezado y el pie no se pueden editar desde este di\u00E1logo. Puede modificarlos o borrarlos editando su texto."
// The New eXeLearning
});