tinyMCE.addI18n('eu.media_dlg',{list:"Zerrenda",file:"Fitxategia/URL",advanced:"Aurreratua",general:"Orokorra",title:"Sartu / editatu ahokatutako euskarria","align_top_left":"Goian ezkerran","align_center":"Erdian","align_left":"Ezkerrean","align_bottom":"Behean","align_right":"Eskuinean","align_top":"Goian","qt_stream_warn":"Streaming bidez ematen diren rtsp baliabideak aurreratuak fitxa n dagoen QT Src eremuan gehitu behar dira.\n Streaming gabeko bertsio bat ere gehitu beharko zenuke.",qtsrc:"QT Src",progress:"Aurrerapena",sound:"Soinua",swstretchvalign:"Stretch V-Align",swstretchhalign:"Stretch H-Align",swstretchstyle:"Stretch style",scriptcallbacks:"Script callbacks","align_top_right":"Goian eskuinean",uimode:"UI Modua",rate:"Rate",playcount:"Play count",defaultframe:"Lehenetsitako fotograma",currentposition:"Uneko posizioa",currentmarker:"Current marker",captioningid:"Captioning id",baseurl:"Base URL",balance:"Balanzea",windowlessvideo:"Lehiogabeko bideoa",stretchtofit:"Neurrikoa izateko zabaldu",mute:"Ixilik",invokeurls:"URLa deitu",fullscreen:"Pantaila osoa",enabled:"Gaituta",autostart:"Automatikoki hasi",volume:"Bolumena",target:"Helburua",qtsrcchokespeed:"Talka abiadura",href:"Href",endtime:"Noiz bukatu",starttime:"Noiz hasi",enablejavascript:"Gaitu JavaScript",correction:"Zuzenketarik ez",targetcache:"Helburu katxea",playeveryframe:"Marko guztiak erreproduzitu",kioskmode:"Kiosko modua",controller:"Controller",menu:"Erakutsi menua",loop:"Begizta",play:"Auto play",hspace:"H-Space",vspace:"V-Space","class_name":"Klasea",name:"Izena",id:"Id",type:"Mota",size:"Tamaina",preview:"Aurrebista","constrain_proportions":"Itxura erlazioa blokeatu",controls:"Kontrolak",numloop:"Begizta kopurua",console:"Konsola",cache:"Katxea",autohref:"AutoHREF",liveconnect:"SWLiveConnect",flashvars:"Flashvars",base:"Oinarria",bgcolor:"Atzea",wmode:"WMode",salign:"SAlign",align:"Lerrokatu",scale:"Eskalatu",quality:"Kalitatea",shuffle:"Shuffle",prefetch:"Prefetch",nojava:"Java ez",maintainaspect:"Itxura mantendu",imagestatus:"Irudi edoera",center:"Erdian",autogotourl:"Automatikoi joan URLra","shockwave_options":"Shockwave aukerak","rmp_options":"Real media player aukerak","wmp_options":"Windows media player aukerak","qt_options":"Quicktime aukerak","flash_options":"Flash aukerak",hidden:"Ezkutuan","align_bottom_left":"Behean ezkerrean","align_bottom_right":"Behean eskuinean",flash:"Flash (swf, flv, mp3)",quicktime:"QuickTime (mov, mp4, mpeg)",windowsmedia:"Windows Media (wmv, wma)",realmedia:"Real Media (ram)",shockwave:"shockwave",audio:"HTML5 audio (ogg)",video:"HTML5 video (ogv/ogg, webm)",iframe:"iframe","html5_video_options":"HTML5 bideo aukerak",altsource1:"Ordezko iturria 1",altsource2:"Ordezko iturria 2",preload:"Aurrekargatu",poster:"Posterra",source:"Iturria","html5_audio_options":"Audio aukerak","preload_none":"Ez aurrekargatu","preload_metadata":"Bideoaren metadatuak aurrekargatu","preload_auto":"Nabitzaileari erabakitzen utzi",
// The New eXeLearning
selected_file : "Aukeratutako fitxategia",
html5_warning : "HTML5 ez dabil nabigatzaile guztietan",
recommended_type : "Gomendatutako mota",
confirm_question : "Aldaketarik gabe jarraitu?",
preview_error : "Aurrebista ezin izan da sortu",
video_download_file_warning : "Erabiltzailearen nabigatzaileak ezin badu bideoa erreproduzitu, fitxategiaren esteka bistaratuko da.",
audio_download_file_warning : "Erabiltzailearen nabigatzaileak ezin badu audioa erreproduzitu, fitxategiaren esteka bistaratuko da.",
use_mediaelement : "Usar reproductor JavaScript",
"tab_caption":"Goiburua eta oina",
"recognition":"Izenburua eta egiletza",
"header":"Goiburua",
"media_title":"Lanaren titulua",
"media_title_link":"Izenburuaren esteka",
"author_name":"Jatorria/egilea",
"author_name_link":"Jatorri/egileari esteka",
"caption_license":"Lizentzia",
"caption_select_license":"Aukeratu...",
"public_domain":"Jabari publikoa",
"all_rights_reserved":"Eskubide guztiak erreserbatuta",
"block_presentation":"Aurkezpena",
"text_align":"Testuaren lerrokatzea",
"align_left":"Ezkerrean",
"align_center":"Erdian",
"align_right":"Eskuinean",
"image_and_caption_position":"Multzoaren posizioa",
"position_center":"Erdian",
"position_normal":"Normala",
"image_and_caption_float":"Portaera",
"position_left":"Testuaren ezkerrean",
"position_right":"Testuaren eskuinean",
"image_and_caption_margin":"Multzoaren marjina",
"caption_explanation":"Goiburua eta oina ezingo dira editatu elkarrizketa-koadro honetatik.",
"caption_warning":"Goiburua eta oina ezingo dira editatu elkarrizketa-koadro honetatik. Sortutako testura jo editatzeko edo borratzeko."
// The New eXeLearning
});