tinyMCE.addI18n('gl.media_dlg',{list:"Lista",file:"Arquivo/URL",advanced:"Avanzado",general:"Xeral",title:"Insertar/editar medio embebido","align_top_left":"Arriba Izda.","align_center":"Centrado","align_left":"Esquerda","align_bottom":"Abaixo","align_right":"Dereita","align_top":"Arriba","qt_stream_warn":"Os recursos rtsp de Streaming deber\u00edan engadirse no campo QT Src da pesta\u00f1a avanzada.\nAdem\u00e1is deber\u00eda engadir unha versi\u00f3n no Streaming no campo Src.",qtsrc:"QT Src",progress:"Progreso",sound:"Son",swstretchvalign:"Esturar ali\u00f1. V.",swstretchhalign:"Estirar ali\u00f1. H.",swstretchstyle:"Estilo estiramento",scriptcallbacks:"Script callbacks","align_top_right":"Arriba Dta.",uimode:"Modo UI",rate:"Relaci\u00f3n",playcount:"Cantas reproducci\u00f3ns",defaultframe:"Frame predet.",currentposition:"Posici\u00f3n actual",currentmarker:"Marcador actual",captioningid:"Id de lenda",baseurl:"URL Base",balance:"Balance",windowlessvideo:"Video sen vent\u00e1",stretchtofit:"Estirar pra axustar",mute:"Silencio",invokeurls:"Invocar URLs",fullscreen:"Pantalla Completa",enabled:"Habilitado",autostart:"Comezo Autom\u00e1tico",volume:"Volume",target:"Obxetivo",qtsrcchokespeed:"Vel. de choque",href:"Href",endtime:"Fin",starttime:"Inicio",enablejavascript:"Habilitar JavaScript",correction:"Sen correci\u00f3n",targetcache:"Obxetivo cache",playeveryframe:"Reproducir t\u00f3dolos frames",kioskmode:"Modo kiosco",controller:"Controller",menu:"Mostrar Men\u00fa",loop:"Repetitivo",play:"Comezo Autom\u00e1tico",hspace:"Espacio H.",vspace:"Espacio V.","class_name":"Clase",name:"Nome",id:"Id",type:"Tipo",size:"Tama\u00f1o",preview:"Vista Previa","constrain_proportions":"Bloquear proporci\u00f3ns",controls:"Controis",numloop:"N\u00fam. repetici\u00f3ns",console:"Consola",cache:"Cach\u00e9",autohref:"AutoHREF",liveconnect:"SWLiveConnect",flashvars:"Flashvars",base:"Base",bgcolor:"Fondo",wmode:"WMode",salign:"SAlign",align:"Ali\u00f1aci\u00f3n",scale:"Escala",quality:"Calidade",shuffle:"Aleatorio",prefetch:"PreBusca",nojava:"No java",maintainaspect:"Manter aspecto",imagestatus:"Estado de imaxe",center:"Centrado",autogotourl:"Ir a URL autom\u00e1t.","shockwave_options":"Opci\u00f3ns Shockwave","rmp_options":"Opci\u00f3ns Real media player","wmp_options":"Opci\u00f3ns Windows media player","qt_options":"Opci\u00f3ns Quicktime","flash_options":"Opci\u00f3ns Flash",hidden:"Oculto","align_bottom_left":"Abaixo Izda.","align_bottom_right":"Abaixo Dta.",flash:"Flash (swf, flv, mp3)",quicktime:"QuickTime (mov, mp4, mpeg)","embedded_audio_options":"Opci\u00f3ns de audio embebido",windowsmedia:"Windows Media (wmv, wma)",realmedia:"Real Media (ram)",shockwave:"shockwave",audio:"HTML5 audio (ogg)",video:"HTML5 video (ogv/ogg, webm)","html5_video_options":"Opci\u00f3ns HTML5 de v\u00eddeo",altsource1:"Fonte alternativa 1",altsource2:"Fonte alternativa 2",preload:"Precarga",poster:"P\u00f3ster",source:"Fonte","html5_audio_options":"Opci\u00f3ns de audio","preload_none":"Non precarga","preload_metadata":"Precargar metadatos de v\u00eddeo","preload_auto":"Permitir que decida o navegador do usuario",iframe:"iframe",embeddedaudio:"Audio embebido",
// The New eXeLearning
selected_file : "Arquivo seleccionado",
html5_warning : "HTML5 non funciona en t\u00F3dolos navegadores",
recommended_type : "Tipo recomendado",
confirm_question : "Continuar sen facer cambios?",
preview_error : "Non se puido xerar unha previsualizaci\u00F3n",
video_download_file_warning : "Se o navegador do usuario non pode reproducilo v\u00EDdeo amosarase un enlace ao arquivo.",
audio_download_file_warning : "Se o navegador do usuario non pode reproducilo audio amosarase un enlace ao arquivo.",
"tab_caption":"Encabezamento e p\u00E9",
"recognition":"T\u00EDtulo e reco\u00F1ecemento",
"header":"Encabezamento",
"media_title":"T\u00EDtulo da obra",
"media_title_link":"Ligaz\u00F3n ao t\u00EDtulo",
"author_name":"Orixe/autor",
"author_name_link":"Ligaz\u00F3n orixe/autor",
"caption_license":"Licenza",
"caption_select_license":"Seleccionar...",
"public_domain":"Dominio p\u00FAblico",
"all_rights_reserved":"T\u00F3dolos dereitos reservados",
"block_presentation":"Presentaci\u00F3n",
"text_align":"Ali\u00F1aci\u00F3n do texto",
"align_left":"Esquerda",
"align_center":"Centro",
"align_right":"Dereita",
"image_and_caption_position":"Posici\u00F3n do conxunto",
"position_center":"Centro",
"position_normal":"Normal",
"image_and_caption_float":"Comportamento",
"position_left":"\u00C1 esquerda do texto",
"position_right":"\u00C1 dereita do texto",
"image_and_caption_margin":"Marxe do conxunto",
"caption_explanation":"O encabezamento e o p\u00E9 non ser\u00E1n editables neste di\u00E1logo.",
"caption_warning":"O encabezamento e o p\u00E9 non se poden editar dende este di\u00E1logo. Pode modificalos ou eliminalos editando o seu texto."
// The New eXeLearning
});