tinyMCE.addI18n('nl.media_dlg',{list:"Lijst",file:"Bestand/URL",advanced:"Geavanceerd",general:"Algemeen",title:"Media invoegen/bewerken","align_top_left":"Linksboven","align_center":"Centreren","align_left":"Links","align_bottom":"Onder","align_right":"Rechts","align_top":"Boven","qt_stream_warn":"Gestreamde RTSP bronnen dienen op het tabblad geavanceerd bij Quicktime bron te worden opgegeven.\nDe niet-gestreamde versie kan dan bij het tabblad algemeen worden opgegeven.",qtsrc:"Quicktime bron",progress:"Voortgang",sound:"Geluid",swstretchvalign:"V-Schaal",swstretchhalign:"H-Schaal",swstretchstyle:"Schaal",scriptcallbacks:"Script callbacks","align_top_right":"Rechtsboven",uimode:"UI Modus",rate:"Snelheid",playcount:"Afspeelteller",defaultframe:"Standaard frame",currentposition:"Huidige positie",currentmarker:"Huidige markering",captioningid:"Ondertiteling id",baseurl:"Basis URL",balance:"Balans",windowlessvideo:"Video zonder venster",stretchtofit:"Passend maken",mute:"Dempen",invokeurls:"URLs laden",fullscreen:"Volledig scherm",enabled:"Ingeschakeld",autostart:"Automatisch afspelen",volume:"Volume",target:"Doel",qtsrcchokespeed:"Chokesnelheid",href:"Href",endtime:"Eindtijd",starttime:"Starttijd",enablejavascript:"JavaScript Inschakelen",correction:"Geen correctie",targetcache:"Doelcache",playeveryframe:"Elk frame afspelen",kioskmode:"Kioskmodus",controller:"Controller",menu:"Menu weergeven",loop:"Herhalen",play:"Automatisch afspelen",hspace:"H-Ruimte",vspace:"V-Ruimte","class_name":"Klasse",name:"Naam",id:"Id",type:"Type",size:"Afmetingen",preview:"Voorbeeld","constrain_proportions":"Verhouding bewaren",controls:"Bediening",numloop:"Aantal herhalingen",console:"Console",cache:"Cache",autohref:"AutoHREF",liveconnect:"SWLiveConnect",flashvars:"Variabelen",base:"Basis",bgcolor:"Achtergrond",wmode:"WMode",salign:"Schaaluitlijning",align:"Uitlijning",scale:"Schaal",quality:"Kwaliteit",shuffle:"Willekeurige volgorde",prefetch:"Voorladen",nojava:"Geen Java",maintainaspect:"Verhouding bewaren",imagestatus:"Afbeeldingstatus",center:"Centreren",autogotourl:"Automatisch naar URL","shockwave_options":"Shockwave opties","rmp_options":"Real Media Player Opties","wmp_options":"Windows Media Player Opties","qt_options":"Quicktime opties","flash_options":"Flash opties",hidden:"Verborgen","align_bottom_left":"Linksonder","align_bottom_right":"Rechtsonder",flash:"flash",quicktime:"quicktime","embedded_audio_options":"Ge\u00efntegreerd Geluid Opties",windowsmedia:"windowsmedia",realmedia:"realmedia",shockwave:"shockwave",audio:"geluid",video:"video","html5_video_options":"HTML5 Video Opties",altsource1:"Alternatieve bron 1",altsource2:"Alternatieve bron 2",preload:"Voorladen",poster:"Poster",source:"Bron","html5_audio_options":"Audio Opties","preload_none":"Niet voorladen","preload_metadata":"Video metadata voorladen","preload_auto":"Laat browser beslissen",iframe:"iframe",embeddedaudio:"ge\u00efntegreerd geluid",
// The New eXeLearning
video:"HTML5 video (ogv/ogg, webm)",
audio:"HTML5 audio (ogg)",
flash:"Flash (swf, flv, mp3)",
quicktime:"QuickTime (mov, mp4, mpeg)",
windowsmedia:"Windows Media (wmv, wma)",
realmedia:"Real Media (ram)",
selected_file : "Gekozen bestand",
html5_warning : "HTML5 werkt niet in alle browsers",
recommended_type : "Aanbevolen type",
confirm_question : "Doorgaan zondwer Uw instellingen aan te passen?",
preview_error : "Kon geen voorbeeldweergave aanmaken",
video_download_file_warning : "Voor browsers die dit type video niet ondersteunen zal een link naar de video worden getoond.",
audio_download_file_warning : "Voor browsers die dit type audio niet ondersteunen zal een link naar de audio worden getoond.",
use_mediaelement : "Use MediaElement.js audio and video player",
"tab_caption":"Koptekst en bijschrift",
"recognition":"Titel en Naamsvermelding",
"header":"Koptekst",
"media_title":"Mediatitel",
"media_title_link":"Link naar titel",
"author_name":"Bron/Auteur",
"author_name_link":"Link naar Bron/Auteur",
"caption_license":"Licentie",
"caption_select_license":"Kies een licentie...",
"public_domain":"Public Domain",
"all_rights_reserved":"Alle rechten voorbehouden",
"block_presentation":"Presentatie",
"text_align":"Uitlijning tekst",
"align_left":"Links",
"align_center":"Midden",
"align_right":"Rechts",
"image_and_caption_position":"Groepspositie",
"position_center":"Midden",
"position_normal":"Geen",
"image_and_caption_float":"Drijven",
"position_left":"Links",
"position_right":"Rechts",
"image_and_caption_margin":"Groepsmarge",
"caption_explanation":"Het is niet mogelijk om de koptekst of het onderschrift aan te passen in dit dialoogvenster.",
"caption_warning":"Je kunt de koptekst of het onderschrift niet aanpassen in dit dialoogvenster. Je kunt deze onderdelen wel wijzigen of verwijderen door de tekst zelf te bewerken."
// The New eXeLearning
});