tinyMCE.addI18n('pt.media_dlg',{list:"Lista",file:"Arquivo/URL",advanced:"Avan\u00e7ado",general:"Geral",title:"Inserir/Editar m\u00eddia embutida","align_top_left":"Topo esquerda","align_center":"Centro","align_left":"Esquerda","align_bottom":"Abaixo","align_right":"Direita","align_top":"Topo","qt_stream_warn":"Fluxos de recursos RTSP devem ser acrescentados ao campo QT Src no Modo Avan\u00e7ado.\nUma vers\u00e3o sem fluxo tamb\u00e9m deve ser acrescentada ao campo Src.",qtsrc:"QT Src",progress:"Progresso",sound:"Som",swstretchvalign:"For\u00e7ar V-Alinhamento",swstretchhalign:"For\u00e7ar H-Alinhamento",swstretchstyle:"For\u00e7ar Estilo",scriptcallbacks:"Retornos de chamada de script","align_top_right":"Topo direita",uimode:"Modo UI",rate:"Taxa",playcount:"Contagem de ouvintes",defaultframe:"Frame padr\u00e3o",currentposition:"Posi\u00e7\u00e3o atual",currentmarker:"Marcador atual",captioningid:"Id de legenda",baseurl:"URL Base",balance:"Stereo",windowlessvideo:"V\u00eddeo sem janela",stretchtofit:"Estender",mute:"Mudo",invokeurls:"Chamar URLs",fullscreen:"Tela inteira",enabled:"Ativado",autostart:"Execu\u00e7\u00e3o autom\u00e1tica",volume:"Volume",target:"Alvo",qtsrcchokespeed:"Diminuir Velocidade",href:"Link",endtime:"Hora do fim",starttime:"Hora de in\u00edcio",enablejavascript:"Permitir JavaScript",correction:"Sem correc\u00e7\u00f5es",targetcache:"Cache alvo",playeveryframe:"Executar todas as frames",kioskmode:"Modo Kiosk",controller:"Controlador",menu:"Mostrar menu",loop:"Repeti\u00e7\u00e3o autom\u00e1tica",play:"Execu\u00e7\u00e3o autom\u00e1tica",hspace:"Espa\u00e7o horizontal",vspace:"Espa\u00e7o vertical","class_name":"Classe",name:"Nome",id:"ID",type:"Tipo",size:"Dimens\u00f5es",preview:"Previs\u00e3o","constrain_proportions":"Manter propor\u00e7\u00f5es",controls:"Controles",numloop:"Repeti\u00e7\u00f5es",console:"Console",cache:"Cache",autohref:"AutoHREF",liveconnect:"SWLiveConnect",flashvars:"Flash Vars",base:"Base",bgcolor:"Fundo",wmode:"WMode",salign:"SAlign",align:"Alinhamento",scale:"Escala",quality:"Qualidade",shuffle:"Aleat\u00f3rio",prefetch:"Pr\u00e9-buscar",nojava:"Sem Java",maintainaspect:"Manter aspecto",imagestatus:"Status da imagem",center:"Centro",autogotourl:"Auto abrir URL","shockwave_options":"Op\u00e7\u00f5es Shockwave","rmp_options":"Op\u00e7\u00f5es Real Media Player","wmp_options":"Op\u00e7\u00f5es Windows Media Player","qt_options":"Op\u00e7\u00f5es Quicktime","flash_options":"Op\u00e7\u00f5es Flash",hidden:"Oculto","align_bottom_left":"Abaixo esquerda","align_bottom_right":"Abaixo direita",flash:"flash",quicktime:"quicktime","embedded_audio_options":"Op\u00e7\u00f5es de \u00c1udio Embutido",windowsmedia:"windowsmedia",realmedia:"realmedia",shockwave:"shockware",audio:"\u00e1udio",video:"v\u00eddeo","html5_video_options":"Op\u00e7\u00f5es de v\u00eddeo HTML5",altsource1:"C\u00f3digo alternativo 1",altsource2:"C\u00f3digo alternativo 2",preload:"Pr\u00e9-carregar",poster:"Poster",source:"Fonte","html5_audio_options":"Op\u00e7\u00f5es de Audio","preload_none":"N\u00e3o Pr\u00e9-carregar","preload_metadata":"Pr\u00e9-carregar metadata de v\u00eddeo","preload_auto":"Deixar que navegador do usu\u00e1rio decida",iframe:"iframe",embeddedaudio:"\u00e1udio embutido",
// The New eXeLearning
video:"HTML5 video (ogv/ogg, webm)",
audio:"HTML5 audio (ogg)",
flash:"Flash (swf, flv, mp3)",
quicktime:"QuickTime (mov, mp4, mpeg)",
windowsmedia:"Windows Media (wmv, wma)",
realmedia:"Real Media (ram)",
selected_file : "Ficheiro selecionado",
html5_warning : "HTML5 n\u00E3o funciona em todos os navegadores",
recommended_type : "Tipo recomendado",
confirm_question : "Continuar sem fazer qualquer mudan\u00E7a?",
preview_error : "N\u00E3o foi poss\u00EDvel gerar uma pr\u00E9-visualiza\u00E7\u00E3o",
video_download_file_warning : "Se o navegador do utilizador n\u00E3o conseguir reproduzir o v\u00EDdeo, ser\u00E1 mostrada uma liga\u00E7\u00E3o para o ficheiro.",
audio_download_file_warning : "Se o navegador do utilizador n\u00E3o conseguir reproduzir o \u00E1udio, ser\u00E1 mostrada uma liga\u00E7\u00E3o para o ficheiro.",
use_mediaelement : "Use MediaElement.js audio and video player",
"tab_caption":"Cabe\u00E7alho e legenda",
"recognition":"T\u00EDtulo e reconhecimento da autoria",
"header":"Cabe\u00E7alho",
"media_title":"T\u00EDtulo",
"media_title_link":"Liga\u00E7\u00E3o da t\u00EDtulo",
"author_name":"Fonte / Autoria",
"author_name_link":"Liga\u00E7\u00E3o \u00E0 fonte / autoria",
"caption_license":"Licen\u00E7a",
"caption_select_license":"Escolha uma licen\u00E7a...",
"public_domain":"Dom\u00EDnio p\u00FAblico",
"all_rights_reserved":"Todos os direitos reservados",
"block_presentation":"Apresenta\u00E7\u00E3o",
"text_align":"Alinhamento do texto",
"align_left":"\u00C0 esquerda",
"align_center":"Centrado",
"align_right":"\u00C0 direita",
"image_and_caption_position":"Posi\u00E7\u00E3o do bloco",
"position_center":"Centrado",
"position_normal":"Nenhuma",
"image_and_caption_float":"Flutuante",
"position_left":"\u00C0 esquerda",
"position_right":"\u00C0 direita",
"image_and_caption_margin":"Margens do bloco",
"caption_explanation":"N\u00E3o \u00E9 poss\u00EDvel editar o cabe\u00E7alho e a legenda neste di\u00E1logo.",
"caption_warning":"N\u00E3o \u00E9 poss\u00EDvel editar o cabe\u00E7alho e a legenda neste di\u00E1logo. Para os modificar ou apagar, edite o texto."
// The New eXeLearning
});