tinyMCE.addI18n('en.exegames',{
    title : _("Games (hangman...)"),
    general : _("General"),
    instructions : _("Instructions"),
    choose_a_type : _("Choose a type:"),
    update : _("Update"),
    // Accessibility
    enable_javascript : _("Please enable JavaScript to play this game."),
    accessibility : _("Accessibility"),
    accessibility_1 : _("These games require JavaScript."),
    accessibility_2 : _("This is the message that the users with no JavaScript will see:"),
    accessibility_3 : _("Message:"),
    accessibility_4 : _("You can change it at any time."),
    missing_js_warning : _("Provide a warning to users who have JavaScript disabled (Accessibility)."),
    // Hangman
    hangman : _("Hangman Game"),
    hangman_desc : _("Guess letters to complete each word."),
    hangman_letters : _("Alphabet to Select From"),
    include_capital_letters : _("Automatically include capital letters"),
    case_sensitive : _("Case sensitive"),
    hangman_az : _("abcdefghijklmnñopqrstuvwxyz"),
    words_to_guess : _("Words to guess"),
    dd : _("Word to guess"),
    dt : _("Hint or definition"),
    missing_az : _("Please write the Alphabet to Select From"),
    missing_dd : _("A word to guess is missing"),
    missing_dt : _("A hint or definition is missing"),
    missing_words_to_guess : _("Please add at least one word to guess"),
    hangmanInstructions_1 : _("Write the list of letters and/or numbers to choose from."),
    hangmanInstructions_2 : _("You may include capital letters or they can be automatically included."),
    hangmanInstructions_3 : _("Choose if you want the game to be case sensitive."),
    hangmanInstructions_4 : _("Add at least one word to guess (question or definition + word)."),
    deleteGameInstructions : _("You may delete the game from the editor itself."),
    accessibilityReminder : _("Don't forget to check the Accessibility tab."),
	// Errors
	inline_popups_plugin_is_required : _('The plugin \u0022inlinepopups\u0022 must be enabled'),
	jquery_is_required : _('jQuery is required'),
    error_recovering_data : _('Error recovering data')
});
