.\"          Hey, EMACS: -*- nroff -*-
.\"
.\" If you want to edit this manpage to make it more useful,
.\" you might find the groff_man(7) manpage helpful.
.\"
.TH PYTHON-EXE "1" "September 2005" "python-exe 0.10" "User Commands"
.SH NAME
python-exe \- eLearning XHTML editor
.SH SYNOPSIS
.B exe
.I [ ... ]
.br
.B run-exe.sh
.I [ ... ]
.SH DESCRIPTION
.RS 6
.B Note:
This is a mostly useless dummy manual page for the
.B python-exe
package.
What follows in the description of the package (if any)
provided in the packages setup.py file.
.RE
.PP
The eXe project is an authoring environment to enable teachers to publish
web content without the need to become proficient in HTML or XML markup.
Content generated using eXe can be used by any Learning Management System.
.SH SEE ALSO
Other places which may or may not offer more information
on the commands in this package include:
.IP
/usr/share/doc/python-exe/
.IP
http://exelearning.org
.PP
You might also try running
.B pydoc
on the scripts themselves (or just examine them with your
favorite text viewer) to see if they contain any documention.
.SH AUTHOR
exe was written by University of Auckland <exe@exelearning.org>
.PP
This manual page was generated automatically by
Matthew Sherborne <matthew@exelearning.org>
using dh_make (distutils 2.4.1)
for the Debian project.

