// ES lang variables

tinyMCE.addToLang('media',{
title : 'Insertar/Editar multimedia',
desc : 'Insertar/Editar multimedia',
general : 'General',
advanced : 'Avanzado',
file : 'Fichero/URL',
list : 'Lista',
size : 'Dimensiones',
preview : 'Previsualizar',
constrain_proportions : 'Restringir proporciones',
type : 'Tipo',
id : 'Id',
name : 'Nombre',
class_name : 'Clase',
vspace : 'Espacio V',
hspace : 'Espacio H',
play : 'Auto-play',
loop : 'Bucle',
menu : 'Mostrar men&uacute;',
quality : 'Calidad',
scale : 'Escala',
align : 'Alinear',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Color de fondo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Oculto',
controller : 'Controlador',
kioskmode : 'Kiosk mode',
playeveryframe : 'Reproducir todos los fotogramas',
targetcache : 'Target cache',
correction : 'Sin correcci&oacute;n',
enablejavascript : 'Habilitar JavaScript',
starttime : 'Tiempo inicio',
endtime : 'Tiempo fin',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Target',
volume : 'Volumen',
autostart : 'Auto-start',
enabled : 'Habilitado',
fullscreen : 'Pantalla completa',
invokeurls : 'Invoke URLs',
mute : 'Silencio',
stretchtofit : 'Encajar',
windowlessvideo : 'Windowless video',
balance : 'Balance',
baseurl : 'URL base',
captioningid : 'ID subtitulado',
currentmarker : 'Marcador actual',
currentposition : 'Posici&oacute;n actual',
defaultframe : 'Fotograma por defecto',
playcount : 'Play count',
rate : 'Rate',
uimode : 'UI Mode',
flash_options : 'Opciones Flash',
qt_options : 'Opciones Quicktime',
wmp_options : 'Opciones Windows media player',
rmp_options : 'Opciones Real media player',
shockwave_options : 'Opciones Shockwave',
autogotourl : 'Auto-redirecci&oacute;n a URL',
center : 'Centro',
imagestatus : 'Estado imagen',
maintainaspect : 'Mantener aspecto',
nojava : 'Sin java',
prefetch : 'Prefetch',
shuffle : 'Aleatorio',
console : 'Consola',
numloop : 'No. bucles',
controls : 'Controles',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Sonido',
progress : 'Progreso',
qtsrc : 'QT Src',
qt_stream_warn : 'Los recursos de Streaming deben a&ntilde;adirse al campo QT Src en la pesta&ntilde;a Avanzado.\nTambi&eacute;n deber&iacute;a a&ntilde;adir una versi&oacute;n sin Streaming en Src field.',
align_top : 'Arriba',
align_right : 'Derecha',
align_bottom : 'Abajo',
align_left : 'Izquierda',
align_center : 'Centro',
align_top_left : 'Superior izquierda',
align_top_right : 'Superior derecha',
align_bottom_left : 'Inferior izquierda',
align_bottom_right : 'Inferior derecha',
select_media_type : 'Debe seleccionar un tipo instalado'
});
