// JR
// ES lang variables

tinyMCE.addToLang('media',{
title : 'Insertar / editar medio embebido',
desc : 'Insertar / editar medio embebido',
general : 'General',
advanced : 'Avanzado',
file : 'Archivo/URL',
list : 'Lista',
size : 'Dimensiones',
preview : 'Vista previa',
constrain_proportions : 'Bloquear relación de aspecto',
type : 'Tipo',
id : 'Id',
name : 'Nombre',
class_name : 'Clase',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Comienzo automático',
loop : 'Repetitivo',
menu : 'Mostrar menú',
quality : 'Calidad',
scale : 'Escala',
align : 'Alineación',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Fondo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Caché',
hidden : 'Oculto',
controller : 'Controller',
kioskmode : 'Kiosk mode',
playeveryframe : 'Reproducir todos los frames',
targetcache : 'Target cache',
correction : 'Sin corrección',
enablejavascript : 'Habilitar JavaScript',
starttime : 'Inicio',
endtime : 'Fin',
href : 'Href',
qtsrcchokespeed : 'Velocidad de choque',
target : 'Destino',
volume : 'Volumen',
autostart : 'Comienzo automático',
enabled : 'Habilitado',
fullscreen : 'Pantalla Completa',
invokeurls : 'Invocar URLs',
mute : 'Silencio',
stretchtofit : 'Estirar para ajustar',
windowlessvideo : 'Video sin ventana',
balance : 'Balance',
baseurl : 'URL Base',
captioningid : 'Captioning id',
currentmarker : 'Marcador actual',
currentposition : 'Posición actual',
defaultframe : 'Frame predet.',
playcount : 'Cuántas reproducciones',
rate : 'Ratio',
uimode : 'Modo UI',
flash_options : 'Opciones Video Flash',
qt_options : 'Opciones Quicktime',
wmp_options : 'Opciones Windows media player',
rmp_options : 'Opciones Real media player',
shockwave_options : 'Opciones Shockwave',
autogotourl : 'Ir a URL automát.',
center : 'Centrado',
imagestatus : 'Estado de imagen',
maintainaspect : 'Mantener aspecto',
nojava : 'No java',
prefetch : 'Prebúsqueda',
shuffle : 'Aleatorio',
console : 'Consola',
numloop : 'Núm. repeticiones',
controls : 'Controles',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Estilo estiramiento',
swstretchhalign : 'Alin. H. Estiramiento',
swstretchvalign : 'Alin. V. Estiramiento',
sound : 'Sonido',
progress : 'Progreso',
qtsrc : 'QT Src',
qt_stream_warn : 'Los recursos rtsp de Streaming deberían añadirse en el campo QT Src de la pestaña avanzada.\nAdemás debería añadir una versión no Streaming en el campo Src.',
align_top : 'Arriba',
align_right : 'Derecha',
align_bottom : 'Abajo',
align_left : 'Izquierda',
align_center : 'Centrado',
align_top_left : 'Arriba izquierda',
align_top_right : 'Arriba derecha',
align_bottom_left : 'Abajo izquierda',
align_bottom_right : 'Abajo derecha',
select_media_type : 'Deberías tener instalado el tipo de medio selecconado',
});
