FMATH_i18n = {
	// addToolbarImage
	menu_new : "New document",
	menu_save : "Save",
	menu_xml_edit : "Edit (XML/MathML)",
	menu_tex_edit : "Edit (TeX)",
	menu_edit_delete : "Delete",
	menu_edit_cut : "Cut",
	menu_edit_copy : "Copy",
	menu_edit_paste_left : "Paste on the left",
	menu_edit_paste_replace : "Paste (replace)",
	menu_edit_paste_right : "Paste con the right",
	menu_edit_undo : "Undo",
	menu_edit_redo : "Redo",
	menu_sign1 : "Signs (1)",
	menu_sign2 : "Signs (2)",
	menu_sign3 : "Signs (3)",
	menu_sign4 : "Signs (4)",
	menu_sign5 : "Signs (5)",
	menu_sign6 : "Signs (6)",
	menu_text1 : "Text (1)",
	menu_text2 : "Text (2)",
	menu_text3 : "Text (3)",
	menu_text4 : "Text (4)",
	menu_text5 : "Text (5)",
	menu_text6 : "Text (6)",
	menu_unicode : "Unicode",
	menu_plus : "Plus",
	menu_fraction : "Fraction",
	menu_fence : "Fence",
	menu_sum : "Sum",
	menu_matrix : "Matrix",
	menu_sin : "Sin",
	menu_formulas : "Formulas",
	win_insert_right : "Insert on the right",
	win_insert_left : "Insert on the left",
	// addTextButton
	win_replace : "Replace Selected",
	win_close : "Close"	
}