doc_root       			= "/var/www/html/python/eXe/"
startcgi 				= "/python/eXe/start.pyg"
previewcgi				= "/python/eXe/preview/preview.pyg"
theme_template			= "/var/www/html/python/eXe/idevices/index_content.template"
publish_template		= "/var/www/html/python/eXe/idevices/publish_content.template"
template_directory		= "idevices/"

topicxmlfile			= "topics.xml"
sectionxmlfile			= "sections.xml"
unitxmlfile				= "units.xml"
idevicexmlfile			= "idevices.xml"

coursexmlfile	  		= doc_root + "courses.xml"
#form template here#
courseForm   			= doc_root + template_directory + "course_form.template" 
topicForm      			= doc_root + template_directory + "topic_form.template" 
sectionForm  			= doc_root + template_directory + "section_form.template" 
unitForm  				= doc_root + template_directory + "unit_form.template" 
readingactivityForm		= doc_root + template_directory + "readingactivity_form.template" 
freetextForm 			= doc_root + template_directory + "freetext_form.template" 
multimediaForm 			= doc_root + template_directory + "multimedia_form.template" 
objectiveForm 			= doc_root + template_directory + "objectives_form.template" 
scopeForm 				= doc_root + template_directory + "scope_form.template" 
preknowledgeForm 		= doc_root + template_directory + "preknowledge_form.template" 
activityForm 			= doc_root + template_directory + "activity_form.template" 

#content template here#
eXe_content_template 	= doc_root + template_directory + "index_content.template"
course_content_template = doc_root + template_directory + "course_content.template"
topic_content_template	= doc_root + template_directory + "topic_content.template"
section_content_template= doc_root + template_directory + "section_content.template"
unit_content_template 	= doc_root + template_directory + "unit_content.template"

#xml template here#

course_xml_template 	= doc_root + template_directory + "course_xml.template"
topic_xml_template 		= doc_root + template_directory + "topic_xml.template"
section_xml_template 	= doc_root + template_directory + "section_xml.template"
unit_xml_template 		= doc_root + template_directory + "unit_xml.template"
objectives_xml_template = doc_root + template_directory + "objectives_xml.template"
readingactivity_xml_template = doc_root + template_directory + "readingactivity_xml.template" 
freetext_xml_template	= doc_root + template_directory + "freetext_xml.template" 
multimedia_xml_template	= doc_root + template_directory + "multimedia_xml.template" 
scope_xml_template		= doc_root + template_directory + "scope_xml.template" 
preknowledge_xml_template	= doc_root + template_directory + "preknowledge_xml.template" 
activity_xml_template	= doc_root + template_directory + "activity_xml.template" 
idevices_xml_template	= doc_root + template_directory + "idevices_xml.template"

objectives_content_template = doc_root + template_directory + "objectives_content.template"
readingactivity_content_template = doc_root + template_directory + "readingactivity_content.template" 
freetext_content_template	= doc_root + template_directory + "freetext_content.template" 
multimedia_content_template	= doc_root + template_directory + "multimedia_content.template" 
scope_content_template		= doc_root + template_directory + "scope_content.template" 
preknowledge_content_template	= doc_root + template_directory + "preknowledge_content.template" 
activity_content_template	= doc_root + template_directory + "activity_content.template" 
idevices_content_template	= doc_root + template_directory + "idevices_content.template"
