// NO lang variables by Knut B. Jacobsen

tinyMCE.addToLang('table',{
general_tab : 'Generell',
advanced_tab : 'Avansert',
general_props : 'Generelle egenskaper',
advanced_props : 'Avanserte egenskaper',
desc : 'Opprett/endre tabell',
row_before_desc : 'Opprett rad foran',
row_after_desc : 'Opprett rad etter',
delete_row_desc : 'Fjern rad',
col_before_desc : 'Opprett kolonne foran',
col_after_desc : 'Opprett kolonne etter',
delete_col_desc : 'Fjern kolonne',
rowtype : 'Rad i tabell',
title : 'Opprett/endre tabell',
width : 'Bredde',
height : 'H&oslash;yde',
cols : 'Kolonner',
rows : 'Rader',
cellspacing : 'Celle mellomrom',
cellpadding : 'Celle fylling',
border : 'Rammebredde',
align : 'Justering',
align_default : 'Ingen',
align_left : 'Venstre',
align_right : 'H&oslash;yre',
align_middle : 'Midtstilt',
row_title : 'tabell rad egenskaper',
cell_title : 'tabell celle egenskaper',
cell_type : 'Celle type',
row_desc : 'tabell rad egenskaper',
cell_desc : 'tabell celle egenskaper',
valign : 'Vertikal justering',
align_top : 'Topp',
align_bottom : 'Bunn',
props_desc : 'tabell egenskaper',
bordercolor : 'Rammefarge',
bgcolor : 'Bakgrunnsfarge',
merge_cells_title : 'Sl&aring; sammen tabell celler',
split_cells_desc : 'Splitt tabell celler',
merge_cells_desc : 'Sl&aring; sammen tabell celler',
cut_row_desc : 'Fjern tabell rad',
copy_row_desc : 'Kopier tabell rad',
paste_row_before_desc : 'Lim inn tabell rad foran',
paste_row_after_desc : 'Lim inn tabell rad etter',
id : 'Id',
style: 'Stil',
langdir : 'Spr&aring;k retning',
langcode : 'Spr&aring;k kode',
mime : 'M&aring;lets MIME type',
ltr : 'Venstre mot h&oslash;yre',
rtl : 'H&oslash;re mot venstre',
bgimage : 'Bakgrunnsbilde',
summary : 'Sum',
td : "Data",
th : "Overskrift",
cell_cell : 'Oppdater valgt celle',
cell_row : 'Oppdater alle celler i raden',
cell_all : 'Oppdater alle celler i tabellen',
row_row : 'Oppdater valgt rad',
row_odd : 'Oppdater ulike rader i tabellen',
row_even : 'Oppdater even rader i tabellen',
row_all : 'Oppdater alle rader i tabellen',
thead : 'Tabell Hode',
tbody : 'Tabell Kropp',
tfoot : 'Tabell Fot',
del : 'Slett tabell',
scope : 'Scope',
row : 'Row',
col : 'Col',
rowgroup : 'Row Group',
colgroup : 'Col Group',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});