tinyMCE.addI18n('ca.advimage_dlg',{"image_list":"Llista d\'imatges","align_right":"A la dreta","align_left":"A l\'esquerra","align_textbottom":"Baix del text","align_texttop":"Dalt del text","align_bottom":"Inferior","align_middle":"Mitjan lloc","align_top":"Superior","align_baseline":"L\u00ednia de base",align:"Alineaci\u00f3",hspace:"Espai horitzontal",vspace:"Espai vertical",dimensions:"Dimensions",border:"Vora",list:"Llista de la imatge",alt:"Descripci\u00f3 de la imatge",src:"URL de la imatge","dialog_title":"Insereix/edita imatge","missing_alt":"Esteu segur que voleu continuar sense incloure una descripci\u00f3 de la imatge? La imatge pot no ser accessible a usuaris amb discapacitats, o a aquells que utilitzin navegadors de text o que naveguin amb les imatges desactivades.","example_img":"Aparen\u00e7a imatge previsualitzada",misc:"Miscel\u00b7l\u00e0nia",mouseout:"quan el ratol\u00ed marxa",mouseover:"quan el ratol\u00ed arriba","alt_image":"Imatge alternativa","swap_image":"Canvia imatge",map:"Mapa de la imatge",id:"Id",rtl:"De dreta a esquerra",ltr:"D\'esquerra a dreta",classes:"Classes",style:"Estil","long_desc":"Enlla\u00e7 a la descripci\u00f3 llarga",langcode:"Codi de l\'idioma",langdir:"Direcci\u00f3 de l\'idioma","constrain_proportions":"Mant\u00e9 la proporci\u00f3",preview:"Previsualitzaci\u00f3",title:"T\u00edtol",general:"General","tab_advanced":"Avan\u00e7at","tab_appearance":"Aparen\u00e7a","tab_general":"General",width:"Amplada",height:"Al\u00e7ada",
// The New eXeLearning
"tab_caption":"Encabezado y pie de foto",
"recognition":"T\u00EDtulo y reconocimiento",
"header":"Encabezado",
"image_title":"T\u00EDtulo de la imagen",
"image_title_link":"Enlace del t\u00EDtulo",
"author_name":"Origen/autor",
"author_name_link":"Enlace origen/autor",
"caption_license":"Licencia",
"caption_select_license":"Seleccionar...",
"public_domain":"Dominio p\u00FAblico",
"all_rights_reserved":"Todos los derechos reservados",
"block_presentation":"Presentaci\u00F3n",
"text_align":"Alineaci\u00F3n del texto",
"align_left":"Izquierda",
"align_center":"Centro",
"align_right":"Derecha",
"image_and_caption_position":"Posici\u00F3n del conjunto",
"position_center":"Centro",
"position_normal":"Normal",
"image_and_caption_float":"Comportamiento",
"position_left":"A la izquierda del texto",
"position_right":"A la derecha del texto",
"image_and_caption_margin":"Margen del conjunto",
"caption_explanation":"El encabezado y el pie de foto no ser\u00E1n editables desde este di\u00E1logo.",
"caption_warning":"El encabezado y el pie de foto no se pueden editar desde este di\u00E1logo. Puede modificarlos o borrarlos editando su texto."
// The New eXeLearning
});