tinyMCE.addI18n('en.advimage_dlg',{"image_list":_("Image List"),"align_right":_("Right"),"align_left":_("Left"),"align_textbottom":_("Text Bottom"),"align_texttop":_("Text Top"),"align_bottom":_("Bottom"),"align_middle":_("Middle"),"align_top":_("Top"),"align_baseline":_("Baseline"),align:_("Alignment"),hspace:_("Horizontal Space"),vspace:_("Vertical Space"),dimensions:_("Dimensions"),border:_("Border"),list:_("Image List"),alt:_("Image Description"),src:_("Image URL"),"dialog_title":_("Insert/Edit Image"),"missing_alt":_("Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off."),"example_img":_("Appearance Preview Image"),misc:_("Miscellaneous"),mouseout:_("For Mouse Out"),mouseover:_("For Mouse Over"),"alt_image":_("Alternative Image"),"swap_image":_("Swap Image"),map:_("Image Map"),id:_("ID"),rtl:_("Right to Left"),ltr:_("Left to Right"),classes:_("Classes"),style:_("Style"),"long_desc":_("Long Description Link"),langcode:_("Language Code"),langdir:_("Language Direction"),"constrain_proportions":_("Constrain Proportions"),preview:_("Preview"),title:_("Title"),general:_("General"),"tab_advanced":_("Advanced"),"tab_appearance":_("Appearance"),"tab_general":_("General"),width:_("Width"),height:_("Height"),
// The New eXeLearning
"tab_caption":_("Header and Caption"),
"recognition":_("Title and Attribution"),
"header":_("Header"),
"image_title":_("Image Title"),
"image_title_link":_("Title Link"),
"author_name":_("Source/Author"),
"author_name_link":_("Source/Author Link"),
"caption_license":_("License"),
"caption_select_license":_("Choose a license..."),
"public_domain":_("Public Domain"),
"all_rights_reserved":_("All Rights Reserved"),
"block_presentation":_("Presentation"),
"text_align":_("Text Alignment"),
"align_left":_("Left"),
"align_center":_("Center"),
"align_right":_("Right"),
"image_and_caption_position":_("Group Position"),
"position_center":_("Center"),
"position_normal":_("None"),
"image_and_caption_float":_("Float"),
"position_left":_("Left"),
"position_right":_("Right"),
"image_and_caption_margin":_("Group Margin"),
"caption_explanation":_("You will not be able to edit the header or the caption from this dialog."),
"caption_warning":_("The header and the caption can't be edited from this dialog. You can change or remove them editing the text itself.")
// The New eXeLearning
});