tinyMCE.addI18n('es.advimage_dlg',{"image_list":"Lista de imagen","align_right":"Derecha","align_left":"Izquierda","align_textbottom":"Texto abajo","align_texttop":"Texto arriba","align_bottom":"Debajo","align_middle":"Medio","align_top":"Arriba","align_baseline":"L\u00ednea base",align:"Alineaci\u00f3n",hspace:"Espacio horizontal",vspace:"Espacio vertical",dimensions:"Dimensiones",border:"Bordes",list:"Lista de imagen",alt:"Descripci\u00f3n de la imagen",src:"URL de la imagen","dialog_title":"Insertar/editar imagen","missing_alt":" \u00bfEsta seguro de continuar sin introducir una descripci\u00f3n a la imagen? Sin ella puede no ser accesible para usuarios con discapacidades, o para aquellos que usen navegadores de modo texto, o tengan deshabilitadas las im\u00e1genes de la p\u00e1gina.","example_img":"Vista previa de la imagen",misc:"Miscel\u00e1neo",mouseout:"para mouseout",mouseover:"para mouseover","alt_image":"Imagen alternativa","swap_image":"Intercambiar imagen",map:"Mapa de imagen",id:"Id",rtl:"Derecha a izquierda",ltr:"Izquierda a derecha",classes:"Clases",style:"Estilos","long_desc":"V\u00ednculo para descripci\u00f3n larga",langcode:"C\u00f3digo del lenguaje",langdir:"Direcci\u00f3n del lenguaje","constrain_proportions":"Bloquear relaci\u00f3n de aspecto",preview:"Vista previa",title:"T\u00edtulo",general:"General","tab_advanced":"Avanzado","tab_appearance":"Apariencia","tab_general":"General",width:"Ancho",height:"Alto",
// The New eXeLearning
"tab_caption":"Encabezado y pie de foto",
"recognition":"T\u00EDtulo y reconocimiento",
"header":"Encabezado",
"image_title":"T\u00EDtulo de la imagen",
"image_title_link":"Enlace del t\u00EDtulo",
"author_name":"Origen/autor",
"author_name_link":"Enlace origen/autor",
"caption_license":"Licencia",
"caption_select_license":"Seleccionar...",
"public_domain":"Dominio p\u00FAblico",
"all_rights_reserved":"Todos los derechos reservados",
"block_presentation":"Presentaci\u00F3n",
"text_align":"Alineaci\u00F3n del texto",
"align_left":"Izquierda",
"align_center":"Centro",
"align_right":"Derecha",
"image_and_caption_position":"Posici\u00F3n del conjunto",
"position_center":"Centro",
"position_normal":"Normal",
"image_and_caption_float":"Comportamiento",
"position_left":"A la izquierda del texto",
"position_right":"A la derecha del texto",
"image_and_caption_margin":"Margen del conjunto",
"caption_explanation":"El encabezado y el pie de foto no ser\u00E1n editables desde este di\u00E1logo.",
"caption_warning":"El encabezado y el pie de foto no se pueden editar desde este di\u00E1logo. Puede modificarlos o borrarlos editando su texto."
// The New eXeLearning
});