tinyMCE.addI18n('eu.advimage_dlg',{"image_list":"Irudi-zerrenda","align_right":"Eskuinean","align_left":"Ezkerrean","align_textbottom":"Testua behean","align_texttop":"Testua goian","align_bottom":"Behean","align_middle":"Tartean","align_top":"Goian","align_baseline":"Oinarri-marra",align:"Alineazioa",hspace:"Tarte horizontala",vspace:"Tarte bertikala",dimensions:"Tamaina",border:"Inguruko marra",list:"Irudi-zerrenda",alt:"Irudiaren deskribapena",src:"Irudiaren URL helbidea","dialog_title":"Irudia txertatu/editatu","missing_alt":"Irudiaren deskribapena gehitu gabe jarraitu nahi duzu? Hau horrela, ezgaitasunak dituztenentzat edo testu nabigatzaile bat darabiltenentzat ez da irisgarria izango.","example_img":"Nola ikusiko den",misc:"Bestelakoak",mouseout:"xagua kentzen denean",mouseover:"xagua gainean dagoenean","alt_image":"Ordezko irudia","swap_image":"Irudia ordezkatu",map:"Irudi-mapa",id:"Id",rtl:"Eskuinetik ezkerrera",ltr:"Ezkerretik eskuinera",classes:"Klaseak",style:"Estiloa","long_desc":"Deskribapen luzearen lotura",langcode:"Hizkuntza-kodea",langdir:"Hizkuntzaren norabidea","constrain_proportions":"Proportzioak mantendu",preview:"Aurrebista",title:"Izenburua",general:"Orokorra","tab_advanced":"Aurreratua","tab_appearance":"Itxura","tab_general":"Orokorra",width:"Zabalera",height:"Altuera",
// The New eXeLearning
"tab_caption":"Argazkiaren goiburua eta oina",
"recognition":"Izenburua eta egiletza",
"header":"Goiburua",
"image_title":"Irudiaren goiburua",
"image_title_link":"Izenburuaren esteka",
"author_name":"Jatorria/egilea",
"author_name_link":"Jatorri/egileari esteka",
"caption_license":"Lizentzia",
"caption_select_license":"Aukeratu...",
"public_domain":"Jabari publikoa",
"all_rights_reserved":"Eskubide guztiak erreserbatuta",
"block_presentation":"Aurkezpena",
"text_align":"Testuaren lerrokatzea",
"align_left":"Ezkerrean",
"align_center":"Erdian",
"align_right":"Eskuinean",
"image_and_caption_position":"Multzoaren posizioa",
"position_center":"Erdian",
"position_normal":"Normala",
"image_and_caption_float":"Portaera",
"position_left":"Testuaren ezkerrean",
"position_right":"Testuaren eskuinean",
"image_and_caption_margin":"Multzoaren marjina",
"caption_explanation":"Irudiaren goiburua eta oina ezingo dira editatu elkarrizketa-koadro honetatik.",
"caption_warning":"Irudiaren goiburua eta oina ezingo dira editatu elkarrizketa-koadro honetatik. Sortutako testura jo editatzeko edo borratzeko."
// The New eXeLearning
});