tinyMCE.addI18n('fr.advimage_dlg',{"image_list":"Liste d\'images","align_right":"Droite (flottant)","align_left":"Gauche (flottant)","align_textbottom":"Texte en bas","align_texttop":"Texte en haut","align_bottom":"En bas","align_middle":"Au milieu","align_top":"En haut","align_baseline":"Normal",align:"Alignement",hspace:"Espacement horizontal",vspace:"Espacement vertical",dimensions:"Dimensions",border:"Bordure",list:"Liste d\'images",alt:"Description de l\'image",src:"URL de l\'image","dialog_title":"Ins\u00e9rer / \u00e9diter une image","missing_alt":"\u00cates-vous s\u00fbr de vouloir continuer sans d\u00e9finir de description pour l\'image ? Sans elle, l\'image peut ne pas \u00eatre accessible \u00e0 certains utilisateurs handicap\u00e9s, ceux utilisant un navigateur texte ou ceux qui naviguent sans affichage des images.","example_img":"Apparence de l\'image",misc:"Divers",mouseout:"\u00e0 la sortie de la souris",mouseover:"au survol de la souris","alt_image":"Image alternative","swap_image":"Image de remplacement",map:"Image cliquable",id:"Id",rtl:"De droite \u00e0 gauche",ltr:"De gauche \u00e0 droite",classes:"Classes",style:"Style","long_desc":"Description longue du lien",langcode:"Code de la langue",langdir:"Sens de lecture","constrain_proportions":"Conserver les proportions",preview:"Pr\u00e9visualisation",title:"Titre",general:"G\u00e9n\u00e9ral","tab_advanced":"Avanc\u00e9","tab_appearance":"Apparence","tab_general":"G\u00e9n\u00e9ral",width:"Largeur",height:"Hauteur",
// The New eXeLearning
"tab_caption":"En-t\u00EAte et l\u00E9gende de l\'image",
"recognition":"Titre et attribution",
"header":"En-t\u00EAte",
"image_title":"Titre de l\'image",
"image_title_link":"Lien tu titre",
"author_name":"Source/auteur",
"author_name_link":"Lien source/auteur",
"caption_license":"Licence",
"caption_select_license":"S\u00E9lectionner une licence...",
"public_domain":"Domaine public",
"all_rights_reserved":"Tous droits r\u00E9serv\u00E9s",
"block_presentation":"Pr\u00E9sentation",
"text_align":"Alignement du texte",
"align_left":"Gauche",
"align_center":"Centre",
"align_right":"Droite",
"image_and_caption_position":"Position de l\'ensemble",
"position_center":"Centre",
"position_normal":"Normal",
"image_and_caption_float":"Comportement",
"position_left":"\u00C0 gauche du texte",
"position_right":"\u00C0 droite du texte",
"image_and_caption_margin":"Marge de l\'ensemble",
"caption_explanation":"L\'en-t\u00EAte et la l\u00E9gende de l\'image ne seront pas editables \u00E0 partir de ce dialogue.",
"caption_warning":"L\'en-t\u00EAte et la l\u00E9gende de l\'image ne sont pas editables \u00E0 partir de ce dialogue. Vous pouvez les modifier ou les \u00E9liminer en \u00E9ditant le texte."
// The New eXeLearning
});