tinyMCE.addI18n('gl.advimage_dlg',{"image_list":"Lista de imaxes","align_right":"Dereita","align_left":"Esquerda","align_textbottom":"Texto abaixo","align_texttop":"Texto arriba","align_bottom":"Abaixo","align_middle":"Medio","align_top":"Arriba","align_baseline":"Li\u00f1a base",align:"Ali\u00f1amento",hspace:"Espacio horizontal",vspace:"Espacio vertical",dimensions:"Dimensi\u00f3ns",border:"Bordes",list:"Lista de imaxes",alt:"Descripci\u00f3n da imaxe",src:"URL da imaxe","dialog_title":"Insertar/editar imaxe","missing_alt":"\u00bfEsta seguro de continuar sen introducir unha descripci\u00f3n \u00e1 imaxe? Sen ela pode non ser accesible pra usuarios con discapacidades, ou pra aqueles que usen navegadores de modo texto, ou te\u00f1an deshabilitadas as imaxes da p\u00e1xina.","example_img":"Vista previa da imaxe",misc:"Miscel\u00e1neo",mouseout:"pra mouseout",mouseover:"pra mouseover","alt_image":"Imaxe alternativa","swap_image":"Intercambiar imaxe",map:"Mapa de imaxe",id:"Id",rtl:"Dereita a esquerda",ltr:"Esquerda a dereita",classes:"Clases",style:"Estilos","long_desc":"V\u00ednculo pra descripci\u00f3n larga",langcode:"C\u00f3digo do idioma",langdir:"Direcci\u00f3n do idioma","constrain_proportions":"Bloquear proporci\u00f3ns",preview:"Vista previa",title:"T\u00edtulo",general:"Xeral","tab_advanced":"Avanzado","tab_appearance":"Apariencia","tab_general":"Xeral",width:"Ancho",height:"Algo",
// The New eXeLearning
"tab_caption":"Encabezado y pie de foto",
"recognition":"T\u00EDtulo y reconocimiento",
"header":"Encabezado",
"image_title":"T\u00EDtulo de la imagen",
"image_title_link":"Enlace del t\u00EDtulo",
"author_name":"Origen/autor",
"author_name_link":"Enlace origen/autor",
"caption_license":"Licencia",
"caption_select_license":"Seleccionar...",
"public_domain":"Dominio p\u00FAblico",
"all_rights_reserved":"Todos los derechos reservados",
"block_presentation":"Presentaci\u00F3n",
"text_align":"Alineaci\u00F3n del texto",
"align_left":"Izquierda",
"align_center":"Centro",
"align_right":"Derecha",
"image_and_caption_position":"Posici\u00F3n del conjunto",
"position_center":"Centro",
"position_normal":"Normal",
"image_and_caption_float":"Comportamiento",
"position_left":"A la izquierda del texto",
"position_right":"A la derecha del texto",
"image_and_caption_margin":"Margen del conjunto",
"caption_explanation":"El encabezado y el pie de foto no ser\u00E1n editables desde este di\u00E1logo.",
"caption_warning":"El encabezado y el pie de foto no se pueden editar desde este di\u00E1logo. Puede modificarlos o borrarlos editando su texto."
// The New eXeLearning
});