tinyMCE.addI18n('nl.advimage_dlg',{"image_list":"Lijst","align_right":"Rechts","align_left":"Links","align_textbottom":"Onderkant tekst","align_texttop":"Bovenkant tekst","align_bottom":"Onder","align_middle":"Midden","align_top":"Boven","align_baseline":"Basislijn",align:"Uitlijning",hspace:"Horizontale ruimte",vspace:"Verticale ruimte",dimensions:"Afmetingen",border:"Rand",list:"Lijst",alt:"Beschrijving",src:"Bestand/URL","dialog_title":"Afbeelding invoegen/bewerken","missing_alt":"Wilt u de afbeelding zonder beschrijving invoegen? De afbeelding wordt dan mogelijk niet opgemerkt door mensen met een visuele handicap, of mensen die zonder afbeeldingen browsen.","example_img":"Voorbeeldweergave",misc:"Diversen",mouseout:"Bij muis uit",mouseover:"Bij muis over","alt_image":"Alternatieve afbeeldingen","swap_image":"Afbeelding wisselen",map:"Afbeeldingsplattegrond",id:"Id",rtl:"Van rechts naar links",ltr:"Van links naar rechts",classes:"Klasses",style:"Stijl","long_desc":"Uitgebreide beschrijving",langcode:"Taalcode",langdir:"Taalrichting","constrain_proportions":"Verhouding behouden",preview:"Voorbeeld",title:"Titel",general:"Algemeen","tab_advanced":"Geavanceerd","tab_appearance":"Weergave","tab_general":"Algemeen",width:"Breedte",height:"Hoogte",
// The New eXeLearning
"tab_caption":"Koptekst en bijschrift",
"recognition":"Titel en Naamsvermelding",
"header":"Koptekst",
"image_title":"Naam van de afbeelding",
"image_title_link":"Link naar titel",
"author_name":"Bron/Auteur",
"author_name_link":"Link naar Bron/Auteur",
"caption_license":"Licentie",
"caption_select_license":"Kies een licentie...",
"public_domain":"Public Domain",
"all_rights_reserved":"Alle rechten voorbehouden",
"block_presentation":"Presentatie",
"text_align":"Uitlijning tekst",
"align_left":"Links",
"align_center":"Midden",
"align_right":"Rechts",
"image_and_caption_position":"Groepspositie",
"position_center":"Midden",
"position_normal":"Geen",
"image_and_caption_float":"Drijven",
"position_left":"Links",
"position_right":"Rechts",
"image_and_caption_margin":"Groepsmarge",
"caption_explanation":"Het is niet mogelijk om de koptekst of het onderschrift van de afbeelding aan te passen in dit dialoogvenster.",
"caption_warning":"Je kunt de koptekst of het onderschrift van de afbeelding niet aanpassen in dit dialoogvenster. Je kunt deze onderdelen wel wijzigen of verwijderen door de tekst zelf te bewerken."
// The New eXeLearning
});