tinyMCE.addI18n('pt.advimage_dlg',{"image_list":"Lista de imagens","align_right":"Direita","align_left":"Esquerda","align_textbottom":"Base do texto","align_texttop":"Topo do texto","align_bottom":"Abaixo","align_middle":"Meio","align_top":"Topo","align_baseline":"Sobre a linha de texto",align:"Alinhamento",hspace:"Espa\u00e7o horizontal",vspace:"Espa\u00e7o vertical",dimensions:"Dimens\u00f5es",border:"Limite",list:"Lista de imagens",alt:"Descri\u00e7\u00e3o da imagem",src:"Endere\u00e7o da imagem","dialog_title":"Inserir/editar imagem","missing_alt":"Tem certeza que deseja continuar sem acrescentar uma descri\u00e7\u00e3o \u00e0 imagem? (Isto pode gerar problemas de acessibilidade em alguns navegadores)","example_img":"Pr\u00e9-Visualiza\u00e7\u00e3o",misc:"Misto",mouseout:"mouseout",mouseover:"mouseover","alt_image":"Imagem alternativa","swap_image":"Trocar imagem",map:"Mapa de imagem",id:"Id",rtl:"Da direita para a esquerda",ltr:"Da esquerda para a direita",classes:"Classes",style:"Estilo","long_desc":"Descri\u00e7\u00e3o extensa",langcode:"C\u00f3digo do idioma",langdir:"Dire\u00e7\u00e3o do texto","constrain_proportions":"Manter propor\u00e7\u00f5es",preview:"Pr\u00e9-Visualiza\u00e7\u00e3o",title:"T\u00edtulo",general:"Geral","tab_advanced":"Avan\u00e7ado","tab_appearance":"Apar\u00eancia","tab_general":"Geral",width:"Largura",height:"Altura",
// The New eXeLearning
"tab_caption":"Cabe\u00E7alho e legenda",
"recognition":"T\u00EDtulo e reconhecimento da autoria",
"header":"Cabe\u00E7alho",
"image_title":"T\u00EDtulo da imagem",
"image_title_link":"Liga\u00E7\u00E3o do t\u00EDtulo",
"author_name":"Fonte / Autoria",
"author_name_link":"Liga\u00E7\u00E3o \u00E0 fonte / autoria",
"caption_license":"Licen\u00E7a",
"caption_select_license":"Escolha uma licen\u00E7a...",
"public_domain":"Dom\u00EDnio p\u00FAblico",
"all_rights_reserved":"Todos os direitos reservados",
"block_presentation":"Apresenta\u00E7\u00E3o",
"text_align":"Alinhamento do texto",
"align_left":"\u00C0 esquerda",
"align_center":"Centrado",
"align_right":"\u00C0 direita",
"image_and_caption_position":"Posi\u00E7\u00E3o do bloco",
"position_center":"Centrado",
"position_normal":"Nenhuma",
"image_and_caption_float":"Flutuante",
"position_left":"\u00C0 esquerda",
"position_right":"\u00C0 direita",
"image_and_caption_margin":"Margens do bloco",
"caption_explanation":"N\u00E3o \u00E9 poss\u00EDvel editar o cabe\u00E7alho e a legenda da imagem neste di\u00E1logo.",
"caption_warning":"N\u00E3o \u00E9 poss\u00EDvel editar o cabe\u00E7alho e a legenda da imagem neste di\u00E1logo. Para os modificar ou apagar, edite o texto."
// The New eXeLearning
});