$i18n = {
	Interactive_Video_Editor : "Editor de vídeos interactivos",
	Delete : "Borrar",
	Save_as : "Guardar como...",
	Preview : "Previsualizar",
	Save : "Guardar",
	Quit : "Salir",
	Messages : "Mensajes (avisos, confirmación...)",
	Help : "Ayuda",
	Close_Help : "Cerrar la ayuda",
	Front_Page : "Portada",
	Create_Front_Page : "Crear una portada",
	Create : "Crear",
	Create_Frame : "Crear un fotograma",
	// Buttons
	Create_Frame_Submit : "Crear fotograma",
	Update_Frame_Submit : "Actualizar fotograma",
	Edit : "Editar",
	Edit_Frame : "Editar un fotograma",
	Create_a_front_page : "Crea una portada",
	Add_new_frames : "Añade fotogramas",
	You_can_edit_them_later : "Después podrás editarlos",
	Click_on_Save_when_you_finish : "Haz clic en Guardar cuando termines",
	Extra_instructions : "También puedes guardar una copia del contenido, previsualizarlo o eliminarlo desde el menú superior.",
	Your_Interactive_Video_Cover : "La portada de tu vídeo interactivo",
	Title : "Título",
	required : "obligatorio",
	Introduction : "Introducción",
	Save_Front_Page : "Guardar portada",
	// Types
	Text : "Texto",
	Image : "Imagen",
	Single_Choice : "Respuesta única",
	Multiple_Choice : "Respuesta múltiple",
	Cloze_Quiz : "Rellenar huecos",
	Dropdown_Activity : "Desplegable",
	Pairs_Game : "Emparejado",
	Scrambled_List : "Lista desordenada",
	// Types instructions
	Text_Instructions : "Escribe el texto que se mostrará en el segundo especificado. Puedes usar código HTML.",
	Image_Instructions : "Muestra una imagen de la Mediateca en el segundo especificado. Selecciona una imagen (escribe su dirección o ve a &quot;Mis imágenes&quot;) y escribe un pequeño texto que la describa.",
	Single_Choice_Instructions : "Escribe la pregunta y sus respuestas. No olvides seleccionar la respuesta correcta.",
	Multiple_Choice_Instructions : "Escribe la pregunta y sus respuestas. Puede haber más de una respuesta correcta.",
	Cloze_Quiz_Instructions : "Escribe un texto y tacha las palabras a completar. La ortografía (tildes, mayúsculas...) se tendrá en cuenta. Puedes incluir las instrucciones en el propio texto.",
	Dropdown_Activity_Instructions : "Escribe un texto y tacha las palabras a completar. Donde esté cada palabra tachada se mostrará un desplegable con todas las opciones, incluidas las de la pestaña \"Añadir opciones\". Puedes incluir las instrucciones en el propio texto.",
	Pairs_Game_Instructions : "Escribe las instrucciones y añade las parejas en el orden correcto.",
	Scrambled_List_Instructions : "Escribe el anunciado (la pregunta) y añade elementos a la lista (en el orden correcto).",	
	// Text
	Text_to_show : "Escribe el texto a mostrar",
	// Image
	General : "General",
	My_images : "Mis imágenes",
	Example : "Example",
	Alternative_Text : "Texto alternativo",
	Your_images : "Tus imágenes",
	Question : "Pregunta",
	Answers : "Respuestas",
	Right_Answer : "Correcta",
	// Cloze
	Cloze_Quiz_Instructions : "<strong>Tacha las palabras</strong> a completar. Es sensible a mayúsculas, minúsculas, etc.",
	Text_to_complete : "Texto a completar",
	// Dropdown
	Add_Options : "Añadir opciones",
	You_can_add_more_options_to_the_dropdown_lists : "Si quieres puedes añadir más opciones a los desplegables",
	// Pairs
	Instructions : "Instrucciones",
	Pairs : "Parejas",
	Introduction_or_instructions : "Introducción o instrucciones",
	Fill_in_at_least_two_pairs : "Rellena al menos dos filas correctamente emparejadas.",
	// Scrambled List
	List : "Lista",
	List_elements : "Elementos a ordenar (en el orden correcto)",
	// Edition
	You_should_create_a_Frame_first : "Primero debes crear algún fotograma."
}