$i18n = {
	Interactive_Video_Editor : _("Interactive video editor"),
	Delete : _("Delete"),
	Save : _("Save"),
	Quit : _("Exit"),
	Help : _("Help"),
	Toggle_Help : _("Show/Hide help"),
	Close_Help : _("Close help"),
	Front_Page : _("Cover"),
	Create_Front_Page : _("Create a cover"),
	Create : _("Create"),
	Create_Frame : _("Create a slide"),
	// Buttons
	Create_Frame_Submit : _("Create slide"),
	Update_Frame_Submit : _("Update slide"),
	Edit : _("Edit"),
	Edit_Frame : _("Edit slides"),
	Create_a_front_page : _("Create a cover (front page)"),
	Add_new_frames : _("Add new slides (frames)"),
	You_can_edit_them_later : _("You can edit them later"),
	Click_on_Save_when_you_finish : _("Click on Save when you finish"),
	Your_Interactive_Video_Cover : _("Your interactive video cover"),
	Title : _("Title"),
	required : _("required"),
	Introduction : _("Introduction"),
	Save_Front_Page : _("Save cover"),
	// Types
	Text : _("Text"),
	Image : _("Image"),
	Single_Choice : _("Single choice"),
	Multiple_Choice : _("Multiple choice"),
	Cloze_Quiz : _("Fill in the blank"),
	Dropdown_Activity : _("Dropdown activity"),
	Pairs_Game : _("Match pairs"),
	Scrambled_List : _("Scrambled list"),
	// Types instructions
	Text_Instructions : _("Write a text. You can add lists, links..."),
	Image_Instructions : _("Add an image with description (alternative text)."),
	Single_Choice_Instructions : _("Write a question and some answers. Don't forget to choose the right one."),
	Multiple_Choice_Instructions : _("Write a question and some answers. You can select more than one right answer."),
	Cloze_Quiz_Instructions : _("Write a text and strike through the words to complete. Check the spelling. It's case sensitive."),
	Dropdown_Activity_Instructions : _("Write a text and strike through the words to complete. A dropdown menu (SELECT) will be displayed where those words are. You can also add more options."),
	Pairs_Game_Instructions : _("Write some instructions and add pairs in the right order."),
	Scrambled_List_Instructions : _("Write the wording and add elements to the list (in the right order)."),	
	// Text
	Text_to_show : _("Write the text to be shown"),
	Question : _("Question"),
	Answers : _("Answers"),
	Right_Answer : _("Right answer"),
	// Cloze
	Cloze_Quiz_Instructions : _("Strike through the words to complete. It's case sensitive."),
	Text_to_complete : _("Text to complete"),
	// Dropdown
	Add_Options : _("Add options"),
	You_can_add_more_options_to_the_dropdown_lists : _("You can add more options to the dropdown lists (optional)"),
	// Pairs
	Instructions : _("Instructions"),
	Pairs : _("Pairs"),
	Introduction_or_instructions : _("Introduction or instructions"),
	Fill_in_at_least_two_pairs : _("Fill in at least two pairs."),
	// Scrambled List
	List : _("List"),
	List_elements : _("Elements (it the right order)"),
	// Edition
	You_should_create_a_Frame_first : _("Please create a slide (frame) first."),
	No_Title : _("The title is required."),
	Cover_Updated : _("Cover updated."),
	No_Text : _("Please write a text."),
	No_Image : _("Please add an image."),
	No_Alt : _("Provide an alternative text (describe the image)."),
	No_Question : _("Please write a question."),
	At_Least_2_Answers : _("Add at least two answers."),
	No_Right_Answer : _("Please choose the right answer."),
	No_ST_Words : _("No struck-through words..."),
	No_Introduction : _("Write an introduction (instructions, etc.)."),
	At_Least_2_Pairs : _("Add at least two pairs."),
	At_Least_2_Elements : _("Add at least two elements to the list."),
	Important : _("Important"),
	Click_On_Save_Warning : _("Your changes won't be saved until you click on \"Save\"."),
	Hide_Warning : _("Do not show this message again"),
	All_Frames_Deleted : _("All the slides have been deleted."),
	Type : _("Type"),
	Num : _("Num."),
	Start : _("Start"),
	End : _("End"),
	Actions : _("Actions"),
	Delete_Slide_X : _("Remove slide %?"),
	Slides_List : _("Slides list"),
	New_Slide : _("New slide"),
	Frame_Created : _("The slide was created!"),
	Changes_Saved : _("Saved changes!"),
	Accept : _("Accept"),
	Cancel : _("Cancel"),
	Code_Error : _("Could not retrieve data (Core error)"),
	Youtube_API_Changed : _("The Youtube API might have changed."),
	Local_File : _("Local file"),
	Invalid_URL : _("Please type or paste a valid URL."),
	Saved : _("Saved!"),
	Click_On_Exit : _("Click on \"Exit\" to finish."),
	Stop_Video : _("Stop the playing video"),
	Hours : _("Hours"),
	Minutes : _("Minutes"),
	Seconds : _("Seconds"),
	Now : _("Now"),
	Current_Time : _("Current frame second"),
	Second_Zero_Warning : _("The slide can't start in that second (zero)."),
	Time_Exceed_Warning : _("The video is not that long. Check the start/end time."),
	Time_Mismatch : _("Please check the start/end time."),
	Check_Start : _("Please check the \"Start\" time"),
	Check_End : _("Please check the \"End\" time"),
	Start_Instructions : _("Set the time for the slide to be shown"),
	End_Instructions : _("If you don't want the video to stop, set the time for the slide to be hidden"),
	Get_Time_Instructions : _("Click on % to get the video current time.")
}