$i18n = {
	Interactive_Video_Editor : "Interactive video editor",
	Delete : "Delete",
	Save : "Save",
	Quit : "Exit",
	// Messages : "Mensajes (avisos, confirmación...)",
	Help : "Help",
	Toggle_Help : "Show/Hide help",
	Close_Help : "Close help",
	Front_Page : "Cover",
	Create_Front_Page : "Create a cover",
	Create : "Create",
	Create_Frame : "Create a slide",
	// Buttons
	Create_Frame_Submit : "Create slide",
	Update_Frame_Submit : "Update slide",
	Edit : "Edit",
	Edit_Frame : "Edit slides",
	Create_a_front_page : "Create a cover (front page)",
	Add_new_frames : "Add new slides (frames)",
	You_can_edit_them_later : "You can edit them later",
	Click_on_Save_when_you_finish : "Click on Save when you finish",
	Your_Interactive_Video_Cover : "Your interactive video cover",
	Title : "Title",
	required : "required",
	Introduction : "Introduction",
	Save_Front_Page : "Save cover",
	// Types
	Text : "Text",
	Image : "Image",
	Single_Choice : "Single choice",
	Multiple_Choice : "Multiple choice",
	Cloze_Quiz : "Fill in the blank",
	Dropdown_Activity : "Dropdown activity",
	Pairs_Game : "Match pairs",
	Scrambled_List : "Scrambled list",
	// Types instructions
	Text_Instructions : "Write a text. You can add lists, links...",
	Image_Instructions : "Add an image with description (alternative text).",
	Single_Choice_Instructions : "Write a question and its answers. Don't forget to choose the right one.",
	Multiple_Choice_Instructions : "Write a question and its answers. You can select more than one right answer.",
	Cloze_Quiz_Instructions : "Write a text and strike through the words to complete. Check the spelling. It's case sensitive.",
	Dropdown_Activity_Instructions : "Write a text and strike through the words to complete. A dropdown menu (SELECT) will be displayed where those words are. You can add more options to those menus too.",
	Pairs_Game_Instructions : "Write some instructions and add pairs in the right order.",
	Scrambled_List_Instructions : "Write the wording and add elements to the list (in the right order).",	
	// Text
	Text_to_show : "Write the text to be shown",
	// Image
	// General : "General",
	// My_images : "Mis imágenes",
	// Example : "Example",
	// Alternative_Text : "Texto alternativo",
	// Your_images : "Tus imágenes",
	Question : "Question",
	Answers : "Answers",
	Right_Answer : "Right answer",
	// Cloze
	Cloze_Quiz_Instructions : "<strong>Strike through the words</strong> to complete. It's case sensitive.",
	Text_to_complete : "Text to complete",
	// Dropdown
	Add_Options : "Add options",
	You_can_add_more_options_to_the_dropdown_lists : "You can add more options to the dropdown menus (optional)",
	// Pairs
	Instructions : "Instructions",
	Pairs : "Pairs",
	Introduction_or_instructions : "Introduction or instructions",
	Fill_in_at_least_two_pairs : "Fill in at least two pairs.",
	// Scrambled List
	List : "List",
	List_elements : "Elements (it the right order)",
	// Edition
	You_should_create_a_Frame_first : "Please create a slide (frame) first.",
	No_Title : "The title is required.",
	Cover_Updated : "Cover updated.",
	No_Text : "Please write a text.",
	No_Image : "Please add an image.",
	No_Alt : "Provide an alternative text (describe the image).",
	No_Question : "Please write a question.",
	At_Least_2_Answers : "Add at least two answers.",
	No_Right_Answer : "Please choose the right answer.",
	No_ST_Words : "No struck-through words...",
	No_Introduction : "Write an introduction (instructions, etc.).",
	At_Least_2_Pairs : "Add at least two pairs.",
	At_Least_2_Elements : "Add at least two elements to the list.",
	Important : "Important",
	Click_On_Save_Warning : "Your changes won't be saved until you click on \"Save\".",
	Hide_Warning : "Do not show this message again",
	All_Frames_Deleted : "All the slides have been deleted.",
	Type : "Type",
	Num : "Num.",
	Start : "Start",
	End : "End",
	Actions : "Actions",
	Delete_Slide_X : "Remove slide %?",
	Slides_List : "Slides list",
	New_Slide : "New slide",
	Frame_Created : "The slide was created!",
	Changes_Saved : "Saved changes!",
	Accept : "Accept",
	Cancel : "Cancel",
	Code_Error : "Could not retrieve data (Core error)",
	Youtube_API_Changed : "The Youtube API might have changed.",
	Local_File : "Local file",
	Invalid_URL : "Please type or paste a valid URL.",
	Saved : "Saved!",
	Click_On_Exit : "Click on \"Exit\" to finish.",
	Stop_Video : "Stop the playing video",
	Hours : "Hours",
	Minutes : "Minutes",
	Seconds : "Seconds",
	Now : "Now",
	Current_Time : "Current frame second",
	Second_Zero_Warning : "The slide can't start in that second (zero).",
	Time_Exceed_Warning : "The video is not that long. Check the start/end time.",
	Time_Mismatch : "Please check the start/end time.",
	Check_Start : "Please check the \"Start\" time",
	Check_End : "Please check the \"End\" time",
	Start_Instructions : "Set the time for the slide to be shown",
	End_Instructions : "If you don't want the video to stop, set the time for the slide to be hidden",
	Get_Time_Instructions : "Click on % to get the video current time."
}