// EU lang variables

tinyMCE.addI18n('eu.exemath',{
desc : 'LaTeXetik Mathera',
contextmenu_update : 'LaTeX Math irudiaren ezaugarriak',
generate_title : 'LaTeX Math irudia eXerentzat',
verbose_font_size : 'Aukeratu letra-tipoaren tamaina:', 
font_size : 'Letra-tipoaren tamaina:',
compile_tooltip : 'Math irudia aurreikusi',
compile_label:  'Aurreikusi',
latex_source : 'Latex kodea sartu:',
image_src : 'Sortutako Math irudia',
image_alt : 'Irudiaren deskribapena:',
tab_general : 'Sorgailua',
tab_appearance : 'Irudiaren itxura',
insert_text: 'Testu edukia',
insert_newline: 'Lerro berria',
verbose_insert_symbols: 'Sinboloen LaTeX kodea txertatu:',
insert_symbols: ' ',
verbose_insert_latex: 'Latex kodea erantsi:',
insert_latex: ' ',
constrain_proportions : 'Proportzioak mantendu',
style : 'Estiloa',
example_img : 'Nola ikusiko den',
//advimage_dlg
"image_list": "Irudi-zerrenda",
"align_right": "Eskuinean",
"align_left": "Ezkerrean",
"align_textbottom": "Testua behean",
"align_texttop": "Testua goian",
"align_bottom": "Behean",
"align_middle": "Tartean",
"align_top": "Goian",
"align_baseline": "Oinarri-marra",
align: "Alineazioa",
hspace: "Tarte horizontala",
vspace: "Tarte bertikala",
dimensions: "Tamaina",
border: "Inguruko marra",
list: "Irudi-zerrenda",
alt: "Irudiaren deskribapena",
src: "Irudiaren URL helbidea",
"dialog_title": "Irudia txertatu/editatu",
"missing_alt": "Irudiaren deskribapena gehitu gabe jarraitu nahi duzu? Hau horrela, ezgaitasunak dituztenentzat edo testu nabigatzaile bat darabiltenentzat ez da irisgarria izango.",
"example_img": "Nola ikusiko den",
misc: "Bestelakoak",
mouseout: "xagua kentzen denean",
mouseover: "xagua gainean dagoenean",
"alt_image": "Ordezko irudia",
"swap_image": "Irudia ordezkatu",
map: "Irudi-mapa",
id: "Id",
rtl: "Eskuinetik ezkerrera",
ltr: "Ezkerretik eskuinera",
classes: "Klaseak",
style: "Estiloa",
"long_desc": "Deskribapen luzearen lotura",
langcode: "Hizkuntza-kodea",
langdir: "Hizkuntzaren norabidea",
"constrain_proportions": "Proportzioak mantendu",
preview: "Aurrebista",
title: "Izenburua",
general: "Orokorra",
"tab_advanced": "Aurreratua",
"tab_appearance": "Itxura",
"tab_general": "Orokorra",
width: "Width",
height: "Height"
});