import os

Import('env dist install installDir')

pys = [
	'regxpcom.py',
	'tracer_demo.py',
    ]

pycs = map(env.Pyc, pys)
pyos = map(env.Pyo, pys)
allPyFiles = pys + pycs + pyos

dist += env.Install('#dist/pyxpcom/tools/', allPyFiles)
install += env.Install(os.path.join(installDir, 'pyxpcom', 'tools'), allPyFiles)
