if (typeof(_)=='undefined') {
    if (top) _ = top._
    else _ = function(str) {
        return str;
    }
}
var $i18n = {
    Assistant : _("Assistant"),
    Menu : _("Menu"),
    Previous : _("Previous"),
    Next : _("Next"),
    // New
    What_is_eXe : _('What is eXeLearning'),
    eXe_is : _('eXeLearning Is an open source program to create educational contents.'),
    With_eXe : _('With eXeLearning you can:'),
    With_eXe_Create : _('Create educational resources with different contents: texts, multimedia materials, interactive activities, internet links...'),
    With_eXe_Choose : _('Choose and customise the design of the resource'),
    With_eXe_Export : _('Export them into different formats: website, ePub, SCORM (for Moodle and other LMS)...'),	
    Guide_Intro : _('In this short guide we will explain how to use eXeLearning.'),
    Step_1_Objective : _('The first step is to create a new project.'),
    How_to_create_a_project : _('How to create a project'),
    Create_a_project : _('Create a project'),
    Go_to_Properties : _('Switch to the "Properties" tab.'),
    Fill_the_fields : _('Fill in the following fields:'),
    Title : _('Title'),
    Language : _('Language'),
    General_description : _('General description (about 150 characters)'),
    Authorship : _('Authorship'),
    Content_License : _('License'),
    Click_Save : _('Click "Save".'),
    Go_to_Authoring : _('Switch back to the "Content" tab.'),
    Remember_to_save : _('Remember to save your project whenever you change something.'),
    Now_you_can_add_pages : _('Now you can start adding pages to your project!'),
    How_to_add_pages : _('How to add pages'),
    Adding_pages : _('Adding Pages'),
    Outline_buttons_instructions : _('The buttons to manage the pages are on the left part of the screen, just over the block "Outline".'),
    Click_on_Add_Page : _('Click on "Add Page".'),
    Edit_name_instructions : _('Click on "Rename" or doubleclick on the page you had just created to change its name.'),
    Delete_page_instructions : _('You can delete it using "Delete".'),
    Move_pages_instructions : _('Create as many pages as you need and organise them to your liking by using the arrows that appear on the bottom of the block "Outline":'),
    Move_pages_image : _('Outline'),
    Now_you_can_add_content : _('Once the page is created you can add content.'),
    How_to_add_content : _('How to add content'),
    Adding_content : _('Adding content'),
    iDevices_position : _('On the bottom left of the screen there is an area iDevices.'),
    iDevices_definition : _('IDevices are blocks that you can add to your pages.'),
    iDevices_organization : _('They are organized by categories: interactive, non-interactive activities...'),
    A_simple_test : _('A simple test:'),
    Add_a_Free_Text_iDevice : _("Add a Free Text iDevice by clicking on its name (it's under Textual Information)."),
    Write : _('Write something.'),
    Save_what_you_wrote : _('Save it clicking on the button below the editor: '),
    Save_image : _('Save'),
    That_is_all : _("That's all! If you add another iDevice you will see that you can also use the buttons to choose the position that each iDevice fills:"),
    Try_other_iDevices : _('Test the different iDevices: Interactive Activities, Image Gallery...'),
    Creating_contents_is_easy : _("It's so easy to create contents."),
    Now_you_have_to_export : _('The only thing left is to export the project so you can view it in web format, include it in your LMS or allow other people to see and use it.'),
    How_to_export : _('How to export your project'),
    Export : _('Exporting a project'),
    Export_instructions_1 : _('Switch to "File" - "Export" and choose the format that suits you:'),
    Export_instructions_1_A : _('Web Site (browsable web pages). It is the same content that you can see  from Tools - Preview.'),
    Export_instructions_1_B : _('Single (HTML) Page (this combines all your pages into one so you can print your content).'),
    Export_instructions_1_C : _('ePub3 (e-book).'),
    Export_instructions_1_D : _('SCORM (to be used in Moodle and other LMS platforms).'),
    Export_instructions_2 : _('Name the folder or file exported and choose "Save".'),
    Export_is_finished : _("That's all! In such a simple way you have already created an educational resource."),
    Export_reminder : _('Remember that whenever you want to edit or modify the project you will only have to open your elp file with eXe and work with it. At the end you will only have to export it again.'),
    There_are_more_export_options : _('These are the most common options, but there are more. In the next section we will explain where to find them.'),
    Other_options : _('More Options'),
    Advanced_user_toggler_instructions : _('On the top of the screen you will find an option "Advanced user". If you enable it, more export options, new elements in the Properties tab and more tools will be shown.'),
    Other_help_options : _('Further help options:'),
    eXe_Tutorial : _('eXe Tutorial'),
    eXe_Forums : _('eXe Forums'),
    eXe_Forums_objective : _('(resolve your doubts)'),
    Report_an_Issue : _('Report an Issue'),
    More_information : _('Further information:'),
    About_eXe : _('About eXe'),
    Release_Notes : _('Release Notes'),	
    Legal_Notes : _('Legal Notes'),
    eXe_Web_Site : _('eXe Web Site'),
    New_window : _('Open Link in a New Window')
}