// UK lang variables

tinyMCE.addToLang('exemath',{
desc : 'LaTeX to Math for eXe',
contextmenu_update : 'LaTeX Math Image properties',
generate_title : 'Generate eXe LaTeX Math Image',
compile_tooltip : 'Generated Math Image',
latex_source : 'LaTeX source',
image_src : 'generated Math Image',
image_alt : 'Math Image description',
tab_general : 'eXe Math: Generate',
tab_appearance : 'eXe Math: Image Appearance',
insert_text: 'Insert verbatim text',
insert_newline: 'Insert new line',
insert_symbols: 'Or, insert any of the following symbols:',
tab_advanced : 'Advanced',
general : 'General',
title : 'Title',
preview : 'Preview',
constrain_proportions : 'Constrain proportions',
langdir : 'Language direction',
langcode : 'Language code',
long_desc : 'Long description link',
style : 'Style',
classes : 'Classes',
ltr : 'Left to right',
rtl : 'Right to left',
id : 'Id',
image_map : 'Image map',
swap_image : 'Swap image',
alt_image : 'Alternative image',
mouseover : 'for mouse over',
mouseout : 'for mouse out',
misc : 'Miscellaneous',
example_img : 'Appearance&nbsp;preview&nbsp;image',
missing_alt : 'Are you sure you want to continue without including an Image Description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.'
});
