// UK lang variables

tinyMCE.addToLang('exemath',{
generate_title : 'Generate eXe LaTeX Math Image',
desc : 'LaTeX to Math for eXe',
tab_general : 'eXe Math Image: Generate',
tab_appearance : 'eXe Math Image: Appearance',
tab_advanced : 'BOGUS Advanced',
compile_tooltip : 'Generate Math Image',
general : 'eXe Math Image Generation',
latex_source : 'LaTeX source',
preview : 'BOGUS eXe Math Preview (what IS the difference?!?!?)',
constrain_proportions : 'BOGUS Constrain proportions',
langdir : 'BOGUS Language direction',
langcode : 'BOGUS Language code',
image_src : 'eXe Math Image filename',
long_desc : 'BOGUS eXe Math Long description link',
image_alt : 'Math Image ALT description',
style : 'BOGUS Style',
classes : 'BOGUS Classes',
ltr : 'BOGUS Left to right',
rtl : 'BOGUS Right to left',
id : 'BOGUS Id',
image_map : 'BOGUS Image map',
swap_image : 'BOGUS Swap image',
alt_image : 'BOGUS Alternative image',
mouseover : 'BOGUS for mouse over',
mouseout : 'BOGUS for mouse out',
misc : 'BOGUS Miscellaneous',
example_img : 'Appearance&nbsp;preview&nbsp;image',
missing_alt : 'BOGUS Are you sure you want to continue without including an Image Description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.'
});
