import os

Import('env dist install installDir PYTHON_VER')

env.Append(INCLUDE=['..'])

LIBS = ['python%s' % PYTHON_VER, 'xpcom', 'xpcom_core', 'plds4', 'plc4', 'nspr4', 'pthread', 'dl', 'm', 'python2.4']
                                                            
loader = env.SharedLibrary('pyloader', 'pyloader.cpp', LIBS=LIBS)
dist += env.Install('#dist/Components', loader)
install += env.Install(os.path.join(installDir, 'components'), loader)

