// JR
// ES lang variables

tinyMCE.addToLang('table',{
general_tab : 'General',
advanced_tab : 'Avanzado',
general_props : 'Propiedades generales',
advanced_props : 'Propiedades avanzadas',
desc : 'Insertar una nueva tabla',
row_before_desc : 'Insertar fila (antes)',
row_after_desc : 'Insertar fila (después)',
delete_row_desc : 'Borrar fila',
col_before_desc : 'Insertar columna (antes)',
col_after_desc : 'Insertar columna (después)',
delete_col_desc : 'Borrar columna',
rowtype : 'Tipo de fila',
title : 'Insertar/Modicar tabla',
width : 'Ancho',
height : 'Alto',
cols : 'Columnas',
rows : 'Filas',
cellspacing : 'Espaciado de celda',
cellpadding : 'Relleno de celda',
border : 'Borde',
align : 'Alineación',
align_default : 'Defecto',
align_left : 'Izquierda',
align_right : 'Derecha',
align_middle : 'Centrado',
row_title : 'Propiedades de la fila',
cell_title : 'Propiedades de la celda',
cell_type : 'Tipo de celda',
row_desc : 'Propiedades de la fila',
cell_desc : 'Propiedades de la celda',
valign : 'Alineación vertical',
align_top : 'Arriba',
align_bottom : 'Abajo',
props_desc : 'Propiedades de la tabla',
bordercolor : 'Color del borde',
bgcolor : 'Color de fondo',
merge_cells_title : 'Unir celdas',
split_cells_desc : 'Dividir celdas unidas',
merge_cells_desc : 'Unir celdas',
cut_row_desc : 'Cortar fila',
copy_row_desc : 'Copiar fila',
paste_row_before_desc : 'Pegar filas (antes)',
paste_row_after_desc : 'Pegar filas (después)',
id : 'Id',
style: 'Estilo',
langdir : 'Dirección del lenguaje',
langcode : 'Código del lenguaje',
mime : 'Tipo MIME destino',
ltr : 'Izquierda a derecha',
rtl : 'Derecha a izquierda',
bgimage : 'Imagen de fondo',
summary : 'Resumen',
td : "Dato",
th : "Encabezado",
cell_cell : 'Actualizar celda actual',
cell_row : 'Actualizar todas las celdas en la fila',
cell_all : 'Actualizar todas las celdas en la tabla',
row_row : 'Actualizar fila actual',
row_odd : 'Actualizar filas impares',
row_even : 'Actualizar filas pares',
row_all : 'Actualizar todas las filas',
thead : 'Encabezado de la tabla',
tbody : 'Cuerpo de la tabla',
tfoot : 'Pie de la tabla',
del : 'Borrar tabla',
scope : 'Alcance',
row : 'Fila',
col : 'Columna',
rowgroup : 'Grupo de filas',
colgroup : 'Grupo de columnas',
col_limit : 'Ha superado el número máximo de columnas: {$cols}',
row_limit : 'Ha superado el número máximo de filas: {$rows}.',
cell_limit : 'Ha superado el número máximo de celdas: {$cells}.',
missing_scope: '¿Está seguro que desea continuar sin especificar el alcance del encabezado de celda? Sin él podría ser dificultoso para algunos usuarios entender el contenido o los datos mostrados en la tabla.',
caption : 'Título de la tabla'
});
