// ES lang variables

tinyMCE.addToLang('table',{
general_tab : 'General',
advanced_tab : 'Avanzado',
general_props : 'Propiedades generales',
advanced_props : 'Propiedades avanzadas',
desc : 'Inserta una nueva tabla',
row_before_desc : 'A&ntilde;adir fila antes',
row_after_desc : 'A&ntilde;adir fila despu&eacute;s',
delete_row_desc : 'Eliminar fila',
col_before_desc : 'A&ntilde;adir columna antes',
col_after_desc : 'A&ntilde;adir columna despu&eacute;s',
delete_col_desc : 'Eliminar columna',
rowtype : 'Ubicaci&oacute;n de la fila',
title : 'Insertar/Modificar tabla',
width : 'Ancho',
height : 'Alto',
cols : 'Columnas',
rows : 'Filas',
cellspacing : 'Celda-espacio',
cellpadding : 'Celda-padding',
border : 'Borde',
align : 'Alinear',
align_default : 'Por defecto',
align_left : 'Izquierda',
align_right : 'Derecha',
align_middle : 'Centro',
row_title : 'Propiedades de la fila',
cell_title : 'Propiedades de la celda',
cell_type : 'Tipo de celda',
row_desc : 'Propiedades de la fila',
cell_desc : 'Propiedades de la celda',
valign : 'Alineaci&oacute;n vertical',
align_top : 'Superior',
align_bottom : 'Inferior',
props_desc : 'Propiedades de la tabla',
bordercolor : 'Color borde',
bgcolor : 'Color fondo',
merge_cells_title : 'Combinar celdas',
split_cells_desc : 'Separar celdas combinadas',
merge_cells_desc : 'Combinar celdas',
cut_row_desc : 'Cortar fila',
copy_row_desc : 'Pegar fila',
paste_row_before_desc : 'Pegar fila antes',
paste_row_after_desc : 'Pegar fila despu&eacute;s',
id : 'Id',
style: 'Estilo',
langdir : 'Direcci&oacute;n idioma',
langcode : 'C&oacute;digo idioma',
mime : 'Tipo MIME destino',
ltr : 'Izquierda a derecha',
rtl : 'Derecha a izquierda',
bgimage : 'Imagen fondo',
summary : 'Resumen',
td : "Dato",
th : "Cabecera",
cell_cell : 'Actualizar celda actual',
cell_row : 'Actualizar todas las celdas de la fila',
cell_all : 'Actualizar todas las celdas de la tabla',
row_row : 'Actualizar fila actual',
row_odd : 'Actualizar filas impares',
row_even : 'Actualizar filas pares',
row_all : 'Actualizar todas las filas',
thead : 'Cabecera (thead)',
tbody : 'Cuerpo (tbody)',
tfoot : 'Pie de tabla (tfoot)',
del : 'Borrar tabla',
scope : '&Aacute;mbito (scope)',
row : 'Fila',
col : 'Col',
rowgroup : 'Row Group',
colgroup : 'Col Group',
col_limit : 'Ha excedido el m&aacute;ximo de columnas permitidas: {$cols}.',
row_limit : 'Ha excedido el m&aacute;ximo de filas permitidas: {$rows}.',
cell_limit : 'Ha excedido el m&aacute;ximo de celdas permitidas: {$cells}.',
missing_scope: '&iquest;Continuar sin especificar el &aacute;mbito de esta cabecera?\nEsto puede impedir a algunos usuarios la comprensi&oacute;n de la tabla.',
caption : 'T&iacute;tulo'
});
