// EU lang variables

tinyMCE.addToLang('table',{
general_tab : 'Orokorra',
advanced_tab : 'Aurreratua',
general_props : 'Ezaugarri orokorrak',
advanced_props : 'Ezaugarri aurreratuak',
desc : 'Taula berri bat txertatu',
row_before_desc : 'Txertatu lerroa aurretik',
row_after_desc : 'Txertatu lerroa ondoren',
delete_row_desc : 'Ezabatu lerroa',
col_before_desc : 'Txertatu zutabea aurretik',
col_after_desc : 'Txertatu zutabea ondoren',
delete_col_desc : 'Ezabatu zutabea',
rowtype : 'Lerro mota',
title : 'Txertatu/Aldatu taula',
width : 'Zabalera',
height : 'Altuera',
cols : 'Zutabeak',
rows : 'Lerroak',
cellspacing : 'Gelaxkaren tartea',
cellpadding : 'Gelaxkaren betegarria',
border : 'Ertza',
align : 'Lerrokatzea',
align_default : 'Lehenetsia',
align_left : 'Ezkerrera',
align_right : 'Eskuinera',
align_middle : 'Erdian',
row_title : 'Lerro ezaugarriak',
cell_title : 'Gelaxka ezaugarriak',
cell_type : 'Gelaxka mota',
row_desc : 'Lerro ezaugarriak',
cell_desc : 'Gelaxka ezaugarriak',
valign : 'Lerrokatze bertikala',
align_top : 'Goian',
align_bottom : 'Behean',
props_desc : 'Taula ezaugarriak',
bordercolor : 'Ertz kolorea',
bgcolor : 'Atzeko kolorea',
merge_cells_title : 'Bateratu gelaxkak',
split_cells_desc : 'Banatu bateratutako gelaxkak',
merge_cells_desc : 'Bateratu gelaxkak',
cut_row_desc : 'Moztu lerroa',
copy_row_desc : 'Kopiatu lerroa',
paste_row_before_desc : 'Itsatsi lerroa aurretik',
paste_row_after_desc : 'Itsatsi lerroa ondoren',
id : 'Id',
style: 'Estiloa',
langdir : 'Hizkuntzaren norabidea',
langcode : 'Hizkuntza-kodea',
mime : 'Helburuaren MIME mota',
ltr : 'Ezkerretik eskuinera',
rtl : 'Eskuinetik ezkerrera',
bgimage : 'Atzeko irudia',
summary : 'Laburpena',
td : "Datuak",
th : "Goiburua",
cell_cell : 'Eguneratu uneko gelaxka',
cell_row : 'Eguneratu lerroko gelaxka guztiak',
cell_all : 'Eguneratu gelaxka guztiak',
row_row : 'Eguneratu uneko lerroa',
row_odd : 'Eguneratu lerro bakoitiak',
row_even : 'Eguneratu lerro bikoitiak',
row_all : 'Eguneratu lerro guztiak',
thead : 'Taularen Goiburukoa',
tbody : 'Taularen Gorputza',
tfoot : 'Taularen Oina',
del : 'Ezabatu taula',
scope : 'Eremua (scope)',
row : 'Lerroa',
col : 'Zutabea',
rowgroup : 'Lerro Taldea',
colgroup : 'Zutabe Taldea',
col_limit : 'Zutabe kopuru maximoa ({$cols}) gainditu duzu.',
row_limit : 'Lerro kopuru maximoa ({$rows}) gainditu duzu.',
cell_limit : 'Gelaxka kopuru maximoa ({$cells}) gainditu duzu.',
missing_scope: 'Taularen goiburukoari eremu bat zehaztu gabe jarritu nahi duzula ziur zaude? Eremu hori gabe, ezintasunak dituzten erabiltzaileentzat zaila izango da taularen datuak ulertzea.',
caption : 'Taularen azpititulua'
});
