// ES lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Estilos --',
theme_code_desc : 'Editar c\u00F3digo fuente',
theme_code_title : 'Editor de c\u00F3digo HTML',
theme_code_wordwrap : 'Ajuste de l\u00EDnea',
theme_sub_desc : 'Sub\u00EDndice',
theme_sup_desc : 'Super\u00EDndice',
theme_hr_desc : 'Insertar barra horizontal',
theme_removeformat_desc : 'Borrar formato',
theme_custom1_desc : 'Su descripci\u00F3n personalizada aqu\u00ED',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensiones',
insert_image_vspace : 'Espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineaci\u00F3n',
insert_image_align_default : '-- Sin definir --',
insert_image_align_baseline : 'L\u00EDnea de base',
insert_image_align_top : 'Vertical',
insert_image_align_middle : 'Media',
insert_image_align_bottom : 'Inferior',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'Derecha',
theme_font_size : '-- Tama\u00F1o fuente --',
theme_fontdefault : '-- Familia fuente --',
theme_block : '-- Formato --',
theme_paragraph : 'P\u00E1rrafo',
theme_div : 'Capa (div)',
theme_address : 'Direcci\u00F3n',
theme_pre : 'Preformateado',
theme_h1 : 'Encabezado 1',
theme_h2 : 'Encabezado 2',
theme_h3 : 'Encabezado 3',
theme_h4 : 'Encabezado 4',
theme_h5 : 'Encabezado 5',
theme_h6 : 'Encabezado 6',
theme_blockquote : 'Cita larga (bloque)',
theme_code : 'C\u00F3digo',
theme_samp : 'Ejemplo c\u00F3digo',
theme_dt : 'T\u00E9rmino',
theme_dd : 'Definici\u00F3n',
theme_colorpicker_title : 'Seleccionar color',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Color de texto',
theme_backcolor_desc : 'Color de fondo',
theme_charmap_title : 'Seleccionar caracteres especiales',
theme_charmap_desc : 'Insertar caracteres especiales',
theme_visualaid_desc : 'Mostrar/Ocultar gu\u00EDas',
insert_anchor_title : 'A\u00F1adir/Editar ancla',
insert_anchor_name : 'Nombre del ancla',
theme_anchor_desc : 'A\u00F1adir/Editar ancla',
theme_insert_link_titlefield : 'T\u00EDtulo',
theme_clipboard_msg : 'Copiar/Cortar/Pegar no est\u00E1 disponible en este navegador.\n\u00BFM\u00E1s informaci\u00F3n?',
theme_path : 'Ruta',
cut_desc : 'Cortar',
copy_desc : 'Copiar',
paste_desc : 'Pegar',
link_list : 'Lista de enlaces',
image_list : 'Lista de im\u00E1genes',
browse : 'Examinar',
image_props_desc : 'Propiedades de la imagen',
newdocument_desc : 'Nuevo documento',
class_name : 'Clase',
newdocument : '\u00BFLimpiar todos los contenidos?',
about_title : 'Sobre TinyMCE',
about : 'Sobre TinyMCE',
license : 'Licencia',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Versi\u00F3n',
loaded_plugins : 'Plugins cargados',
help : 'Ayuda',
not_set : '-- Sin definir --',
close : 'Cerrar',
toolbar_focus : 'Saltar a la barra de herramientas - Alt+Q, Saltar al editor - Alt-Z, Saltar a la ruta actual - Alt-X',
invalid_data : 'Error: elementos no v\u00E1lidos. Marcados en rojo.',
more_colors : 'M\u00E1s colores',
color_picker_tab : 'Selector',
color_picker : 'Selector de color',
web_colors_tab : 'Paleta',
web_colors : 'Paleta de colores',
named_colors_tab : 'Por nombre',
named_colors : 'Colores por nombre',
color : 'Color:',
color_name : 'Nombre:',
is_email : 'La direcci\u00F3n parece un e-mail. \u00BFQuiere a\u00F1adir mailto: para enviar correo?',
is_external : 'La direcci\u00F3n parece un enlace externo. \u00BFQuiere a\u00F1adir http:...?'
});
