// JR 
// ES lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Estilos --',
theme_code_desc : 'Editar código HTML',
theme_code_title : 'Editor de código HTML',
theme_code_wordwrap : 'Ajustar al margen',
theme_sub_desc : 'Subíndice',
theme_sup_desc : 'Superíndice',
theme_hr_desc : 'Insertar regla horizontal',
theme_removeformat_desc : 'Borrar formato',
theme_custom1_desc : 'Su descripción personal aquí',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensiones',
insert_image_vspace : 'Espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineación',
insert_image_align_default : '-- No puesta --',
insert_image_align_baseline : 'Línea base',
insert_image_align_top : 'Arriba',
insert_image_align_middle : 'Medio',
insert_image_align_bottom : 'Abajo',
insert_image_align_texttop : 'Texto arriba',
insert_image_align_absmiddle : 'Medio absoluto',
insert_image_align_absbottom : 'Abajo absoluto',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'Derecha',
theme_font_size : '-- Tamaño fuentes --',
theme_fontdefault : '-- Familia fuentes --',
theme_block : '-- Formato --',
theme_paragraph : 'Párrafo',
theme_div : 'Div',
theme_address : 'Dirección',
theme_pre : 'Preformateado',
theme_h1 : 'Enabezado 1',
theme_h2 : 'Enabezado 2',
theme_h3 : 'Enabezado 3',
theme_h4 : 'Enabezado 4',
theme_h5 : 'Enabezado 5',
theme_h6 : 'Enabezado 6',
theme_blockquote : 'Cita',
theme_code : 'Código',
theme_samp : 'Ejemplo de código',
theme_dt : 'Término de definición',
theme_dd : 'Descripción de definición',
theme_colorpicker_title : 'Seleccionar un color',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Seleccionar color del texto',
theme_backcolor_desc : 'Seleccionar color del fondo',
theme_charmap_title : 'Elegir caracter personalizado',
theme_charmap_desc : 'Insertar caracteres personalizados',
theme_visualaid_desc : 'Mostrar/ocultar línea de guía/elementos invisibles',
insert_anchor_title : 'Insertar/editar ancla',
insert_anchor_name : 'Nombre del ancla',
theme_anchor_desc : 'Insertar/editar ancla',
theme_insert_link_titlefield : 'Título',
theme_clipboard_msg : 'Copiar/Cortar/Pegar no se encuentra disponible en Mozilla y Firefox.\n ¿Desea obtener más información acerca de este tema?',
theme_path : 'Ruta',
cut_desc : 'Cortar',
copy_desc : 'Copiar',
paste_desc : 'Pegar',
link_list : 'Lista de enlaces',
image_list : 'Lista de imágenes',
browse : 'Examinar',
image_props_desc : 'Propiedades de la imagen',
newdocument_desc : 'Documento nuevo',
class_name : 'Clase',
newdocument : '¿Seguro que desea limpiar todo el contenido?',
about_title : 'Acerca de TinyMCE',
about : 'Acerca de',
license : 'Licencia',
plugins : 'Complementos',
plugin : 'Complemento',
author : 'Autor',
version : 'Versión',
loaded_plugins : 'Complementos cargados',
help : 'Ayuda',
not_set : '-- Ninguno --',
close : 'Cerrar',
toolbar_focus : 'Ir a los botones de herramientas - Alt+Q, Ir al editor - Alt-Z, Ir a la ruta del elemento - Alt-X',
invalid_data : 'Error: Introdujo un valor no válido, están marcados en rojo.',
more_colors : 'Más colores',
color_picker_tab : 'Paleta',
color_picker : 'Paleta de colores',
web_colors_tab : 'Paleta',
web_colors : 'Paleta de colores',
named_colors_tab : 'Nombrados',
named_colors : 'Colores nombrados',
color : 'Color:',
color_name : 'Nombre:',
is_email : 'La URL que ha introducido parece ser una direción de correo,  ¿desea agregar el prefijo mailto: necesario?',
is_external : 'La URL que ha introducido parece ser un vínculo externo,  ¿desea agregar el prefijo http:// necesario?'
});
