// ES lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Estilos --',
theme_code_desc : 'Editar c&oacute;digo fuente',
theme_code_title : 'Editor de c&oacute;digo HTML',
theme_code_wordwrap : 'Ajuste de l&iacute;nea',
theme_sub_desc : 'Sub&iacute;ndice',
theme_sup_desc : 'Super&iacute;ndice',
theme_hr_desc : 'Insertar barra horizontal',
theme_removeformat_desc : 'Borrar formato',
theme_custom1_desc : 'Su descripci&oacute;n personalizada aqu&iacute;',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensiones',
insert_image_vspace : 'Espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineaci&oacute;n',
insert_image_align_default : '-- Sin definir --',
insert_image_align_baseline : 'L&iacute;nea de base',
insert_image_align_top : 'Vertical',
insert_image_align_middle : 'Media',
insert_image_align_bottom : 'Inferior',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'Derecha',
theme_font_size : '-- Tama&ntilde;o fuente --',
theme_fontdefault : '-- Familia fuente --',
theme_block : '-- Formato --',
theme_paragraph : 'P&aacute;rrafo',
theme_div : 'Capa (div)',
theme_address : 'Direcci&oacute;n',
theme_pre : 'Preformateado',
theme_h1 : 'Encabezado 1',
theme_h2 : 'Encabezado 2',
theme_h3 : 'Encabezado 3',
theme_h4 : 'Encabezado 4',
theme_h5 : 'Encabezado 5',
theme_h6 : 'Encabezado 6',
theme_blockquote : 'Cita larga (bloque)',
theme_code : 'C&oacute;digo',
theme_samp : 'Ejemplo c&oacute;digo',
theme_dt : 'T&eacute;rmino',
theme_dd : 'Definici&oacute;n',
theme_colorpicker_title : 'Seleccionar color',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Color de texto',
theme_backcolor_desc : 'Color de fondo',
theme_charmap_title : 'Seleccionar caracteres especiales',
theme_charmap_desc : 'Insertar caracteres especiales',
theme_visualaid_desc : 'Mostrar/Ocultar gu&iacute;as',
insert_anchor_title : 'A&ntilde;adir/Editar ancla',
insert_anchor_name : 'Nombre del ancla',
theme_anchor_desc : 'A&ntilde;adir/Editar ancla',
theme_insert_link_titlefield : 'T&iacute;tulo',
theme_clipboard_msg : 'Copiar/Cortar/Pegar no est&aacute; disponible en este navegador.\n&iquest;M&aacute;s informaci&oacute;n?',
theme_path : 'Path',
cut_desc : 'Cortar',
copy_desc : 'Copiar',
paste_desc : 'Pegar',
link_list : 'Lista de enlaces',
image_list : 'Lista de im&aacute;genes',
browse : 'Examinar',
image_props_desc : 'Propiedades de la imagen',
newdocument_desc : 'Nuevo documento',
class_name : 'Clase',
newdocument : '&iquest;Limpiar todos los contenidos?',
about_title : 'Sobre TinyMCE',
about : 'Acerca de',
license : 'Licencia',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Versi&oacute;n',
loaded_plugins : 'Plugins cargados',
help : 'Ayuda',
not_set : '-- Sin definir --',
close : 'Cerrar',
toolbar_focus : 'Saltar a la barra de herramientas - Alt+Q, Saltar al editor - Alt-Z, Saltar a la ruta actual - Alt-X',
invalid_data : 'Error: elementos no v&aacute;lidos. Marcados en rojo.',
more_colors : 'M&aacute;s colores',
color_picker_tab : 'Selector',
color_picker : 'Selector de color',
web_colors_tab : 'Paleta',
web_colors : 'Colores de la paleta',
named_colors_tab : 'Por nombre',
named_colors : 'Colores nombrados',
color : 'Color:',
color_name : 'Nombre:',
is_email : 'La direcci&oacute;n parece un e-mail. &iquest;Quiere a&ntilde;adir mailto: para enviar correo?',
is_external : 'La direcci&oacute;n parece un enlace externo. &iquest;Quiere a&ntilde;adir http:...?'
});
