// EU lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Estiloak --',
theme_code_desc : 'HTML kodea editatu',
theme_code_title : 'HTML kodearen editorea',
theme_code_wordwrap : 'Itzulbiratu',
theme_sub_desc : 'Azpi-indizea',
theme_sup_desc : 'Goi-indizea',
theme_hr_desc : 'Lerro horizontala gehitu',
theme_removeformat_desc : 'Formatua kendu',
theme_custom1_desc : 'Nahi duzun deskribapena hemen idatzi',
insert_image_border : 'Inguruko marra',
insert_image_dimensions : 'Tamaina',
insert_image_vspace : 'Tarte bertikala',
insert_image_hspace : 'Tarte horizontala',
insert_image_align : 'Alineazioa',
insert_image_align_default : '-- Defintu gabe --',
insert_image_align_baseline : 'Oinarriko marra',
insert_image_align_top : 'Goian',
insert_image_align_middle : 'Tartean',
insert_image_align_bottom : 'Behean',
insert_image_align_texttop : 'Testua goian',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Ezkerrean',
insert_image_align_right : 'Eskuinean',
theme_font_size : '-- Letra tamaina --',
theme_fontdefault : '-- Letra-mota --',
theme_block : '-- Formatua --',
theme_paragraph : 'Paragrafoa',
theme_div : 'Geruza (div)',
theme_address : 'Helbidea',
theme_pre : 'Aurreformateatua',
theme_h1 : '1. goiburua',
theme_h2 : '2. goiburua',
theme_h3 : '3. goiburua',
theme_h4 : '4. goiburua',
theme_h5 : '5. goiburua',
theme_h6 : '6. goiburua',
theme_blockquote : 'Zita',
theme_code : 'Kodea',
theme_samp : 'Kode adibidea',
theme_dt : 'Definizio terminoa (dt)',
theme_dd : 'Definizioa (dd)',
theme_colorpicker_title : 'Kolorea aukeratu',
theme_colorpicker_apply : 'Apikatu',
theme_forecolor_desc : 'Testuaren kolorea aukeratu',
theme_backcolor_desc : 'Atzeko kolorea aukeratu',
theme_charmap_title : 'Karaktere berezia aukeratu',
theme_charmap_desc : 'Karaktere berezia txertatu',
theme_visualaid_desc : 'Elementu ikustezinak ikustarazi/ezkutatu',
insert_anchor_title : 'Aingura txertatu/editatu',
insert_anchor_name : 'Ainguraren izena',
theme_anchor_desc : 'Aingura txertatu/editatu',
theme_insert_link_titlefield : 'Titulua',
theme_clipboard_msg : 'Kopiatu/Ebaki/Itsatsi ez dago Mozilla eta Firefoxen.\nHonen inguruko informazioa nahi duzu?',
theme_path : 'Bidea',
cut_desc : 'Ebaki',
copy_desc : 'Kopiatu',
paste_desc : 'Itsatsi',
link_list : 'Lotura zerrenda',
image_list : 'Irudi zerrenda',
browse : 'Arakatu',
image_props_desc : 'Irudiaren aukerak',
newdocument_desc : 'Dokumentu berria',
class_name : 'Klasea',
newdocument : 'Eduki guztia kendu nahi duzu?',
about_title : 'TinyMCEri buruz',
about : 'TinyMCEri buruz',
license : 'Lizentzia',
plugins : 'Gehigarriak',
plugin : 'Gehigarria',
author : 'Egilea',
version : 'Bertsioa',
loaded_plugins : 'Kargatutako gehigarriak',
help : 'Laguntza',
not_set : '-- Bat ere ez --',
close : 'Itxi',
toolbar_focus : 'Tresnaren botoietara joan - Alt+Q, Editorera joan - Alt-Z, Elementuaren bidera joan - Alt-X',
invalid_data : 'Errorea: baliogabeak diren aukerak sartu dituzu, gorriz agertzen dira.',
more_colors : 'Kolore gehiago',
color_picker_tab : 'Hautatzailea',
color_picker : 'Kolore hautatzailea',
web_colors_tab : 'Paleta',
web_colors : 'Kolore paleta',
named_colors_tab : 'Izenen arabera',
named_colors : 'koloreak izenen arabera',
color : 'Kolorea:',
color_name : 'Izena:',
is_email : 'Sartutako helbideak e-posta bat dirudi, aurretik mailto: gehitzea nahi duzu?',
is_external : 'Sartutako helbideak kanpoko webgune batena dirudi, aurretik http:// gehitzea nahi duzu?'
});
