// ES lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Cita',
abbr_desc : 'Abreviatura',
acronym_desc : 'Acr\u00F3nimo',
del_desc : 'Eliminado',
ins_desc : 'A\u00F1adido',
glosario_desc : 'Glosario',
codigo_desc : 'Código',
idioma_desc : 'Idioma',
attribute_label_title : 'T\u00EDtulo',
attribute_label_id : 'ID',
attribute_label_class : 'Clase',
attribute_label_style : 'Estilo',
attribute_label_cite : 'Cita',
attribute_label_datetime : 'Fecha/Hora',
attribute_label_langdir : 'Direcci\u00F3n texto',
attribute_option_ltr : 'Izquierda a derecha',
attribute_option_rtl : 'Derecha a izquierda',
attribute_label_langcode : 'Idioma',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'AccessKey',
attribute_label_cite : 'Cita',
attribute_events_tab : 'Eventos',
attribute_attrib_tab : 'Atributos',
attribute_label_ciclo : 'CF_SIGXX',
attribute_label_termino : 'Término',
codigo_label_title : 'Fragmento de código',
general_tab : 'General',
attrib_tab : 'Atributos',
events_tab : 'Eventos',
fieldset_general_tab : 'Preferencias generales',
fieldset_attrib_tab : 'Atributos',
fieldset_events_tab : 'Eventos',
fieldset_codigo_tab : 'Código',
title_ins_element : 'Elemento insertado',
title_del_element : 'Elemento borrado',
title_acronym_element : 'Acr\u00F3nimo',
title_abbr_element : 'Abreviatura',
title_cite_element : 'Cita',
title_glosario_element : 'Enlace a un término del glosario',
title_codigo_element : 'Fragmento o palabras de código',
title_idioma_element : 'Fragmento en otro idioma',
remove : 'Eliminar',
not_set : '-- No definido --',
insert_date : 'Insertar fecha/hora',
option_ltr : 'Izquierda a derecha',
option_rtl : 'Derecha a izquierda',
attribs_desc : 'Insertar/Editar atributos',
attribs_title : 'Insertar/Editar atributos'
});
