// JR
// ES lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Cita',
abbr_desc : 'Abreviatura',
acronym_desc : 'Acrónimo',
del_desc : 'Borrado',
ins_desc : 'Insertado',
glosario_desc : 'Glosario',
codigo_desc : 'Código',
idioma_desc : 'Idioma',
attribute_label_title : 'Título',
attribute_label_id : 'ID',
attribute_label_class : 'Clase',
attribute_label_style : 'Estilo',
attribute_label_cite : 'Cita',
attribute_label_datetime : 'Fecha/Hora',
attribute_label_langdir : 'Dirección del texto',
attribute_option_ltr : 'Izquierda a derecha',
attribute_option_rtl : 'Derecha a izquierda',
attribute_label_langcode : 'Lenguaje',
attribute_label_tabindex : 'Orden de tabulación',
attribute_label_accesskey : 'Tecla de acceso',
attribute_label_cite : 'Cita',
attribute_events_tab : 'Eventos',
attribute_attrib_tab : 'Atributos',
attribute_label_ciclo : 'CF_SIGXX',
attribute_label_termino : 'Término',
codigo_label_title : 'Fragmento de código',
general_tab : 'General',
attrib_tab : 'Atributos',
events_tab : 'Eventos',
fieldset_general_tab : 'Configuración general',
fieldset_attrib_tab : 'Atributos',
fieldset_events_tab : 'Eventos',
fieldset_codigo_tab : 'Código',
title_ins_element : 'Insertado',
title_del_element : 'Borrado',
title_acronym_element : 'Acrónimo',
title_abbr_element : 'Abreviatura',
title_cite_element : 'Cita',
title_glosario_element : 'Enlace a un término del glosario',
title_codigo_element : 'Fragmento o palabras de código',
title_idioma_element : 'Fragmento en otro idioma',
remove : 'Borrar',
not_set : '--Ninguno--',
insert_date : 'Insertar fecha/hora actuales',
option_ltr : 'Izquierda a derecha',
option_rtl : 'Derecha a izquierda',
attribs_desc : 'Insertar/Editar atributos',
attribs_title : 'Insertar/Editar atributos'
});
