// ES lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Cita',
abbr_desc : 'Abreviatura',
acronym_desc : 'Acr&oacute;nimo',
del_desc : 'Eliminado',
ins_desc : 'A&ntilde;adido',
attribute_label_title : 'T&iacute;tulo',
attribute_label_id : 'ID',
attribute_label_class : 'Clase',
attribute_label_style : 'Estilo',
attribute_label_cite : 'Cita',
attribute_label_datetime : 'Fecha/Hora',
attribute_label_langdir : 'Direcci&oacute;n texto',
attribute_option_ltr : 'Izquierda a derecha',
attribute_option_rtl : 'Derecha a izquierda',
attribute_label_langcode : 'Idioma',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'AccessKey',
attribute_label_cite : 'Cita',
attribute_events_tab : 'Eventos',
attribute_attrib_tab : 'Atributos',
general_tab : 'General',
attrib_tab : 'Atributos',
events_tab : 'Eventos',
fieldset_general_tab : 'Preferencias generales',
fieldset_attrib_tab : 'Atributos',
fieldset_events_tab : 'Eventos',
title_ins_element : 'Elemento insertado',
title_del_element : 'Elemento borrado',
title_acronym_element : 'Acr&oacute;nimo',
title_abbr_element : 'Abreviatura',
title_cite_element : 'Cita',
remove : 'Eliminar',
not_set : '-- No definido --',
insert_date : 'Insertar fecha/hora',
option_ltr : 'Izquierda a derecha',
option_rtl : 'Derecha a izquierda',
attribs_desc : 'Insertar/Editar atributos',
attribs_title : 'Insertar/Editar atributos'
});
