'\" t
.\"     Title: INTEF-EXE
.\"    Author: Juan Rafael Fern\('andez <jrfern@telefonica.net>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/28/2021
.\"    Manual: eXe User Manual
.\"    Source: exe
.\"  Language: English
.\"
.TH "INTEF\-EXE" "1" "03/28/2021" "exe" "eXe User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
exe \- The EXtremely Easy to use eLearning authoring tool
.SH "SYNOPSIS"
.HP \w'\fBexe\fR\ 'u
\fBexe\fR [{\fB\-h\fR\ |\ \fB\-\-help\fR} | {\fB\-V\fR\ |\ \fB\-\-version\fR} | \fB\-\-standalone\fR  | \fB\-\-portable\fR ]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBexe\fR
command\&.
.PP
\fBexe\fR
is a GPL2+ free/libre tool for the educational community to create and publish open educational resources\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes (`\-\*(Aq)\&. A summary of options is included below\&.

.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display this help and exit\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Print version information and exit\&.
.RE
.PP
\fB\-\-standalone\fR
.RS 4
Run totally from the current directory (doesn\*(Aqt use the system libraries)\&.
.RE
.PP
\fB\-\-portable\fR
.RS 4
Run in portable mode\&.
.RE
.SH "FILES"
.PP
${HOME}/\&.exe/exe\&.conf
.RS 4
The per\-user configuration file to control the behaviour of
exe\&.
.RE
.SH "BUGS"
.PP
The upstreams
BTS
can be found at
\m[blue]\fB\%https://github.com/exelearning/iteexe/issues\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBexe_do\fR(1)
.PP
The programs are documented fully by
eXeLearning Manual
available at
\m[blue]\fB\%http://exelearning.net/html_manual/exe20/\fR\m[]\&.
.SH "AUTHOR"
.PP
\fBJuan Rafael Fern\('andez\fR <\&jrfern@telefonica\&.net\&>
.RS 4
Wrote this manpage for the Debian system\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2015 Juan Rafael Fern\('andez
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
