// FI lang variables by Urho Konttori from Absolutions

tinyMCE.addToLang('',{
bold_desc : 'Lihavoi',
italic_desc : 'Kursivoi',
underline_desc : 'Alleviivaa',
striketrough_desc : 'Yliviivaa',
justifyleft_desc : 'Vasen tasaus',
justifycenter_desc : 'Keskitys',
justifyright_desc : 'Oikea tasaus',
justifyfull_desc : 'Pakotettu tasaus',
bullist_desc : 'Numeroimaton lista',
numlist_desc : 'Numeroitu lista',
outdent_desc : 'Poista sisennyt',
indent_desc : 'Sisennys',
undo_desc : 'Peruuta',
redo_desc : 'Suorita uudelleen',
link_desc : 'Lis&auml;&auml; linkki',
unlink_desc : 'Poista linkki',
image_desc : 'Lis&auml;&auml; kuva',
cleanup_desc : 'Siisti koodi',
focus_alert : 'Teksink&auml;sittelyalueella t&auml;ytyy olla fokus ennen t&auml;m&auml;n komennon suorittamista.',
edit_confirm : 'Haluatko k&auml;ytt&auml;&auml; WYSIWYG moodia t&auml;h&auml;n tekstialueeseen?',
insert_link_title : 'Lis&auml;&auml;/muokkaa linkki&auml;',
insert : 'Lis&auml;&auml;',
update : 'Lis&auml;&auml;',
cancel : 'Peruuta',
insert_link_url : 'Linkin URL',
insert_link_target : 'Kohde',
insert_link_target_same : 'Avaa linkki samassa ikkunassa',
insert_link_target_blank : 'Avaa linkki uudessa ikkunassa',
insert_image_title : 'Lis&auml;&auml;/muokkaa kuvaa',
insert_image_src : 'Kuvan URL',
insert_image_alt : 'Kuvan selite',
help_desc : 'Apua',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
