// JR
// ES lang variables

tinyMCE.addToLang('style',{
title : 'Editar Estilo CSS',
styleinfo_desc : 'Editar Estilo CSS',
apply : 'Aplicar',
text_tab : 'Texto',
background_tab : 'Fondo',
block_tab : 'Bloque',
box_tab : 'Caja',
border_tab : 'Borde',
list_tab : 'Lista',
positioning_tab : 'Posición',
text_props : 'Texto',
text_font : 'Fuente',
text_size : 'Tamaño',
text_weight : 'Peso',
text_style : 'Estilo',
text_variant : 'Variante',
text_lineheight : 'Ancho de la fila',
text_case : 'Minús./Mayús.',
text_color : 'Color',
text_decoration : 'Decoración',
text_overline : 'Subrayado superior',
text_underline : 'Subrayado',
text_striketrough : 'Tachado',
text_blink : 'Parpadeo',
text_none : 'none',
background_color : 'Color de fondo',
background_image : 'Imagen de fondo',
background_repeat : 'Repetición',
background_attachment : 'Adjunto',
background_hpos : 'Posición horizontal',
background_vpos : 'Posición vertical',
block_wordspacing : 'Espacio entre palabra',
block_letterspacing : 'Especio entre letra',
block_vertical_alignment : 'Alineación vertical',
block_text_align : 'Alineación del texto',
block_text_indent : 'Sangría',
block_whitespace : 'Espacio en blanco',
block_display : 'Display',
box_width : 'Ancho',
box_height : 'Alto',
box_float : 'Float',
box_clear : 'Clear',
padding : 'Padding',
same : 'Lo mismo en todos',
top : 'Arriba',
right : 'Derecha',
bottom : 'Debajo',
left : 'Izquierda',
margin : 'Margen',
style : 'Estilo',
width : 'Ancho',
height : 'Alto',
color : 'Color',
list_type : 'Tipo',
bullet_image : 'Imagen de la viñeta',
position : 'Posición',
positioning_type : 'Tipo',
visibility : 'Visibilidad',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Placement',
clip : 'Clip'
});
