// ES lang variables

tinyMCE.addToLang('style',{
title : 'Editar CSS',
styleinfo_desc : 'Editar CSS',
apply : 'Aplicar',
text_tab : 'Texto',
background_tab : 'Fondo',
block_tab : 'Bloque',
box_tab : 'Caja',
border_tab : 'Borde',
list_tab : 'Listas',
positioning_tab : 'Posici&oacute;n',
text_props : 'Texto',
text_font : 'Fuente',
text_size : 'Tama&ntilde;o',
text_weight : 'Peso',
text_style : 'Estilo',
text_variant : 'Variante',
text_lineheight : 'Interlineado',
text_case : 'Mayus./Min.',
text_color : 'Color',
text_decoration : 'Decoraci&oacute;n',
text_overline : 'L&iacute;nea encima',
text_underline : 'Subrayado',
text_striketrough : 'Tachado',
text_blink : 'Parpadeo',
text_none : 'Ninguna',
background_color : 'Color fondo',
background_image : 'Imagen fondo',
background_repeat : 'Repetir',
background_attachment : 'Relaci&oacute;n',
background_hpos : 'Pos. horizontal',
background_vpos : 'Pos. vertical',
block_wordspacing : 'Espacio entre palabras',
block_letterspacing : 'Interletrado',
block_vertical_alignment : 'Alineaci&oacute;n vertical',
block_text_align : 'Alineaci&oacute;n texto',
block_text_indent : 'Indentado texto',
block_whitespace : 'Romper palabras',
block_display : 'Mostrar',
box_width : 'Ancho',
box_height : 'Alto',
box_float : 'Flotar',
box_clear : 'Despejar',
padding : 'Padding',
same : 'Igual para todos',
top : 'Arriba',
right : 'Derecha',
bottom : 'Abajo',
left : 'Izquierda',
margin : 'Margen',
style : 'Estilo',
width : 'Ancho',
height : 'Altura',
color : 'Color',
list_type : 'Tipo',
bullet_image : 'Imagen elementos lista',
position : 'Posici&oacute;n',
positioning_type : 'Tipo',
visibility : 'Visibilidad',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Ubicaci&oacute;n',
clip : 'Clip'
});
