// EU lang variables

tinyMCE.addToLang('style',{
title : 'Aldatu CSS estiloa',
styleinfo_desc : 'Aldatu CSS estiloa',
apply : 'Apikatu',
text_tab : 'Testua',
background_tab : 'Atzea',
block_tab : 'Blokea',
box_tab : 'Caxa',
border_tab : 'Ertza',
list_tab : 'Zerrendak',
positioning_tab : 'Kokapena',
text_props : 'Testua',
text_font : 'Letra-tipoa',
text_size : 'Tamaina',
text_weight : 'Pisua',
text_style : 'Estiloa',
text_variant : 'Aldaera',
text_lineheight : 'Lerro garaiera',
text_case : 'Minus./Maius.',
text_color : 'Kolorea',
text_decoration : 'Apaingarriak',
text_overline : 'Goimarra',
text_underline : 'Azpimarra',
text_striketrough : 'Marratua',
text_blink : 'Keinada',
text_none : 'Bat ere ez',
background_color : 'Atzeko kolorea',
background_image : 'Atzeko irudia',
background_repeat : 'Errepikatu',
background_attachment : 'Eranskina',
background_hpos : 'Posizio horizontala',
background_vpos : 'Posizio bertikala',
block_wordspacing : 'Hitz banaketa',
block_letterspacing : 'Letra banaketa',
block_vertical_alignment : 'Lerrokatze bertikala',
block_text_align : 'Testu lerrokatzea',
block_text_indent : 'Koska',
block_whitespace : 'Zuriunea',
block_display : 'Erakutsi',
box_width : 'Zabalera',
box_height : 'Altuera',
box_float : 'Flotatu',
box_clear : 'Garbitu',
padding : 'Padding',
same : 'Guztientzat berdina',
top : 'Gora',
right : 'Eskuina',
bottom : 'Behera',
left : 'Ezkerra',
margin : 'Margina',
style : 'Estiloa',
width : 'Zabalera',
height : 'Altuera',
color : 'Kolorea',
list_type : 'Mota',
bullet_image : 'Bulet-irudia',
position : 'Kokapena',
positioning_type : 'Mora',
visibility : 'Ikusgarritasuna',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Ubicaci\u00F3n',
clip : 'Klip'
});
