tinyMCE.addI18n('en.media_dlg',{list:_("List"),file:_("File/URL"),advanced:_("Advanced"),general:_("General"),title:_("Insert/Edit Embedded Media"),"align_top_left":_("Top Left"),"align_center":_("Center"),"align_left":_("Left"),"align_bottom":_("Bottom"),"align_right":_("Right"),"align_top":_("Top"),"qt_stream_warn":_("Streamed RTSP resources should be added to the QT Source field under the Advanced tab.\nYou should also add a non-streamed version to the Source field."),qtsrc:_("QT Source"),progress:_("Progress"),sound:_("Sound"),swstretchvalign:_("Stretch V-Align"),swstretchhalign:_("Stretch H-Align"),swstretchstyle:_("Stretch Style"),scriptcallbacks:_("Script Callbacks"),"align_top_right":_("Top Right"),uimode:_("UI Mode"),rate:_("Rate"),playcount:_("Play Count"),defaultframe:_("Default Frame"),currentposition:_("Current Position"),currentmarker:_("Current Marker"),captioningid:_("Captioning ID"),baseurl:_("Base URL"),balance:_("Balance"),windowlessvideo:_("Windowless Video"),stretchtofit:_("Stretch to Fit"),mute:_("Mute"),invokeurls:_("Invoke URLs"),fullscreen:_("Full Screen"),enabled:_("Enabled"),autostart:_("Auto Start"),volume:_("Volume"),target:_("Target"),qtsrcchokespeed:_("Choke Speed"),href:_("HREF"),endtime:_("End Time"),starttime:_("Start Time"),enablejavascript:_("Enable JavaScript"),correction:_("No Correction"),targetcache:_("Target Cache"),playeveryframe:_("Play Every Frame"),kioskmode:_("Kiosk Mode"),controller:_("Controller"),menu:_("Show Menu"),loop:_("Loop"),play:_("Auto Play"),hspace:_("H-Space"),vspace:_("V-Space"),"class_name":_("Class"),name:_("Name"),id:_("ID"),type:_("Type"),size:_("Dimensions"),preview:_("Preview"),"constrain_proportions":_("Constrain Proportions"),controls:_("Controls"),numloop:_("Num Loops"),console:_("Console"),cache:_("Cache"),autohref:_("Auto HREF"),liveconnect:_("SWLiveConnect"),flashvars:_("Flash Vars"),base:_("Base"),bgcolor:_("Background"),wmode:_("WMode"),salign:_("SAlign"),align:_("Align"),scale:_("Scale"),quality:_("Quality"),shuffle:_("Shuffle"),prefetch:_("Prefetch"),nojava:_("No Java"),maintainaspect:_("Maintain Aspect"),imagestatus:_("Image Status"),center:_("Center"),autogotourl:_("Auto Goto URL"),"shockwave_options":_("Shockwave Options"),"rmp_options":_("Real Media Player Options"),"wmp_options":_("Windows Media Player Options"),"qt_options":_("QuickTime Options"),"flash_options":_("Flash Options"),hidden:_("Hidden"),"align_bottom_left":_("Bottom Left"),"align_bottom_right":_("Bottom Right"),"html5_video_options":_("HTML5 Video Options"),altsource1:_("Alternative source 1"),altsource2:_("Alternative source 2"),preload:_("Preload"),poster:_("Poster"),source:_("Source"),"html5_audio_options":_("Audio Options"),"preload_none":_("Don\'t Preload"),"preload_metadata":_("Preload video metadata"),"preload_auto":_("Let user\'s browser decide"), "embedded_audio_options":_("Embedded Audio Options"), video:_("HTML5 video (ogv/ogg, webm, mp4)"), audio:_("HTML5 audio (mp3, ogg, wav)"), flash:_("Flash (swf, flv, mp3)"), quicktime:_("QuickTime (mov, mp4, mpeg)"), shockwave:_("Shockwave"), windowsmedia:_("Windows Media (wmv, wma)"), realmedia:_("Real Media (ram)"), iframe:_("Iframe"), embeddedaudio:_("Embedded Audio"),
// The New eXeLearning
selected_file : _("Selected file"),
html5_warning : _("HTML5 does not work in all browsers"),
recommended_type : _("Recommended type"),
confirm_question : _("Continue without changing your settings?"),
preview_error : _("Could not generate preview"),
video_download_file_warning : _("For Web browsers that do not support this video, a link to the video file will be displayed."),
audio_download_file_warning : _("For Web browsers that do not support this audio, a link to the audio file will be displayed."),
use_mediaelement : _("Use JavaScript player"),
"tab_caption":_("Header and Caption"),
"recognition":_("Title and Attribution"),
"header":_("Header"),
"media_title":_("Media Title"),
"media_title_link":_("Title Link"),
"author_name":_("Source/Author"),
"author_name_link":_("Source/Author Link"),
"caption_license":_("License"),
"caption_select_license":_("Choose a license..."),
"public_domain":_("Public Domain"),
"all_rights_reserved":_("All Rights Reserved"),
"caption_explanation":_("You will not be able to edit the header or the caption from this dialog."),
"caption_warning":_("The header and the caption can't be edited from this dialog. You can change or remove them editing the text itself."),
"use_autoplay": _("Use Autoplay"),
"use_controls": _("Use Controls"),
quicktime:_("QuickTime (mov, mpeg)")
// The New eXeLearning
}); 