// ES lang variables

tinyMCE.addI18n('es.exemath',{
desc : 'LaTeX a Math',
contextmenu_update : 'Propiedades de la imagen LaTeX Math',
generate_title : 'Imagen LaTeX Math para eXe',
verbose_font_size : 'Seleccione tama\u00F1o de fuente:', 
font_size : 'Tama\u00F1o de fuente:', 
compile_tooltip : 'Previsualizar imagen Math',
compile_label:  'Previsualizar',
latex_source : 'Introducir c\u00F3digo LaTeX:',
image_src : 'Imagen Math generada',
image_alt : 'Texto alternativo de la imagen:',
tab_general : 'Generador',
tab_appearance : 'Apariencia de la imagen',
insert_text: 'Contenido textual',
insert_newline: 'Nueva l\u00EDnea',
verbose_insert_symbols: 'Pinche para insertar el c\u00F3digo LaTeX de los s\u00EDmbolos:',
insert_symbols: ' ',
verbose_insert_latex: 'A\u00F1adir su propio c\u00F3digo LaTeX:',
general : 'General',
title : 'T\u00EDtulo',
preview : 'Previsualizaci\u00F3n de la imagen',
constrain_proportions : 'Restringir proporciones',
style : 'Estilo',
example_img : 'Imagen&nbsp;de&nbsp;previsualizaci\u00F3n',
press_preview_before_saving : 'Genera la imagen pulsando \u0022Previsualizar\u0022 antes de guardar',
inline_popups_plugin_is_required : 'El plugin \u0022inlinepopups\u0022 debe estar activado',
//advimage_dlg
"image_list": "Lista de imagen",
"align_right": "Derecha",
"align_left": "Izquierda",
"align_textbottom": "Texto abajo",
"align_texttop": "Texto arriba",
"align_bottom": "Debajo",
"align_middle": "Medio",
"align_top": "Arriba",
"align_baseline": "L\u00ednea base",
align: "Alineaci\u00f3n",
hspace: "Espacio horizontal",
vspace: "Espacio vertical",
dimensions: "Dimensiones",
border: "Bordes",
list: "Lista de imagen",
alt: "Descripci\u00f3n de la imagen",
src: "URL de la imagen",
"dialog_title": "Insertar/editar imagen",
"missing_alt": " \u00bfEst\u00E1 seguro de continuar sin introducir una descripci\u00f3n a la imagen? Sin ella puede no ser accesible para usuarios con discapacidades, o para aquellos que usen navegadores de modo texto, o tengan deshabilitadas las im\u00e1genes de la p\u00e1gina.",
"example_img": "Vista previa de la imagen",
misc: "Miscel\u00e1neo",
mouseout: "para mouseout",
mouseover: "para mouseover",
"alt_image": "Imagen alternativa",
"swap_image": "Intercambiar imagen",
map: "Mapa de imagen",
id: "Id",
rtl: "Derecha a izquierda",
ltr: "Izquierda a derecha",
classes: "Clases",
style: "Estilos",
"long_desc": "V\u00ednculo para descripci\u00f3n larga",
langcode: "C\u00f3digo del lenguaje",
langdir: "Direcci\u00f3n del lenguaje",
"constrain_proportions": "Bloquear relaci\u00f3n de aspecto",
preview: "Vista previa",
title: "T\u00edtulo",
general: "General",
"tab_advanced": "Avanzado",
"tab_appearance": "Apariencia",
"tab_general": "General",
width: "Ancho",
height: "Alto",
no_source_code_found : "No se ha encontrado el c\u00f3digo fuente.",
"missing_alt":"\u00bfEsta seguro de continuar sin introducir una descripci\u00f3n a la imagen? Sin ella puede no ser accesible para usuarios con discapacidades, o para aquellos que usen navegadores de modo texto, o tengan deshabilitadas las im\u00e1genes de la p\u00e1gina."
});