// FR lang variables

tinyMCE.addI18n('fr.exemath',{
desc : 'LaTeX \u00E0 Math',
contextmenu_update : 'Propri\u00E9t\u00E9s de l\'image LaTeX Math',
generate_title : 'Image LaTeX Math pour eXe',
verbose_font_size : 'S\u00E9lectionnez la taille de la police:', 
font_size : 'Taille de la police:', 
compile_tooltip : 'Pr\u00E9visualiser image Math',
compile_label:  'Pr\u00E9visualiser',
latex_source : 'Introduire code LaTeX:',
image_src : 'Image Math cr\u00E9\u00E9e',
image_alt : 'Texte alternatif de l\'image:',
tab_general : 'G\u00E9n\u00E9ral',
tab_appearance : 'Apparence',
insert_text: 'Contexte textuel',
insert_newline: 'Nouvelle ligne',
verbose_insert_symbols: 'Cliquer pour ins\u00E9rer le code LaTeX des symboles:',
insert_symbols: ' ',
verbose_insert_latex: 'Ajouter votre propre code LaTeX:',
general : 'G\u00E9n\u00E9ral',
title : 'Titre',
preview : 'Aper\u00E7u',
constrain_proportions : 'Bloquer la relation d\'aspect',
style : 'Styles',
example_img : 'Aper\u00E7u de l\'image',
press_preview_before_saving : 'Cr\u00E9er l\'image en cliquant sur \u0022Pr\u00E9visualiser\u0022 avant de sauvegarder',
inline_popups_plugin_is_required : 'Le plugin \u0022inlinepopups\u0022 doit \u00EAtre activ\u00E9',
//advimage_dlg
"image_list": "Liste d\'image",
"align_right": "Droite",
"align_left": "Gauche",
"align_textbottom": "Texte en bas",
"align_texttop": "Texte en haut",
"align_bottom": "Dessous",
"align_middle": "Au milieu",
"align_top": "En haut",
"align_baseline": "Ligne de base",
align: "Alignement",
hspace: "Espace horizontal",
vspace: "Espace vertical",
dimensions: "Dimensions",
border: "Bords",
list: "Liste d\'image",
alt: "Description de l\'image",
src: "URL de l\'image",
"dialog_title": "Ins\u00E9rer/\u00E9diter image",
"missing_alt": "\u00cates-vous s\u00fbr de vouloir continuer sans d\u00e9finir de description pour l\'image? Sans elle, l\'image peut ne pas \u00eatre accessible \u00e0 certains utilisateurs handicap\u00e9s, ceux utilisant un navigateur texte ou ceux qui naviguent sans affichage des images.",
misc: "Divers",
mouseout: "pour mouseout",
mouseover: "pour mouseover",
"alt_image": "Image alternative",
"swap_image": "\u00C9changer image",
map: "Carte image",
id: "Id",
rtl: "De droite \u00E0 gauche",
ltr: "De gauche \u00E0 droite",
classes: "Classes",
"long_desc": "Lien pour description longue",
langcode: "Code du langage",
langdir: "Direction du langage",
"tab_advanced": "Avanc\u00E9",
width: "Largeur",
height: "Hauteur",
no_source_code_found : "Le code source est introuvable"
});