// GL lang variables

tinyMCE.addI18n('gl.exemath',{
desc : 'LaTeX a Math',
contextmenu_update : 'Propiedades da imaxe LaTeX Math',
generate_title : 'Imaxe LaTeX Math para eXe',
verbose_font_size : 'Seleccione tama\u00F1o da fonte:', 
font_size : 'Tama\u00F1o da fonte:', 
compile_tooltip : 'Previsualizar imaxe Math',
compile_label:  'Previsualizar',
latex_source : 'Introducir c\u00F3digo LaTeX:',
image_src : 'Imaxe Math xerada',
image_alt : 'Texto alternativo da imaxe:',
tab_general : 'Xerador',
tab_appearance : 'Apariencia da imaxe',
insert_text: 'Contido textual',
insert_newline: 'Nova li\u00F1a',
verbose_insert_symbols: 'Clique para insertar o c\u00F3digo LaTeX dos s\u00EDmbolos:',
insert_symbols: ' ',
verbose_insert_latex: 'Engadir o propio c\u00F3digo LaTeX:',
general : 'Xeral',
title : 'T\u00EDtulo',
preview : 'Previsualizaci\u00F3n da imaxe',
constrain_proportions : 'Restrinxir proporci\u00F3ns',
style : 'Estilo',
example_img : 'Imaxe&nbsp;de&nbsp;previsualizaci\u00F3n',
press_preview_before_saving : 'Xera a imaxe premendo en \u0022Previsualizar\u0022 antes de gardar',
inline_popups_plugin_is_required : 'O plugin \u0022inlinepopus\u0022 debe estar activado',
//advimage_dlg
"image_list": "Lista de imaxe",
"align_right": "Dereita",
"align_left": "Esquerda",
"align_textbottom": "Texto abaixo",
"align_texttop": "Texto enriba",
"align_bottom": "Debaixo",
"align_middle": "Medio",
"align_top": "Enriba",
"align_baseline": "Li\u00F1a base",
align: "Ali\u00F1aci\u00F3n",
hspace: "Espazo horizontal",
vspace: "Espazo vertical",
dimensions: "Dimensi\u00F3ns",
border: "Bordes",
list: "Listaxe de imaxe",
alt: "Descrici\u00F3n da imaxe",
src: "URL da imaxe",
"dialog_title": "Insertar/editar imaxe",
"missing_alt": " Esta seguro de continuar sen introducir unha descrici\u00F3n da imaxe? Sen ela pode non ser accesible para usuarios con discapacidades, ou para aqueles que utilicen navegadores en modo texto, ou te\u00F1an deshabilitadas as imaxes da p\u00E1xina.",
"example_img": "Vista previa da imaxe",
misc: "Miscel\u00E1neo",
mouseout: "para mouseout",
mouseover: "para mouseover",
"alt_image": "Imaxe alternativa",
"swap_image": "Intercambiar imaxe",
map: "Mapa de imaxe",
id: "Id",
rtl: "Dereita a esquerda",
ltr: "Esquerda a dereita",
classes: "Clases",
style: "Estilos",
"long_desc": "V\u00EDnculo para descrici\u00F3n longa",
langcode: "C\u00F3digo da linguaxe",
langdir: "Direcci\u00F3n da linguaxe",
"constrain_proportions": "Bloquear relaci\u00F3n de aspecto",
preview: "Vista previa",
title: "T\u00EDtulo",
general: "Xeral",
"tab_advanced": "Avanzado",
"tab_appearance": "Apariencia",
"tab_general": "Xeral",
width: "Ancho",
height: "Alto",
no_source_code_found : "Non se atopou o c\u00F3digo fonte."
});