// IT lang variables

tinyMCE.addI18n('it.exemath',{
desc : 'LaTeX \u2192 Math',
contextmenu_update : 'Propriet\u00E0 dell\'immagine LaTeX Math',
generate_title : 'Immagine LaTeX Math per eXe',
verbose_font_size : 'Seleziona dimensioni dell\'originale:', 
font_size : 'Dimensioni originale:', 
compile_tooltip : 'Anteprima immagine Math',
compile_label:  'Anteprima',
latex_source : 'Inserire codice LaTeX:',
image_src : 'Immagine Math generata',
image_alt : 'Testo alternativo immagine:',
tab_general : 'Generale',
tab_appearance : 'Aspetto',
insert_text: 'Contenuto testuale',
insert_newline: 'Nuova riga',
verbose_insert_symbols: 'Clic per inserire il codice LaTeX dei simboli:',
insert_symbols: ' ',
verbose_insert_latex: 'Aggiungere il proprio codice LaTeX:',
general : 'Generale',
title : 'Titolo',
style : 'Stilo',
example_img : 'Vista&nbsp;precedente&nbsp;immagine',
press_preview_before_saving : 'Genera l\'immagine cliccando \u0022Anteprima\u0022 prima di salvare',
inline_popups_plugin_is_required : 'Il plugin \u0022inlinepopups\u0022 deve essere attivato',
//advimage_dlg
"image_list": "Lista di immagini",
"align_right": "Destra",
"align_left": "Sinistra",
"align_textbottom": "Testo sotto",
"align_texttop": "Testo sopra",
"align_bottom": "Sotto",
"align_middle": "Centro",
"align_top": "Sopra",
"align_baseline": "Linea base",
align: "Allineamento",
hspace: "Spazio orizzontale",
vspace: "Spazio verticale",
dimensions: "Dimensioni",
border: "Bordi",
list: "Lista di immagini",
alt: "Descrizione dell\'immagine",
src: "URL immagine",
"dialog_title": "Inserire/modificare immagine",
"missing_alt": "Sicuro di continuare senza includere una descrizione dell\'immagine? Senza di essa l\'immagine pu\u00f2 non essere accessibile ad alcuni utenti con disabilit\u00e0, o per coloro che usano un browser testuale oppure che hanno disabilitato la visualizzazione delle immagini nel loro browser.",
"example_img": "Vista precedente",
misc: "Varie",
mouseout: "per mouseout",
mouseover: "per mouseover",
"alt_image": "Immagine alternativa",
"swap_image": "Cambiare immagine",
map: "Mappa immagine",
id: "Id",
rtl: "Da destra a sinistra",
ltr: "Da sinistra a destra",
classes: "Classi",
"long_desc": "Link per descrizione lunga",
langcode: "Codice della lingua",
langdir: "Direzione della lingua",
"constrain_proportions": "Mantieni proporzioni",
preview: "Anteprima",
"tab_advanced": "Avanzato",
width: "Larghezza",
height: "Altezza",
no_source_code_found : "Codice sorgente non trovato."
});