// NL lang variables

tinyMCE.addI18n('nl.exemath',{
desc : 'LaTeX to Math for eXe',
contextmenu_update : 'LaTeX Math Image properties',
generate_title : 'eXe LaTeX Math Image',
verbose_font_size : 'Select a font size:', 
font_size : 'Font size:', 
compile_tooltip : 'Preview Math Image',
compile_label:  'Preview',
latex_source : 'Input LaTeX source:',
image_src : 'generated Math Image',
image_alt : 'Math Image description<br>(optional ALT tag):',
tab_general : 'eXe Math: Generate',
tab_appearance : 'eXe Math: Image Appearance',
insert_text: 'verbatim text',
insert_newline: 'new line',
verbose_insert_symbols: 'Click below to insert LaTeX for any of the following symbols:',
insert_symbols: ' ',
verbose_insert_latex: 'And, add your own LaTeX directly into the following:',
constrain_proportions : 'Constrain proportions',
style : 'Style',
example_img : 'Appearance&nbsp;preview&nbsp;image',
press_preview_before_saving : 'Create the image by clicking \u0022Preview\u0022 before saving',
inline_popups_plugin_is_required : 'The plugin \u0022inlinepopups\u0022 must be enabled',
//advimage_dlg
"image_list": "Image List",
"align_right": "Right",
"align_left": "Left",
"align_textbottom": "Text Bottom",
"align_texttop": "Text Top",
"align_bottom": "Bottom",
"align_middle": "Middle",
"align_top": "Top",
"align_baseline": "Baseline",
align: "Alignment",
hspace: "Horizontal Space",
vspace: "Vertical Space",
dimensions: "Dimensions",
border: "Border",
list: "Image List",
alt: "Image Description",
src: "Image URL",
"dialog_title": "Insert/Edit Image",
"missing_alt": "Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
"example_img": "Appearance Preview Image",
misc: "Miscellaneous",
mouseout: "For Mouse Out",
mouseover: "For Mouse Over",
"alt_image": "Alternative Image",
"swap_image": "Swap Image",
map: "Image Map",
id: "ID",
rtl: "Right to Left",
ltr: "Left to Right",
classes: "Classes",
style: "Style",
"long_desc": "Long Description Link",
langcode: "Language Code",
langdir: "Language Direction",
"constrain_proportions": "Constrain Proportions",
preview: "Preview",
title: "Title",
general: "General",
"tab_advanced": "Advanced",
"tab_appearance": "Appearance",
"tab_general": "General",
width: "Width",
height: "Height",
no_source_code_found : "No source code found.",
"missing_alt":"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off."
});