// NL lang variables

tinyMCE.addI18n('nl.exemath',{
desc : 'LaTex naar Math voor eXe',
contextmenu_update : 'LaTex Math Afbeeldingseigenschappen',
generate_title : 'eXe LaTex Math afbeelding',
verbose_font_size : 'Kies een tekengrootte:', 
font_size : 'Tekengrootte:', 
compile_tooltip : 'Voorbeeldweergave Math afbeelding',
compile_label:  'Voorbeeldweergave',
latex_source : 'Voorbeeldweergave:',
image_src : 'Aangemaakte Math afbeelding',
image_alt : 'Beschrijving Math afbeelding<br />(optional ALT tag):',
tab_general : 'Algemeen',
tab_appearance : 'Weergave',
insert_text: 'letterlijke tekst',
insert_newline: 'nieuwe regel',
verbose_insert_symbols: 'Klik hieronder om LaTex in te voegen voor een van de volgende symbolen:',
insert_symbols: ' ',
verbose_insert_latex: 'En, voeg je eigen LaTex aan het volgende toe:',
constrain_proportions : 'Verhoudingen beperken',
style : 'Stijl',
example_img : 'Weergave&nbsp;Voorbeeld&nbsp;afbeelding',
press_preview_before_saving : 'Maak de afbeelding aan door voor opslaan op \u0022Voorbeeldweergave\u0022 te klikken',
inline_popups_plugin_is_required : 'Th plugin \u0022inlinepopups\u0022 moet geactiveerd zijn',
//advimage_dlg
"image_list": "Lijst met afbeeldingen",
"align_right": "Rechts",
"align_left": "Links",
"align_textbottom": "Onderkant tekst",
"align_texttop": "Bovenkant tekst",
"align_bottom": "Onderkant",
"align_middle": "Midden",
"align_top": "Bovenkant",
"align_baseline": "Hoofdlijn",
align: "Uitlijnen",
hspace: "Horizontale ruimte",
vspace: "verticale ruimte",
dimensions: "Afmetingen",
border: "Rand",
list: "Lijst met afbeeldingen",
alt: "Beschrijving van de afbeelding",
src: "URL van de afbeelding",
"dialog_title": "Voeg in/bewerk afbeelding",
"missing_alt": "Weet je zeker dat je wilt doorgaan zonder beschrijving van de afbeelding? Zonder beschrijving is de afbeelding wellicht niet toegankelijk voor sommige gebruikers met een handicap of gebruikers van een text-browser of gebruikers die afbeeldings weergave hebben uitgeschakeld.",
"example_img": "Voorbeeldweergave",
misc: "Diverse",
mouseout: "Voor MouseOut",
mouseover: "Voor MouseOver",
"alt_image": "Alternatieve afbeelding",
"swap_image": "Verwissel afbeelding",
map: "Afbeeling met hyperlinks",
id: "ID",
rtl: "Rechts naar Links",
ltr: "Links naar rechts",
classes: "Klassen",
"long_desc": "Volledige (lange) link",
langcode: "Taalcode",
langdir: "Taal richting",
"constrain_proportions": "Constrain Proportions",
preview: "Voorbeeldweergave",
title: "Titel",
general: "Algemene",
"tab_advanced": "Geavanceerd",
"tab_general": "Algemene",
width: "Breedte",
height: "Hoogte",
no_source_code_found : "Geen broncode gevonden."
});