// PT lang variables

tinyMCE.addI18n('pt.exemath',{
desc : 'De LaTeX para Math',
contextmenu_update : 'Propriedades da imagem LaTeX',
generate_title : 'Imagem LaTeX Math para eXe',
verbose_font_size : 'Selecione tamanho da fonte:', 
font_size : 'Tamanho da fonte:', 
compile_tooltip : 'Pr\u00E9-visualizar imagem Math',
compile_label:  'Pr\u00E9-visualizar',
latex_source : 'Introduzir c\u00F3digo LaTeX:',
image_src : 'Imagem Math gerada',
image_alt : 'Texto alternativo da imagem:',
tab_general : 'Geral',
tab_appearance : 'Apar\u00EAncia',
insert_text: 'Conte\u00FAdo textual',
insert_newline: 'Nova linha',
verbose_insert_symbols: 'Clique para inserir o c\u00F3digo LaTeX dos s\u00EDmbolos:',
insert_symbols: ' ',
verbose_insert_latex: 'Acrescente o seu pr\u00F3prio c\u00F3digo LaTeX:',
general : 'Geral',
title : 'T\u00EDtulo',
preview : 'Pr\u00E9-visualiza\u00E7\u00E3o',
constrain_proportions : 'Bloquear rela\u00E7\u00E3o de aspeto',
style : 'Estilos',
example_img : 'Pr\u00E9-visualiza\u00E7\u00E3o&nbsp;da&nbsp;imagem',
press_preview_before_saving : 'Gera a imagem se clicar em \u0022Pr\u00E9-visualizar\u0022 antes de guardar',
inline_popups_plugin_is_required : 'O plugin \u0022inlinepopups\u0022 deve estar ativado',
//advimage_dlg
"image_list": "Lista de imagem",
"align_right": "Direita",
"align_left": "Esquerda",
"align_textbottom": "Texto em baixo",
"align_texttop": "Texto por cima",
"align_bottom": "Por baixo",
"align_middle": "No meio",
"align_top": "Por cima",
"align_baseline": "Linha base",
align: "Alinhamento",
hspace: "Espa\u00E7o horizontal",
vspace: "Espa\u00E7o vertical",
dimensions: "Dimens\u00F5es",
border: "Contornos",
list: "Lista de imagem",
alt: "Descri\u00E7\u00E3o da imagem",
src: "URL da imagem",
"dialog_title": "Inserir/editar imagem",
"missing_alt": "Tem certeza que deseja continuar sem acrescentar uma descri\u00e7\u00e3o \u00e0 imagem? (Isto pode gerar problemas de acessibilidade em alguns navegadores)",
"example_img": "Pr\u00E9-visualiza\u00E7\u00E3o",
misc: "Miscel\u00E2nea",
mouseout: "para mouseout",
mouseover: "para mouseover",
"alt_image": "Imagem alternativa",
"swap_image": "Trocar imagem",
map: "Mapa de imagem",
id: "Id",
rtl: "Da direita para a esquerda",
ltr: "Da esquerda para a direita",
classes: "Classes",
"long_desc": "Liga\u00E7\u00E3o para descri\u00E7\u00E3o comprida",
langcode: "C\u00F3digo da l\u00EDngua",
langdir: "Sentido da escrita na l\u00EDngua",
"tab_advanced": "Avan\u00E7ado",
width: "Largura",
height: "Altura",
no_source_code_found : "N\u00E3o foi encontrado o c\u00F3digo fonte."
});