// UK lang variables

tinyMCE.addI18n('en.exemath',{
desc : _('LaTeX to Math for eXe'),
contextmenu_update : _('LaTeX Math Image properties'),
generate_title : _('eXe LaTeX Math Image'),
verbose_font_size : _('Select a font size:'), 
font_size : _('Font size:'), 
compile_tooltip : _('Preview Math Image'),
compile_label:  _('Preview'),
latex_source : _('Input LaTeX source:'),
image_src : _('generated Math Image'),
image_alt : _('Math Image description<br>(optional ALT tag):'),
tab_general : _('eXe Math: Generate'),
tab_appearance : _('eXe Math: Image Appearance'),
insert_text: _('verbatim text'),
insert_newline: _('new line'),
verbose_insert_symbols: _('Click below to insert LaTeX for any of the following symbols:'),
insert_symbols: ' ',
verbose_insert_latex: _('And, add your own LaTeX directly into the following:'),
constrain_proportions : _('Constrain proportions'),
style : _('Style'),
example_img : _('Appearance&nbsp;preview&nbsp;image'),
press_preview_before_saving : _('Create the image by clicking \u0022Preview\u0022 before saving'),
inline_popups_plugin_is_required : _('The plugin \u0022inlinepopups\u0022 must be enabled'),
//advimage_dlg
"image_list": _("Image List"),
"align_right": _("Right"),
"align_left": _("Left"),
"align_textbottom": _("Text Bottom"),
"align_texttop": _("Text Top"),
"align_bottom": _("Bottom"),
"align_middle": _("Middle"),
"align_top": _("Top"),
"align_baseline": _("Baseline"),
align: _("Alignment"),
hspace: _("Horizontal Space"),
vspace: _("Vertical Space"),
dimensions: _("Dimensions"),
border: _("Border"),
list: _("Image List"),
alt: _("Image Description"),
src: _("Image URL"),
"dialog_title": _("Insert/Edit Image"),
"missing_alt": _("Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off."),
"example_img": _("Appearance Preview Image"),
misc: _("Miscellaneous"),
mouseout: _("For Mouse Out"),
mouseover: _("For Mouse Over"),
"alt_image": _("Alternative Image"),
"swap_image": _("Swap Image"),
map: _("Image Map"),
id: _("ID"),
rtl: _("Right to Left"),
ltr: _("Left to Right"),
classes: _("Classes"),
style: _("Style"),
"long_desc": _("Long Description Link"),
langcode: _("Language Code"),
langdir: _("Language Direction"),
"constrain_proportions": _("Constrain Proportions"),
preview: _("Preview"),
title: _("Title"),
general: _("General"),
"tab_advanced": _("Advanced"),
"tab_appearance": _("Appearance"),
"tab_general": _("General"),
width: _("Width"),
height: _("Height"),
no_source_code_found : _("No source code found."),
"missing_alt":_("Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.")
});