import os

Import('env dist install installDir')

pys = [
    'pyxpcom_test_tools.py',
    'test_com_exceptions.py',
    'test_isupports_primitives.py',
    'test_streams.py',
    'test_test_component.py',
    'regrtest.py',
    'test_comfile.py',
    'test_components.py',
    'test_misc.py',
    'test_weakreferences.py',
    ]

pycs = map(env.Pyc, pys)
pyos = map(env.Pyo, pys)
allPyFiles = pys + pycs + pyos

dist += env.Install('#dist/xpcom/test/', allPyFiles)
install += env.Install(os.path.join(installDir, 'xpcom', 'test'), allPyFiles)

dist += env.Install('#dist/xpcom/test/', 'test_test_component.js')
install += env.Install(os.path.join(installDir, 'xpcom', 'test'), 'test_test_component.js')
    
SConscript('test_component/SConscript')
