#!/usr/bin/python
# ===========================================================================
# eXe
# Copyright 2004-2005, University of Auckland
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# ===========================================================================

"""
eXe main script
"""

import os
import os.path
import sys
from getopt import getopt, GetoptError
from exe.engine.config       import Config
from exe.webui.webserver     import WebServer
from exe.webui.browser       import launchBrowser
from exe.engine.packagestore import g_packageStore
from exe.engine import version
import logging
import gettext
_   = gettext.gettext
 
log = logging.getLogger(__name__)

def main():
    """
    Main function, starts eXe
    """
    # Process args
    try:
        options, packages = getopt(sys.argv[1:], "hV", ["help", "version"])
    except GetoptError:
        usage()
        sys.exit(2)

    for option, arg in options:
        if option in ("-V", "--version"):
            print "eXe", version.version
            sys.exit()
        if option in ("-h", "--help"):
            usage()
            sys.exit()

    # Get configuration
    configFile = "exe.conf"
    if sys.platform[:3] == "win":
        from exe.engine.winconfig import WinConfig
        config = WinConfig(configFile)

    elif sys.platform[:6] == "darwin":
        from exe.engine.macconfig import MacConfig
        config = MacConfig(configFile)

    else:
        from exe.engine.linuxconfig import LinuxConfig
        config = LinuxConfig(configFile)

    config.loadSettings()
    config.setupLogging("exe.log")
    config.loadStyles()
    g_config = config
    
    # Start user interface
    launchBrowser(config)

    print "Welcome to eXe: the eLearning XML editor"
    log.info("eXe running...")
    
    server = WebServer(config)
    server.run()


def usage():
    """
    Print usage info
    """
    print "Usage: "+os.path.basename(sys.argv[0])+" [OPTION] PACKAGE"
    print "  -V, --version    print version information and exit"
    print "  -h, --help       display this help and exit"
    print "Settings are read from exe.conf"
    print "in $HOME/.exe on Linux/Unix or"
    print "in Documents and Settings\\<user>\\Application Data\\exe on Windows"



if __name__ == "__main__":
    main()
