// ES lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrita (Ctrl+B)',
italic_desc : 'Cursiva (Ctrl+I)',
underline_desc : 'Subrayado (Ctrl+U)',
striketrough_desc : 'Tachado',
justifyleft_desc : 'Izquierda',
justifycenter_desc : 'Centrado',
justifyright_desc : 'Derecha',
justifyfull_desc : 'Justificado',
bullist_desc : 'Lista',
numlist_desc : 'Lista numerada',
outdent_desc : 'Eliminar indentado',
indent_desc : 'Indentar',
undo_desc : 'Deshacer (Ctrl+Z)',
redo_desc : 'Rehacer (Ctrl+Y)',
link_desc : 'A\u00F1adir/Editar enlace',
unlink_desc : 'Quitar enlace',
image_desc : 'Insertar/Editar imagen',
cleanup_desc : 'Limpiar c\u00F3digo',
focus_alert : 'Una instancia del editor debe estar seleccionada para usar este comando.',
edit_confirm : '\u00BFUsar el modo WYSIWYG en este textarea?',
insert_link_title : 'A\u00F1adir/Editar enlace',
insert : 'Insertar',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL del enlace',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir en la misma ventana',
insert_link_target_blank : 'Abrir en ventana nueva',
insert_image_title : 'Insertar/Editar imagen',
insert_image_src : 'URL de la imagen',
insert_image_alt : 'Descripci\u00F3n imagen',
help_desc : 'Ayuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Pegar no est\u00E1 disponible en este navegador.\n\u00BFM\u00E1s informaci\u00F3n?',
popup_blocked : 'Un programa est\u00E1 bloqueando la apertura de popups. Debe deshabilitarlo para poder utilizar el editor correctamente.'
});
