// ES lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrita (Ctrl+B)',
italic_desc : 'Cursiva (Ctrl+I)',
underline_desc : 'Subrayado (Ctrl+U)',
striketrough_desc : 'Tachado',
justifyleft_desc : 'Izquierda',
justifycenter_desc : 'Centrado',
justifyright_desc : 'Derecha',
justifyfull_desc : 'Justificado',
bullist_desc : 'Lista',
numlist_desc : 'Lista numerada',
outdent_desc : 'Eliminar sangr&iacute;a',
indent_desc : 'Indentar',
 : 'Deshacer (Ctrl+Z)',
redo_desc : 'Rehacer (Ctrl+Y)',
link_desc : 'A&ntilde;adir/Editar enlace',
unlink_desc : 'Quitar enlace',
image_desc : 'A&ntilde;adir/Editar imagen',
cleanup_desc : 'Limpiar c&oacute;digo',
focus_alert : 'Una instancia del editor debe estar seleccionada para usar este comando.',
edit_confirm : '&iquest;Usar el modo WYSIWYG en este textarea?',
insert_link_title : 'A&ntilde;adir/Editar enlace',
insert : 'Insertar',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL del enlace',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir en la misma ventana',
insert_link_target_blank : 'Abrir en ventana nueva',
insert_image_title : 'A&ntilde;adir/Editar imagen',
insert_image_src : 'URL de la imagen',
insert_image_alt : 'Descripci&oacute;n imagen',
help_desc : 'Ayuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Pegar no est&aacute; disponible en este navegador.\n&iquest;M&aacute;s informaci&oacute;n?',
popup_blocked : 'Un programa est&aacute; bloqueando la apertura de popups. Debe deshabilitarlo para poder utilizar el editor correctamente.'
});
