// JR
// ES lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrita (Ctrl+B)',
italic_desc : 'Cursiva (Ctrl+I)',
underline_desc : 'Subrayado (Ctrl+U)',
striketrough_desc : 'Tachado',
justifyleft_desc : 'Alinear a la izquierda',
justifycenter_desc : 'Centrar',
justifyright_desc : 'Alinear a la derecha',
justifyfull_desc : 'Justificar',
bullist_desc : 'Lista desordenada',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Reducir sangría',
indent_desc : 'Aumentar sangría',
undo_desc : 'Deshacer (Ctrl+Z)',
redo_desc : 'Rehacer (Ctrl+Y)',
link_desc : 'Insertar/editar enlace',
unlink_desc : 'Romper enlace',
image_desc : 'Insertar/editar imagen',
cleanup_desc : 'Limpiar código basura',
focus_alert : 'A editor instance must be focused before using this command.',
edit_confirm : '¿Desea utilizar el modo WYSIWYG para esta caja de texto?',
insert_link_title : 'Insertar/editar enlace',
insert : 'Insertar',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'Enlazar URL',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir enlace en la misma ventana',
insert_link_target_blank : 'Abrir enlace en una nueva ventana',
insert_image_title : 'Insertar/editar imagen',
insert_image_src : 'URL de la imagen',
insert_image_alt : 'Descripción de la imagen',
help_desc : 'Ayuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Pegar no se encuentra disponible en Mozilla y Firefox.\n ¿Quiere más información sobre este tema?',
popup_blocked : 'Lo sentimos, su bloqueo de ventanas emergentes ha deshabilitado una ventana que provee funcionalidades a la aplicación. Necesita deshabilitar este bloqueo en este sitio para poder utilizar todas las funciones.'
});
