// EU lang variables

tinyMCE.addToLang('',{
bold_desc : 'Beltza (Ctrl+B)',
italic_desc : 'Etzana (Ctrl+I)',
underline_desc : 'Azpimarratua (Ctrl+U)',
striketrough_desc : 'Gainetik marra duena',
justifyleft_desc : 'Ezkerrean alineatu',
justifycenter_desc : 'Erdian zentratu',
justifyright_desc : 'Eskuinean alineatu',
justifyfull_desc : 'Testua justifikatu',
bullist_desc : 'Zerrenda',
numlist_desc : 'Zerrenda ordenatua',
outdent_desc : 'Koska kendu',
indent_desc : 'Koska gehitu',
undo_desc : 'Desegin (Ctrl+Z)',
redo_desc : 'Berregin (Ctrl+Y)',
link_desc : 'Lotura txertatu/editatu',
unlink_desc : 'Lotura kendu',
image_desc : 'Irudia txertatu/editatu',
cleanup_desc : 'Kode zikina garbitu',
focus_alert : 'Editorearen instantzia bat aukeratuta egon behar da komando hau erabiltzeko.',
edit_confirm : 'Testu-kutxa hau WYSIWYG editorea izatea nahi duzu?',
insert_link_title : 'Lotura txertatu/editatu',
insert : 'Txertatu',
update : 'Eguneratu',
cancel : 'Utzi',
insert_link_url : 'Loturaren URLa',
insert_link_target : 'Helburua',
insert_link_target_same : 'Lotura leiho berean ireki',
insert_link_target_blank : 'Lotura leiho berrian ireki',
insert_image_title : 'Irudia txertatu/editatu',
insert_image_src : 'Irudiaren URLa',
insert_image_alt : 'Irudiaren deskribapena',
help_desc : 'Laguntza',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Kopiatu/Ebaki/Itsatsi ez dago Mozilla eta Firefoxen.\nHonen inguruko informazioa nahi duzu?',
popup_blocked : 'Ups, zure popup blokeatzaileak funtzionalitate bat eskaintzen duen leihoa blokeatu du. Blokeatzailea desgaitu beharko duzu tresna hau erabiltzeko.'
});
