// ES lang variables

tinyMCE.addToLang('fullpage',{
	title: "Propiedades del documento",
	desc : 'Propiedades del documento',
	meta_tab : 'General',
	appearance_tab : 'Apariencia',
	advanced_tab : 'Avanzado',
	meta_props : 'Meta informaci&oacute;n',
	langprops : 'Lenguaje y codificaci&oacute;n',
	meta_title : 'T&iacute;tulo',
	meta_keywords : 'Palabras clave',
	meta_description : 'Descripci&oacute;n',
	meta_robots : 'Robots',
	doctypes : 'Doctype',
	langcode : 'C&oacute;digo idioma',
	langdir : 'Direcci&oacute;n',
	ltr : 'Izquierda a derecha',
	rtl : 'Derecha a izquierda',
	xml_pi : 'Declaraci&oacute;n XML',
	encoding : 'Codificaci&oacute;n de caracteres',
	appearance_bgprops : 'Propiedades del fondo',
	appearance_marginprops : 'M&aacute;rgenes cuerpo',
	appearance_linkprops : 'Colores enlaces',
	appearance_textprops : 'Propiedades del texto',
	bgcolor : 'Color de fondo',
	bgimage : 'Imagen de fondo',
	left_margin : 'Margen izquierdo',
	right_margin : 'Margen derecho',
	top_margin : 'Margen superior',
	bottom_margin : 'Margen inferior',
	text_color : 'Color de texto',
	font_size : 'Tama&ntilde;o fuente',
	font_face : 'Familia fuente',
	link_color : 'Color enlace',
	hover_color : 'Color rat&oacute;n encima',
	visited_color : 'Color visitado',
	active_color : 'Color activo',
	textcolor : 'Color',
	fontsize : 'Tama&ntilde;o fuente',
	fontface : 'Familia fuente',
	meta_index_follow : 'Indexar y seguir los enlaces',
	meta_index_nofollow : 'Indexar y no seguir los enlaces',
	meta_noindex_follow : 'No indexar pero seguir los enlaces',
	meta_noindex_nofollow : 'No indexar y no seguir los enlaces',
	appearance_style : 'Hoja de estilo y propiedades de estilo',
	stylesheet : 'Hoja de estilo',
	style : 'Estilo',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'A&ntilde;adir elemento',
	remove : 'Eliminar elemento seleccionado',
	moveup : 'Mover seleccionado hacia arriba',
	movedown : 'Mover seleccionado hacia abajo',
	head_elements : 'Elementos cabecera',
	info : 'Informaci&oacute;n',
	info_text : '',
	add_title : 'T&iacute;tulo',
	add_meta : 'Meta',
	add_script : 'Script',
	add_style : 'Estilo',
	add_link : 'Link',
	add_base : 'Base',
	add_comment : 'Comentario',
	title_element : 'T&iacute;tulo',
	script_element : 'Script',
	style_element : 'Style',
	base_element : 'Base',
	link_element : 'Link',
	meta_element : 'Meta',
	comment_element : 'Comentario',
	src : 'Src',
	language : 'Language',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Type',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Media',
	properties : 'Propiedades',
	name : 'Nombre',
	value : 'Valor',
	content : 'Contenido',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'General',
	advanced_props : 'Avanzado',
	delta_width : 0,
	delta_height : 0
});
