Import('env dist install installDir PYTHON_VER')

sourceFiles = [
    'ErrorUtils.cpp',
    'PyGBase.cpp',
    'PyGModule.cpp',
    'PyGStub.cpp',
    'PyGInputStream.cpp',
    'PyGWeakReference.cpp',
    'PyIClassInfo.cpp',
    'PyIComponentManager.cpp',
    'PyIComponentManagerObsolete.cpp',
    'PyIInputStream.cpp',
    'PyIEnumerator.cpp',
    'PyIID.cpp',
    'PyIInterfaceInfo.cpp',
    'PyIInterfaceInfoManager.cpp',
    'PyISimpleEnumerator.cpp',
    'PyISupports.cpp',
    'PyIVariant.cpp',
    'Pyxpt_info.cpp',
    'TypeObject.cpp',
    'VariantUtils.cpp',
    'dllmain.cpp',
    'xpcom.cpp']

includes = ['PyXPCOM.h', 'PyXPCOM_std.h']

# Build
xpcom = env.SharedLibrary('_xpcom', sourceFiles, LIBS=['xpcom', 'python%s' % PYTHON_VER])
# Here we just use the includes, to force cvs to get them
env.Command('#$source', includes, includes)
env.Depends(xpcom, includes)
dist += env.Install('#dist', xpcom)
install += env.Install(installDir, xpcom)

# Make the loader
env.Export('xpcom')
SConscript('loader/SConscript')
