import os

Import('env dist install installDir PYTHON_VER')

sourceFiles = [
    'ErrorUtils.cpp',
    'PyGBase.cpp',
    'PyGInputStream.cpp',
    'PyGModule.cpp',
    'PyGStub.cpp',
    'PyGWeakReference.cpp',
    'PyIClassInfo.cpp',
    'PyIComponentManager.cpp',
    'PyIEnumerator.cpp',
    'PyIID.cpp',
    'PyIInputStream.cpp',
    'PyIInterfaceInfo.cpp',
    'PyIInterfaceInfoManager.cpp',
    'PyISimpleEnumerator.cpp',
    'PyISupports.cpp',
    'PyIVariant.cpp',
    'Pyxpt_info.cpp',
    'TypeObject.cpp',
    'VariantUtils.cpp',
    'dllmain.cpp',
    ]

includes = ['PyXPCOM.h', 'PyXPCOM_std.h', 'readme.html']

LIBS = ['python%s' % PYTHON_VER, 'xpcom', 'xpcom_core', 'plds4', 'plc4', 'nspr4', 'pthread', 'dl', 'm', 'python2.4']

# Build

_xpcomDeps = env.Object(sourceFiles, LIBS=LIBS)

# Here we just use the includes, to force cvs to get them
#env.Command('', includes, includes)
env.Depends(_xpcomDeps, includes)

# Make the module
env.Export('_xpcomDeps')
env.SConscript('module/SConscript')

# Make the loader
env.SConscript('loader/SConscript')

