# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1165800059);
user_pref("app.update.lastUpdateTime.background-update-timer", 1165800058);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1165800059);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1165800064);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("capability.principal.codebase.p0.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p0.id", "http://127.0.0.1:8081");
user_pref("capability.principal.codebase.p0.subjectName", "");
user_pref("capability.principal.codebase.p1.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p1.id", "http://127.0.0.1:51235");
user_pref("capability.principal.codebase.p1.subjectName", "");
user_pref("capability.principal.codebase.p2.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p2.id", "http://127.0.0.1:51236");
user_pref("capability.principal.codebase.p2.subjectName", "");
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.popup_allowed_events", "change click dblclick mouseup reset submit keypress contextmenu");
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.checkCompatibility", false);
user_pref("extensions.ignoreMTimeChanges", true);
user_pref("extensions.lastAppVersion", "2.0.0.6");
user_pref("extensions.update.autoUpdateEnabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.interval", 63072000);
user_pref("extensions.update.lastUpdateDate", 1339539111);
user_pref("general.open_location.last_url", "about:config");
user_pref("general.open_location.last_window_choice", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("security.warn_submit_insecure", false);
user_pref("signed.applets.codebase_principal_support", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/getkey?client=navclient-auto-ffox2.0&", 1165886465);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.14444");
user_pref("urlclassifier.tableversion.goog-black-url", "1.7417");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.18");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("capability.policy.policynames", "allowclipboard");
user_pref("capability.policy.allowclipboard.sites", "http://127.0.0.1:8081 http://127.0.0.1:51235 http://127.0.0.1:51236");
user_pref("capability.policy.allowclipboard.Clipboard.cutcopy", "allAccess");
user_pref("capability.policy.allowclipboard.Clipboard.paste", "allAccess");
