# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1165800059);
user_pref("app.update.lastUpdateTime.background-update-timer", 1323111483);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1165800059);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1323111140);
user_pref("avg.toolbar.first_installation", false);
user_pref("browser.EULA.override", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 256000);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.search.update", false);
user_pref("browser.tabs.autoHide", true);
user_pref("capability.policy.allowclipboard.Clipboard.cutcopy", "allAccess");
user_pref("capability.policy.allowclipboard.Clipboard.paste", "allAccess");
user_pref("capability.policy.allowclipboard.sites", "http://127.0.0.1:8081 http://127.0.0.1:51235 http://127.0.0.1:51236");
user_pref("capability.policy.policynames", "allowclipboard");
user_pref("capability.principal.codebase.p0.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p0.id", "http://127.0.0.1:8081");
user_pref("capability.principal.codebase.p0.subjectName", "");
user_pref("capability.principal.codebase.p1.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p1.id", "http://127.0.0.1:51235");
user_pref("capability.principal.codebase.p1.subjectName", "");
user_pref("capability.principal.codebase.p2.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p2.id", "http://127.0.0.1:51236");
user_pref("capability.principal.codebase.p2.subjectName", "");
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.disable_open_during_load", false);
user_pref("dom.disable_window_open_feature.status", false);
user_pref("dom.popup_allowed_events", "change click dblclick mouseup reset submit keypress contextmenu");
user_pref("extensions.autoDisableScopes", 14);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.checkCompatibility", false);
user_pref("extensions.checkCompatibility.3.6", false);
user_pref("extensions.checkCompatibility.4.0", false);
user_pref("extensions.checkCompatibility.5.0", false);
user_pref("extensions.checkCompatibility.6.0", false);
user_pref("extensions.checkCompatibility.7.0", false);
user_pref("extensions.checkCompatibility.8.0", false);
user_pref("extensions.checkCompatibility.9.0", false);
user_pref("extensions.checkCompatibility.10.0", false);
user_pref("extensions.checkCompatibility.11.0", false);
user_pref("extensions.checkCompatibility.12.0", false);
user_pref("extensions.checkUpdateSecurity", false);
user_pref("extensions.ignoreMTimeChanges", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.autoUpdate", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.update.autoUpdateEnabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.interval", 63072000);
user_pref("extensions.update.lastUpdateDate", 1339539111);
user_pref("extensions.update.notifyUser", false);
user_pref("general.open_location.last_url", "about:config");
user_pref("general.open_location.last_window_choice", 0);
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 42938);
user_pref("plugin.default_plugin_disabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.prefs.sync.extensions.update.enabled", false);
user_pref("signed.applets.codebase_principal_support", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("toolkit.telemetry.prompted", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/getkey?client=navclient-auto-ffox2.0&", 1165886465);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1325703575);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.14444");
user_pref("urlclassifier.tableversion.goog-black-url", "1.7417");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.18");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
