name: build-macos

on: [push]

jobs:
  build-macos:
    runs-on: macos-10.15

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      PYTHON_CONFIGURE_OPTS: --enable-shared
      DEVELOPER_DIR: /Applications/Xcode_10.3.app/Contents/Developer
      SDKROOT: /Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install brew system libraries
        run: |

          brew install libtiff libjpeg webp little-cms2
          brew install libxml2

      # For compatibility with macos <=10.14, we are using system 2.7.18 python.
      # With this version, openssl 1.0 system libs are backwards compatible.
      # Please look at versions previous  to 2022-07-01 if you need a different python version installed with pyenv,
      # or a newer openssl > 1.0.
      # We could have an action workflow for <=10.14  with system python, and a workflow for >=10.15 with custom python and openssl.
      # At present we are using this action for all versions.
      - name: Install Python requirements
        run: |
          pip install lxml==2.2.8
          pip install py2app==0.25
          pip install Pillow==5.3.0
          pip install zope.interface
          pip install chardet
          pip install gitpython
          pip install suds
          pip install requests-oauthlib
          pip install python-dateutil
          pip install httplib2
          pip install beautifulsoup4
          pip install feedparser
          pip install oauthlib
          pip install webassets
          pip install cssmin

      - name: Create disk image
        run: hdiutil create -volname exe -size 500m -layout GPTSPUD -fs 'Journaled HFS+' -type UDIF installs/osx/exe

      - name: Build package
        run: |
          brew install npm
          echo "--> Installing appdmg" 
          npm install -g appdmg
          which appdmg
          echo "--> Installing appdmg" 
          npm install  appdmg
          which appdmg
          ls -l /usr/local/bin/appdmg
          cd installs/osx
          echo "--> Creating python app and DMG image..."
          python make.py -p

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe-macos
          path: installs/osx/INTEF-exe-*.dmg